### ISSUE TITLE
[Nhóm#6]  Lỗi không truy cập được trang - ở trang https://trading.tabbook.vn/

### ISSUE THREAD

**Issue by 31191021871** [UEHMonQAQC/BI_K45#104]
a. Web browsers: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang https://trading.tabbook.vn/
ii.#2: Đăng nhập tài khoản 
ii.#3: Chọn mục tài khoản của tôi 
![image](https://user-images.githubusercontent.com/92736076/140387661-e8af89d8-f39c-472b-b06d-854a2f8a5e21.png)
iv. #4: Trong mục tài khoản của tôi tiếp tục chọn mục tài khoản của tôi 
![image](https://user-images.githubusercontent.com/92736076/140387879-0a729d32-5314-42f5-9e36-14e2f3da537d.png)
c. Kết quả thực tế: Không truy cập được vào trang
![image](https://user-images.githubusercontent.com/92736076/140387416-8e8551b6-095d-48ab-bc2b-0e3cfe1b1328.png)
d. Kết quả mong đợi: Truy cập vào được trang tài khoản của tôi

**Comment by 31191024332** [comment]
trùng với #341
