### ISSUE TITLE
[Nhóm#4] Kết quả Search không đúng thứ tự - trang https://digital.lib.ueh.edu.vn/

### ISSUE THREAD

**Issue by thanhha02621** [UEHMonQAQC/BI_K45#107]
a. Web Browser: Google Chrome: Phiên bản 95.0.4638.69 (Phiên bản Chính thức) (64 bit)                          
b. Các bước để phát hiện lỗi:                        
i. #1: Vào trang chủ Digital Library: https://digital.lib.ueh.edu.vn/     
![2 1 (3)](https://user-images.githubusercontent.com/87024797/140388345-67aadd8f-2485-4807-955f-fe7d41b493b5.jpg)
ii. #2: Chỗ thanh Search nhập "Giáo trình Luật kinh doanh" 
![Capture111](https://user-images.githubusercontent.com/87024797/140389557-f011d421-a6ed-43fb-b109-9b121d440d76.PNG)  
iii. #3: Xem kết quả
![Capture333](https://user-images.githubusercontent.com/87024797/140390264-fbaac93b-c004-4fd4-99aa-ec43be865e0d.PNG)
                
c. Kết quả thực tế: Hiển thị "Giáo trình Luật kinh doanh" ở vị trí thứ 3        
d. Kết quả mong đợi: Hiển thị "Giáo trình Luật kinh doanh" ở vị trí đầu tiên

**Comment by 31191022164** [comment]
Lỗi này mình xác nhận không phải lỗi chức năng nhé, vì search có ra kết quả và việc sắp xếp này họ có thể sắp xếp theo yêu cầu, mong muốn riêng chứ không nhất thiết phải theo thứ tự chính xác từ trên xuống. @31191026753
