### ISSUE TITLE
[Nhóm#5] Lỗi không đồng nhất căn lề của các hình ảnh có trong bài viết - trang https://youth.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191021279** [UEHMonQAQC/BI_K45#115]
a. Web Browser: Opera 81.0.4196.31
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web: https://youth.ueh.edu.vn
![image](https://user-images.githubusercontent.com/92701347/140440361-783d602d-a600-44d3-b67b-dc91b0a13c7d.png)
ii. #2: Tại mục Sinh viên 5 tốt, chọn như hình minh họa
![khdongnhatcanhinh](https://user-images.githubusercontent.com/92701347/140443063-6d077761-e674-4fa6-9d5f-ecff5fa4fb16.png)
iii. #3: Chọn bài viết như hình:
![chonbaiviet](https://user-images.githubusercontent.com/92701347/140443164-c1f14915-29f3-41a5-a6f0-d8748c26ff9f.png)
iv. #4: Xem nội dung bài viết
![lech](https://user-images.githubusercontent.com/92701347/140443878-0bd1b54d-15f2-432a-94d8-6d8c896f67b5.png)
![lech2](https://user-images.githubusercontent.com/92701347/140444131-f8fcfde4-ebf2-40f1-8b3b-cfa409c667a8.png)
![lech3](https://user-images.githubusercontent.com/92701347/140444241-f2690e2f-8417-4ce2-9047-f90e842b49e4.png)
![lech4](https://user-images.githubusercontent.com/92701347/140444399-333bb8d7-5e25-43af-92ca-18aa42aaac40.png)
c. Kết quả thực tế: các hình ảnh bị lệch nhau, không thẳng hàng
d. Kết quả mong đợi: các hình ảnh được đồng nhất căn lề, thẳng hàng nhau

**Comment by 31191024332** [comment]
Hi Nhóm,
Đây là lỗi format văn bản hông phải lỗi giao diện. Mình không xác nhận lỗi này được nhé. Nhóm kiểm tra lại giúp mình.
Cảm ơn Nhóm 5
