### ISSUE TITLE
[Nhóm#8] Kết quả search không đúng - trang https://boho.com.vn/

### ISSUE THREAD

**Issue by 31181022919** [UEHMonQAQC/BI_K45#116]
a. Web Browser: Google Chrome: Phiên bản 95.0.4638.69 (Phiên bản Chính thức) (64 bit)
b. Các bước để phát hiện lỗi:
i. #1: Vào trang chủ BOHO: https://boho.com.vn/
![image](https://user-images.githubusercontent.com/92730093/140454064-0683c684-0051-49fe-99e0-c95e36cf4ddb.png)
ii. #2: Chỗ thanh Search nhập "Bắc Âu"
![image](https://user-images.githubusercontent.com/92730093/140454156-c9616dab-6650-4801-a39e-03600f28e9b0.png)
iii. #3: Nhấn Enter hoặc biểu tượng kính lúp để thực hiện search. Xem kết quả:
![image](https://user-images.githubusercontent.com/92730093/140454209-b629bd1b-54b7-4ac6-9f88-16d1104967fe.png)
c. Kết quả thực tế: Hiển thị "Không tìm thấy sản phẩm nào khớp với lựa chọn của bạn."
d. Kết quả mong đợi: Hiển thị các sản phẩm với từ khóa "Bắc Âu" đã điền vào thanh tìm kiếm

**Comment by hieeusnguyeenx** [comment]
!! Lỗi không hợp lệ.
Vẫn tìm được sản phẩm theo từ khóa "Bắc Âu" nhé. 
![image](https://user-images.githubusercontent.com/87801356/140460316-e8d7f105-4f47-4387-a29a-6478cb3728aa.png)
![image](https://user-images.githubusercontent.com/87801356/140460349-7da0f995-43db-4aa4-9665-7c75935f6e9a.png)
