### ISSUE TITLE
[Nhóm#5] Navigation bar bị xuất hiện lặp lại đề mục khi dùng chức năng xem Đợt thi - trang https://youth.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191021279** [UEHMonQAQC/BI_K45#119]
a. Web Browser: Opera 81.0.4196.31
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web: https://youth.ueh.edu.vn
![image](https://user-images.githubusercontent.com/92701347/140440361-783d602d-a600-44d3-b67b-dc91b0a13c7d.png)
ii. #2: Tại mục Chức năng -> chọn Hệ thống mã vạch
![laplai](https://user-images.githubusercontent.com/92701347/140447023-44af9317-5519-42ff-b5db-02903c90c8b4.png)
iii. #3: Tiến hành chọn như hình sau:
![ktrantsv](https://user-images.githubusercontent.com/92701347/140447306-75892432-9f3f-4793-bd00-24b27c93fea9.png)
iv. #4: Đăng nhập bằng tài khoản student của trường
![laplainhieu](https://user-images.githubusercontent.com/92701347/140447921-5d403145-dc76-4734-ad41-da2c831c8858.png)
v. #5: Chọn mục Thí sinh cao điểm -> chọn 1 đợt thi cần xem và bấm button Xem 
![thisinhcaodiem](https://user-images.githubusercontent.com/92701347/140448032-9ab03e7c-273b-44da-b195-6ff6823f195f.png)
![dotthicanxem1](https://user-images.githubusercontent.com/92701347/140448325-d36dfbe1-d90d-4353-8cdd-d4e952623269.png)
![bilap](https://user-images.githubusercontent.com/92701347/140448585-cb89e2b1-2230-419e-9110-7ff0f4a9c39f.png)
vi. #6: Tiếp tục bấm button Xem ( ví dụ: 3 lần) 
![navlaptiep](https://user-images.githubusercontent.com/92701347/140448776-b82c1521-a1e6-41d0-8232-0d8c7e9a4044.png)
c. Kết quả thực tế:  navigation bar bị xuất hiện lặp lại đề mục khi thực hiện xem Đợt thi
d. Kết quả mong đợi: navigation bar không bị xuất hiện lặp lại đề mục khi xem Đợt thi

**Comment by 31191024332** [comment]
Domain name của trang ghi lỗi không thuộc youth.ueh.edu.vn nên mình không xác nhận lỗi này nhé. Cảm ơn nhóm
