### ISSUE TITLE
[Nhóm#6] Lỗi bảo mật - trang https://shcd.ueh.edu.vn/

### ISSUE THREAD

**Issue by huongptt23** [UEHMonQAQC/BI_K45#12]
a. Web Browser: Google Chrome Windows 10
b. Các bước phát hiện lỗi
i. #1: Truy cập vào trang https://shcd.ueh.edu.vn/
ii. #2: Kéo xuống mục "Thành viên trên mạng" và chọn 1 bạn sinh viên K45
![6](https://user-images.githubusercontent.com/92672213/139823155-e3f4faab-1150-4dff-b761-6193dc75ae82.png)
iii. #3: Hiển thị thông tin người dùng
![7](https://user-images.githubusercontent.com/92672213/139823271-0ca9d774-11b3-4745-af07-27ba9b70d46c.png)
c. Kết quả thực tế: Có thể xem được thông tin của sinh viên khác
![7](https://user-images.githubusercontent.com/92672213/139822727-0da6601a-19c4-42a4-8af4-a9194174ab57.png)
d. Kết quả mong đợi: Không thể tìm được thông tin của sinh viên khác
![image](https://user-images.githubusercontent.com/92672213/139822982-74753b67-9de7-4ed7-8599-52f7d5e9a3e3.png)

**Comment by 31191024332** [comment]
Đây là chức năng được cho phép coi nên không tính là phi chức năng được. Nhóm kiểm tra lại giúp mình nha
