### ISSUE TITLE
[Nhóm#10] Lỗi kích cỡ quá nhỏ - Trang https://www.cooky.vn

### ISSUE THREAD

**Issue by 31191026529** [UEHMonQAQC/BI_K45#129]
a. Web Browser:  Opera GX version 80.0.4170.86
b. Các bước phát hiện ra lỗi:
 i. #1 Truy cập vào trang web https://www.cooky.vn
![image](https://user-images.githubusercontent.com/83526024/140458759-bf752694-1300-403c-9b24-e8559881c3f1.png)
 ii. #2 Kéo xuống chọn trang công thức
![image](https://user-images.githubusercontent.com/83526024/140458856-2accd60f-b9d0-406e-800e-fa3a2e4b8450.png)
 iii. #3 Chọn wiki
![image](https://user-images.githubusercontent.com/83526024/140458982-3900cf80-4e5b-4cc6-8606-698389408a52.png)
 iv. #4 Kéo xuống để xem
![image](https://user-images.githubusercontent.com/83526024/140459062-e201a1d3-0a31-438b-8715-ab508b33cfb1.png)
c. Kết quả thực tế: dòng chữ xem thêm quá nhỏ
d. Kết quả mong đợi: dòng chữ xem thêm có kích cỡ bằng các chữ khác trên trang.

**Comment by 31191025698** [comment]
Đây không phải là lỗi.
