### ISSUE TITLE
[Nhóm#8] Lỗi hiển thị không đúng số bình luận trên bài đăng - Trang https://boho.com.vn/

### ISSUE THREAD

**Issue by 31181022919** [UEHMonQAQC/BI_K45#134]
a. Web Browser: Google Chrome: Phiên bản 95.0.4638.69 (Phiên bản Chính thức) (64 bit)
b. Các bước để phát hiện lỗi:
i. #1: Vào trang chủ BOHO: https://boho.com.vn/
![image](https://user-images.githubusercontent.com/92730093/140463677-0bafe6bd-0610-4ab8-b1b5-ade99100a2bf.png)
ii.#2: Nhấn vào "Gợi ý chọn tranh" để vào giao diện các bài đăng của web.
![image](https://user-images.githubusercontent.com/92730093/140463727-50e91447-a701-4b57-9c22-bde2f2d6e97b.png)
iii.#3: Chọn để vào 1 bài đăng bất kỳ.
![image](https://user-images.githubusercontent.com/92730093/140463939-6d2056ea-2e3c-4fd4-b821-03f014bc2075.png)
iv.#4: Kéo xuống mục "Trả lời" để bình luận bài đăng:
![image](https://user-images.githubusercontent.com/92730093/140464275-6a4f1acc-ab7e-43e7-ad2a-2170e0921039.png)
v.#5:Điền thông tin và nhấn nút "Phản hồi" để lưu bình luận:
![image](https://user-images.githubusercontent.com/92730093/140464377-cddbee3b-c4e2-48e2-ae6a-fa05776a3f6a.png)
c Kết quả thực tế: Hiển thị phía trên bình luận vừa lưu :"0 THOUGHTS ON 10 BỨC TRANH TREO TƯỜNG PHONG CẢNH CỦA HỌA SĨ NỔI TIẾNG STANISLAW WILK”
d Kết quả mong đợi: Hiển thị phía trên bình luận vừa lưu :"1 THOUGHTS ON 10 BỨC TRANH TREO TƯỜNG PHONG CẢNH CỦA HỌA SĨ NỔI TIẾNG STANISLAW WILK”

**Comment by hieeusnguyeenx** [comment]
@31181022919 
Ở đây có dòng bình luận đang được xác minh nên chưa được accept là 1 bình luận nên đây không phải lỗi nhé. Nếu nhóm tìm được minh chứng cụ thể hơn hoặc bình luận của nhóm được accept mà vẫn bị lỗi này thì nhóm gửi lên đây để mình xác nhận lỗi nhé.
![image](https://user-images.githubusercontent.com/87801356/140552956-e3934f4d-ca61-4807-aef4-61f30ea1310e.png)
