### ISSUE TITLE
[Nhóm#8]  Hiệu suất load trang không đạt - Trang http://global.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181022919** [UEHMonQAQC/BI_K45#135]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập trang https://developers.google.com/speed/pagespeed/insights/
![image](https://user-images.githubusercontent.com/92730093/140476509-34da85c4-3895-4806-a084-e786b04a717a.png)
ii. #2: Nhập địa chỉ của trang http://global.ueh.edu.vn/ vào và ấn nút "PHÂN TÍCH"
![image](https://user-images.githubusercontent.com/92730093/140476707-c3289e66-24b1-48bf-9245-5e22c4e703d8.png)
iii. #3: Chọn "thiết bị di động" và "máy tính để bàn" để xem kết quả.
![image](https://user-images.githubusercontent.com/92730093/140477301-a000e154-6a04-4f50-8ada-1e701cf8f3ce.png)
![image](https://user-images.githubusercontent.com/92730093/140477362-0ecffbf0-8aae-469d-8772-6cd551ffbf21.png)
c. Kết quả thực tế: Tốc độ phản hồi ở thiết bị di động là 35% và Tốc độ phản hồi ở máy tính là 51%
d. Kết quả mong đợi: Trang sẽ được cải thiện về tốc độ phản hồi để người dùng sử dụng nhanh hơn (trên 90%)

**Comment by hieeusnguyeenx** [comment]
@31181022919 
 Như Thầy vừa xác nhận ở tiết học thì đây không phải là lỗi nhé.

**Comment by 31181022919** [comment]
mình có nghe thầy rồi, mình cảm ơn bạn nhé ^^
