### ISSUE TITLE
[Nhóm#5] Chức năng share sản phẩm lên facebook bị lỗi - trang https://nhasachlaptrinh.tk

### ISSUE THREAD

**Issue by 31191021279** [UEHMonQAQC/BI_K45#136]
a. Web Browser: Opera 81.0.4196.31
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web: https://nhasachlaptrinh.tk
![image](https://user-images.githubusercontent.com/92701347/140479854-98514fd1-128c-4eb4-b745-8ad5e8349fb4.png)
ii. #2: Chọn sản phẩm như hình:
![kshare](https://user-images.githubusercontent.com/92701347/140480496-e87a890e-45bc-483b-9092-2457dd6e295d.png)
iii. #3: Click chọn button share sản phảm
![nopeshare](https://user-images.githubusercontent.com/92701347/140480648-3cfa57b7-f248-4043-b98d-70ab94453262.png)
![noshare](https://user-images.githubusercontent.com/92701347/140480781-d384aaa0-37be-4bcc-8e29-236cf4ae8510.png)
c. Kết quả thực tế: không thể share sản phẩm lên facebook
d. Kết quả mong đợi: share được sản phẩm lên facebook

**Comment by 31191024332** [comment]
Đây không phải lỗi CN do liên quan tới chính sách kiểm duyệt nội dung của Facebook. Mình xin phép không xác nhận lỗi này. Cảm ơn nhóm
