### ISSUE TITLE
[Nhóm#2] Lặp lại nội dung 2 lần – trang https://student.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191020293** [UEHMonQAQC/BI_K45#14]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước để phát hiện lỗi:
i. #1: Đăng nhập vào trang: https://student.ueh.edu.vn/ 
![Screenshot (1485)](https://user-images.githubusercontent.com/92731317/139837569-2d4e161d-e952-4539-bcb5-fd79337bf8cf.png)
ii. #2: Bên thanh tra cứu thông tin chọn "Học phần tương đương".
![Screenshot (1486)](https://user-images.githubusercontent.com/92731317/139837585-985a1e02-4dcb-40c2-ae1e-1126ac81c3e1.png)
iii. #3: Màn hình hiển thị:
![Screenshot (1487)](https://user-images.githubusercontent.com/92731317/139837607-d456db75-ef13-44ac-941d-a18431a3db23.png)
c. Kết quả thực tế: Chữ học phần xuất hiện hai lần trong cùng một khung
d. Kết quả mong đợi: Chỉ hiển thị một chữ "học phần" trong bảng này

**Comment by hieeusnguyeenx** [comment]
Mục đích của phần này là có 2 chữ học phần nên đây không phải lỗi.
