### ISSUE TITLE
[Nhóm#10] Lỗi bảo mật thông tin và hình ảnh thí sinh - Trang https://dsa.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191026600** [UEHMonQAQC/BI_K45#142]
a. Google Chrome: Phiên bản 95.0.4638.69
b.Các bước phát hiện lỗi 
i. #1 Truy cập vào trang web : https://dsa.ueh.edu.vn/
Chọn Công tác sinh viên -> Chọn Sự kiện cho người học -> Chọn Đăng ký hoạt động
![loi1](https://user-images.githubusercontent.com/92784090/140545349-24a902d8-fa0f-4629-af1b-2cd03875c504.PNG)
ii. #2 Chọn Xem danh sách đăng ký
![loi1 2](https://user-images.githubusercontent.com/92784090/140545593-7ea9fed7-f7fa-4e5b-893c-039615b382a4.PNG)
![LOI1 3](https://user-images.githubusercontent.com/92784090/140545668-d8f5f5ff-026b-4ccb-a951-49491696a7fc.PNG)
c. Kết quả thực tế: Lộ thông tin và hình ảnh thí sinh.
d. Kết quả mong đợi: Thông tin và hình ảnh thí sinh được bảo mật.

**Comment by 31191025698** [comment]
Như thầy có nói trong buổi 06/11, lỗi bảo mật thông tin được chấp nhận khi thông tin đó web không cho xem nhưng vẫn xem được, còn trong trường hợp này là ý của dsa.
@31191026600
