### ISSUE TITLE
[Nhóm#8] Lỗi không đồng nhất cỡ chữ - trang https://global.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191026190** [UEHMonQAQC/BI_K45#148]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140551931-432799ce-f7e8-4543-856c-cdbcca12de3d.png)
ii. #2 Đăng nhập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140552138-508220cd-1c2f-489a-af35-984ca6da55d8.png)
iii. #3 Nhấp vào tên người dùng ở góc phải, chọn Tùy chọn:
![image](https://user-images.githubusercontent.com/92732798/140552348-ab1cc58f-7946-41e6-9f72-cf35500bf45d.png)
iv. #4 Chọn biểu tượng 3 gạch ở góc trái màn hình để mở thanh hiển thị điều hướng:
![image](https://user-images.githubusercontent.com/92732798/140554335-ee85c295-b302-40e3-a5a3-76ca26ded45a.png)
v. #5 Chọn mục Các trang của hệ thống và nhấp vào Thẻ:
![image](https://user-images.githubusercontent.com/92732798/140554625-77375153-5443-4461-8a4c-486becf59dfe.png)
vi. #6 Xem kết quả hiển thị:
![image](https://user-images.githubusercontent.com/92732798/140554826-69f95ed7-ff82-468a-9995-a09471100559.png)
c. Kết quả thực tế: Không đồng nhất với nhau về cỡ chữ
d. Kết quả mong đợi: Chữ hiển thị được đồng nhất về cỡ chữ

**Comment by hieeusnguyeenx** [comment]
@31191026190 có thể trang web chỉ muốn hiện các thẻ nhu vậy thôi nên không phải lỗi nhé.
