### ISSUE TITLE
[Nhóm#8] Liên kết trong trang không hoạt động - Trang https://global.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191026190** [UEHMonQAQC/BI_K45#149]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140551931-432799ce-f7e8-4543-856c-cdbcca12de3d.png)
ii. #2 Đăng nhập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140552138-508220cd-1c2f-489a-af35-984ca6da55d8.png)
iii. #3 Nhấp vào tên người dùng ở góc phải, chọn Tùy chọn:
![image](https://user-images.githubusercontent.com/92732798/140552348-ab1cc58f-7946-41e6-9f72-cf35500bf45d.png)
iv. #4 Chọn biểu tượng 3 gạch ở góc trái màn hình để mở thanh hiển thị điều hướng:
![image](https://user-images.githubusercontent.com/92732798/140554335-ee85c295-b302-40e3-a5a3-76ca26ded45a.png)
v. #5 Chọn mục Các trang của hệ thống và nhấp vào Các blog trang:
![image](https://user-images.githubusercontent.com/92732798/140556303-3706d2c0-f088-442a-9ceb-a302d7283a87.png)
vi. #6 Nhấp vào Liên kết tĩnh:
![image](https://user-images.githubusercontent.com/92732798/140556123-74812eb1-8ed9-449b-92a6-841c031ae1d5.png)
vii. #7 Nhấp vào Liên kết tĩnh:
![image](https://user-images.githubusercontent.com/92732798/140556391-3753689e-64ff-4956-a35d-827b5e5831d8.png)
c. Kết quả thực tế: Màn hình không chuyển sang trang tiếp theo  và vẫn ở giao diện mặc định
d. Kết quả mong đợi: Chuyển sang trang tiếp theo.

**Comment by hieeusnguyeenx** [comment]
Giao diện có chuyển đến trang của bài viết nên đây không phải lỗi nhé.
