### ISSUE TITLE
[Nhóm#2] Lỗi bảo mật lịch sử tìm kiếm - trang https://www.phuot.vn/

### ISSUE THREAD

**Issue by 31191024056** [UEHMonQAQC/BI_K45#155]
a. Web Browser: Google Chrome 95.0.4638.69  
b. Các bước để phát hiện lỗi
i. #1 Truy cập trang https://www.phuot.vn/
![image](https://user-images.githubusercontent.com/92562222/140619633-c1488e24-f84f-4c93-a2a6-335421ed1f19.png)
ii. #2 Đăng ký và đăng nhập vào trang phượt
![Untitled Diagram drawio (3)](https://user-images.githubusercontent.com/92562222/140619701-071cdecb-56aa-4ff8-9067-3e985831be91.png)
iii. #3 nhấn vào khung tìm kiếm và nhấn tìm kiếm từ khóa bất kỳ
![Untitled Diagram drawio (5)](https://user-images.githubusercontent.com/92562222/140620065-28cd3c07-f72b-4f5d-9a45-e2a5b08f5ca5.png)
iv. #4 Đăng xuất khỏi tài khoản
![image](https://user-images.githubusercontent.com/92562222/140619810-3b9090e0-fa7e-44e9-95ae-7c0e9173a25a.png)
v. #5 Đăng nhập vào bằng tài khoản mail khác
![Untitled Diagram drawio (3)](https://user-images.githubusercontent.com/92562222/140619706-52c156c2-9b2e-4e4f-95b3-dad871279ab5.png)
vi. #6 Nhấn vào khung tìm kiếm
![Untitled Diagram drawio (4)](https://user-images.githubusercontent.com/92562222/140619980-fd6dd9e8-3a10-44e9-ad36-ae72f4cb4c85.png)
c. Kết quả thực tế: lịch sử tìm kiếm 2 tài khoản giống nhau
d. Kết quả mong đợi: lịch sử tìm kiếm của 2 tài khoản phải khác nhau

**Comment by hieeusnguyeenx** [comment]
Mình xác nhận lỗi này. 
Nhưng đây không phải lỗi bảo mật lịch sử tìm kiếm nhé. Hiện tại, bạn đang thao tác trên google nên trang web đề xuất theo cache của google. Do đó mỗi máy sẽ có mỗi đề xuất khác nhau và các tài khoản trên cùng 1 máy sẽ có đè xuất giống nhau. 
Bạn có thể thử bằng cách dùng một máy khác hoặc dùng một trình duyệt khác để test, bạn cũng có thể test bằng cách xóa cache của google.
@31191024056
