### ISSUE TITLE
[Nhóm#10] Lỗi không hiện được hình ảnh trong trang "Đăng công thức" - Trang https://www.cooky.vn

### ISSUE THREAD

**Issue by 31191023135** [UEHMonQAQC/BI_K45#160]
a.Web Browser: Chrome Version 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1 Truy cập vào trang web https://www.cooky.vn
![image](https://user-images.githubusercontent.com/92784013/140757823-72b09508-190d-4f54-9f2b-0a9e1c060569.png)
ii. #2 Truy cập vào Giới thiệu
![image](https://user-images.githubusercontent.com/92784013/140758036-8e53503e-0aca-4dd5-9822-0123eaca01d8.png)
iii. #3 Truy cập vào Đăng công thức
![image](https://user-images.githubusercontent.com/92784013/140758276-0dec326a-b332-438d-b8e3-706516aaf52e.png)
c. Kết quả thực tế: Bị lỗi hình ảnh
![image](https://user-images.githubusercontent.com/92784013/140758517-a0bf900c-772a-4ed9-82f3-460d8a490c07.png)
d. Kết quả mong đợi: Hiện hình ảnh

**Comment by 31191025698** [comment]
Trang vẫn hiển thị các hình ảnh mặc định. Lỗi thuộc về quản trị website không cập nhật hình. Không chấp nhận lỗi.

**Comment by 31191025698** [comment]
@31191023135 
Nhóm có phản biện gì không?
Nếu không mình sẽ close issue.
