### ISSUE TITLE
[Nhóm#10] Lỗi không hiện Banner trên trang chủ của điện thoại - Trang https://www.cooky.vn

### ISSUE THREAD

**Issue by 31191023135** [UEHMonQAQC/BI_K45#162]
a.Web Browser: Chrome Version 95.0.4638.69, điện thoại iphone 11
b. Các bước phát hiện ra lỗi:
i. #1 Truy cập vào trang web https://www.cooky.vn
![image](https://user-images.githubusercontent.com/92784013/140769288-4adf4131-f134-4ed1-a321-b413b3474580.png)
c. Kết quả thực tế: Lỗi ảnh banner ở phần Header
d. Kết quả mong đợi: Hiện ảnh banner

**Comment by 31191025698** [comment]
Đây là Safari không phải Chrome.
(QA không có IPhone 11 :(((((( )

**Comment by 31191025698** [comment]
Không đủ minh bạch
QA xin phép close issue.
