### ISSUE TITLE
[Nhóm#7] Nội dung "CGV" hiển thị trên Tab bị sai lệch với chuẩn- Trang https://www.cgv.vn/

### ISSUE THREAD

**Issue by 31191027399** [UEHMonQAQC/BI_K45#170]
a. Web Browser: Microsoft Edge 95.0.1020.40, Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi
i.#1: Truy cập vào trang https://www.cgv.vn/, kéo xuống khu vực dưới cùng của trang web
![image](https://user-images.githubusercontent.com/92789962/140794154-3c474556-1849-444b-ae3c-a917ca22b6f2.png)
ii.#2: Chọn mục "Tiện Ích Online" 
![image](https://user-images.githubusercontent.com/92789962/140794380-af249859-b7a1-467d-9470-3a902b93c057.png)
iii.#3: Hệ thống chuyển đến trang https://www.cgv.vn/default/cgv-online/, Tên "CGV" hiển thị trên 2 Tabs có sự sai lệch với nhau
![image](https://user-images.githubusercontent.com/92789962/140798760-e7825698-67ce-49f5-9647-75d8d3d85e9a.png)
c. Kết quả thực tế :  Nội dung "CGV" trên tên Tab của trang https://www.cgv.vn/default/cgv-online/ được hiển thị là "Cgv"
d. Kết quả mong đợi: Nội dung "CGV" luôn được giữ nguyên cách viết in hoa toàn bộ trên tên Tab của trang

**Comment by 31191027399** [comment]
Nhóm đã cập nhật lại mô tả, phần c với d đúng với format chuẩn

**Comment by 31191026515** [comment]
Cái này chỉ là lỗi khi các bạn cầm trên tay cái bản thiết kế + requirement mà thôi. Vì cái này là do yêu cầu của khách hàng.
