### ISSUE TITLE
[Nhóm#2] Lỗi chức năng đăng kí chuyển điểm - Trang https://student.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191020008** [UEHMonQAQC/BI_K45#175]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://student.ueh.edu.vn/Home
![image](https://user-images.githubusercontent.com/92733147/140888521-1d8f37ba-9935-48e4-86f5-aa467eb00065.png)
ii. #2: Đăng nhập vào trang web
![image](https://user-images.githubusercontent.com/92733147/140888572-7d4d6da7-bc3f-4b59-97d8-0ec155959e85.png)
iii. #3: Chọn trang Nộp chứng chỉ
![image](https://user-images.githubusercontent.com/92733147/140888863-2299f7cb-ea11-4635-b0ce-573994823350.png)
iv. #4: Lướt xuống phía dưới có nút Đăng kí chuyển điểm
![image](https://user-images.githubusercontent.com/92733147/140889062-c614948c-fb65-4f21-aefc-40bfe5566735.png)
v. #5: Ấn chọn nút Đăng kí chuyển điểm, web hiển thị thông báo và chọn nút Đăng kí
![image](https://user-images.githubusercontent.com/92733147/140889202-2ed4a726-0581-4200-831b-705e4acf8e98.png)
vi. #5: Màn hình hiển thị thông báo 
![image](https://user-images.githubusercontent.com/92733147/140889334-4bbb464a-636f-4185-ab26-22e31376df11.png)
c. Kết quả thực tế: Màn hình hiển thị thông báo Thao tác thành công
d. Kết quả mong muốn: Trả về thông báo báo lỗi do không nhập bất kì dữ liệu nào trước khi chọn nút đăng kí

**Comment by hieeusnguyeenx** [comment]
@31191020008 về chứng chỉ quốc phòng thì đâu đổi được sang môn nào đâu, còn ở đây là thể hiện thao tác thành công là việc bạn đăng ký thành công, và thông tin sẽ đưa đến một bên khác xem xét, nên là có thể họ không ràng buộc ở bước này. 
Nếu bạn tìm được trường hợp cụ thể hơn thì mình sẽ xác nhận nhé. Cảm ơn !
