### ISSUE TITLE
[Nhóm#7] Button không hoạt động - Trang https://www.cgv.vn/

### ISSUE THREAD

**Issue by 31191024882** [UEHMonQAQC/BI_K45#180]
a. Web Browser: Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi
i.#1: Truy cập vào trang https://www.cgv.vn/ 
![2021-11-09](https://user-images.githubusercontent.com/41457211/140958862-1afa2e4d-6b4a-454e-8712-b2c53b971be2.png)
ii.#2: Chọn mục phim -> phim đang chiếu
![2021-11-09 (1)](https://user-images.githubusercontent.com/41457211/140958777-a8a2b8af-2805-4521-86d4-814ff6c40d53.png)
iii.#3: Chọn phim
![2021-11-09 (2)](https://user-images.githubusercontent.com/41457211/140958972-07f8351d-0acf-428d-9e5d-fbefdf8d5312.png)
c. Kết quả thực tế: Không có gì xảy ra
d. Kết quả được mong đợi: Quay về trang danh sách phim

**Comment by 31191026515** [comment]
Mình không xác nhận lỗi này nhé. Mình thao tác thì vẫn ra nha!
![image](https://user-images.githubusercontent.com/92660305/142201984-3c2cf44a-c67a-4b54-b4aa-a5959d49fa1a.png)
