### ISSUE TITLE
[Nhóm#9] Thiếu kí tự * bên cạnh trường bắt buộc – trang https://phonhadat.net/

### ISSUE THREAD

**Issue by 31191026463** [UEHMonQAQC/BI_K45#189]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://phonhadat.net/
![image](https://user-images.githubusercontent.com/92785792/141137279-e61f0044-14bd-496f-8f76-6d25295bd5ed.png)
ii. #2: Đăng nhập sau đó chọn chức năng đăng tin
![11 - 1](https://user-images.githubusercontent.com/92785792/141138923-093ba9a6-7e94-4458-84b9-8e4aecb735b9.PNG)
iii. #3: Tại LỊCH ĐĂNG TIN, xóa ngày bắt đầu và ngày kết thúc
![11-2](https://user-images.githubusercontent.com/92785792/141139537-7cabb9ad-190c-4d5b-b754-4469b92a2187.PNG)
iv. #4: Cuộn trang xuống dưới và bấm chọn đăng tin
![11-3](https://user-images.githubusercontent.com/92785792/141140143-0a298492-edbd-4ad9-9c95-fe30da473fdb.PNG)
v. #5: Xem kết quả
![11-4](https://user-images.githubusercontent.com/92785792/141141088-2b55fb70-a2a2-4792-87bd-144ff98ae98a.PNG)
c. Kết quả thực tế : Không có kí tự * bên cạnh trường ngày bắt đầu và ngày kết thúc nhưng vẫn thông báo lỗi.
d. Kết quả mong đợi: Có kí tự * bên cạnh trường ngày bắt đầu và ngày kết thúc.

**Comment by 31191025698** [comment]
Lỗi phi chức này này thuộc mục nào trong 11 mục mà nhóm liệt kê trong V.3 ở file Test Plan.
@31191026463

**Comment by 31191025698** [comment]
Không phải lỗi phi chức năng.
