### ISSUE TITLE
[Nhóm#9] Lỗi load chậm khi lưu thông tin họ tên mới - trang https://phonhadat.net/ 

### ISSUE THREAD

**Issue by 31191025549** [UEHMonQAQC/BI_K45#190]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi(https://drive.google.com/file/d/1D3dr7hcaTclwhjJpioSkP7XiWclAQwXv/view?usp=sharing)
i. #1: Truy cập trang: https://phonhadat.net/
ii. #2: Chọn đăng nhập
![Đăng nhập](https://user-images.githubusercontent.com/92793356/141311971-82d4a950-086e-4af9-ba6b-49248ce8dbce.png)
![Đăng nhập thành công](https://user-images.githubusercontent.com/92793356/141311984-c7b89782-9c3b-4c5b-b7de-9e573c3aacb9.png)
iii. #3: Chọn thay đổi thông tin cá nhân
![tdttcn](https://user-images.githubusercontent.com/92793356/141312069-308c91c7-0e76-4c72-850d-249a5e887118.png)
iv. #4: Nhập họ tên mới: " Hiếu Minh " và lưu thay đổi
![lưu thay đổi](https://user-images.githubusercontent.com/92793356/141312576-2ed7bbeb-db35-4e99-8707-370d425159d4.png)
![Screenshot (137)](https://user-images.githubusercontent.com/92793356/141312629-cffbb4cb-f84c-40a3-b9d9-51e3b29d6e1e.png)
c. Kết quả thực tế: Tên không được thay đổi ngay mà đợi hơn 3 phút
![khác tên](https://user-images.githubusercontent.com/92793356/141312716-652681c3-5ae9-4aaa-a925-59cf3a4dfd12.png)
d. Kết quả mong muốn: Tên được thay đổi không quá 3 phút

**Comment by 31191025698** [comment]
Cập nhật hình ảnh nữa nha
@31191025549
