### ISSUE TITLE
[Nhóm#9] Tràn khung viền khi kéo dãn khung – trang https://phonhadat.net/

### ISSUE THREAD

**Issue by 31191026463** [UEHMonQAQC/BI_K45#192]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://phonhadat.net/ sau đó chọn đăng tin
![11-5](https://user-images.githubusercontent.com/92785792/141152073-ccd3a626-c1c1-42f8-b087-b68beb833f8a.PNG)
ii. #2: Tại ô nội dung nhập dãy kí tự chữ "s" khoảng 2 dòng (không có khoảng trắng giữa các kí tự) 
![11-7](https://user-images.githubusercontent.com/92785792/141152754-f8369946-07b3-4e18-9bb8-03b42a713dac.PNG)
iii. #3: Để chuột vào góc phải bên dưới khung sau đó kéo dãn khung
![11-8](https://user-images.githubusercontent.com/92785792/141154854-b1208ef4-1191-40d7-9b03-bdba1e605928.PNG)
c. Kết quả thực tế: Khung bị kéo tràn ra khỏi đường viền. 
d. Kết quả mong đợi: Khung không bị tràn ra khỏi viền khi kéo dãn khung.

**Comment by 31191025698** [comment]
Thẻ textarea này cho phép kéo dãn.
Đây là chức năng không phải lỗi.
