### ISSUE TITLE
[Nhóm#9] Lỗi bảo mật tài khoản khi lưu tin lúc không đăng nhập - trang https://phonhadat.net/

### ISSUE THREAD

**Issue by 31191025750** [UEHMonQAQC/BI_K45#193]
a.	Web Browser: Google Chrome 95.0.4638.69
b.	Các bước phát hiện ra lỗi:
i.	#1: Truy cập trang: https://phonhadat.net/ 
ii.	#2: Chọn 1 tin đăng bất kỳ (lúc này chưa đăng nhập tài khoản)
![Lỗi 2](https://user-images.githubusercontent.com/92785502/141155050-75055d4d-c846-4e09-8ede-a548b7a8f00d.png)
iii.	#3: Kéo con trỏ xuống bấm lưu tin
![lỗi 22](https://user-images.githubusercontent.com/92785502/141155120-25281f24-46b2-4253-b422-54d645e7eb16.png)
iv.	#4: Sau khi tin đăng đã được lưu bấm đăng nhập
![lỗi 222](https://user-images.githubusercontent.com/92785502/141155226-8b0598d1-651d-4d93-8cf0-8fdcc437990e.png)
v.	#5: Chọn quản lý tin đã lưu
![lỗi 2222](https://user-images.githubusercontent.com/92785502/141155465-cab013ab-1ef1-4014-9f02-e5049cf596c9.png)
c.	Kết quả thực tế: tin đăng đã lưu vào tài khoản mặc dù chưa đăng nhập
d.	Kết quả mong đợi: hệ thống sẽ bắt buộc người dùng đăng nhập khi bấm lưu tin

**Comment by 31191025698** [comment]
Do cơ chế của website lưu id của tin vào cookie, khi người dùng đăng nhập vào nó sẽ đồng bộ. Nên đây là chức năng.
