### ISSUE TITLE
[Nhóm#7] Không đồng nhất ngôn ngữ - trang https://www.cgv.vn/

### ISSUE THREAD

**Issue by 31191023780** [UEHMonQAQC/BI_K45#196]
a. Web Browser: Microsoft Edge 95.0.1020.40
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang chủ CGV Việt Nam
![image](https://user-images.githubusercontent.com/92867185/141158843-ae5ba70c-ce89-4ce3-8447-fcfe07788b6c.png)
i. #2: Truy cập vào trang Tuyển dụng
![3](https://user-images.githubusercontent.com/92867185/141158990-222f215e-a0de-413a-89cf-8cd10c4630dc.PNG)
iii. #3: Nhấp chọn mục Trụ sở chính
![1](https://user-images.githubusercontent.com/92867185/141159064-adb0017f-5704-42ca-a365-58f8f8431543.PNG)
vi. #4: Nhấp chọn mục Cụm rạp
![2](https://user-images.githubusercontent.com/92867185/141159454-16f2e25b-5fb1-4313-908e-107b445ad962.PNG)
c. Kết quả thực tế: mặc dù để Tiếng Việt nhưng các vị trí công việc ở bên trụ sở chính lại ghi bằng Tiếng Anh, trong khi mục cụm rạp là Tiếng Việt.
d. Kết quả mong đợi: Các vị trí công việc nên đồng nhất Tiếng Việt hoặc Tiếng Anh.

**Comment by 31191026515** [comment]
Mình kiểm tra lại thì thấy đây không phải là lỗi. Lý do là những cái này là bài đăng của người quản trị web, nội dung bài đăng thì tùy vào chủ ý của người viết bài nên họ có thể viết ngôn ngữ nào cũng được. Khi nào chuyển qua chế độ tiếng Anh mà không đồng nhất ngôn ngữ thì mới tính lỗi nhé!
