### ISSUE TITLE
[Nhóm#9] Lỗi thay đổi trùng mật khẩu – trang https://vieclam.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191025750** [UEHMonQAQC/BI_K45#205]
a.	Web Browser: Google Chrome 95.0.4638.69
b.	Các bước phát hiện ra lỗi:
i.	#1: Truy cập trang: https://vieclam.ueh.edu.vn/ 
ii.	#2: Đăng nhập và chọn thay đổi mật khẩu
![lỗi 5](https://user-images.githubusercontent.com/92785502/141220709-1096bcd0-0c3b-4ee6-a3bf-71f87c03a031.png)
iii.	#3: Nhập mật mật khẩu cũ và mật khẩu mới giống nhau 
![lỗi 55](https://user-images.githubusercontent.com/92785502/141220744-a6e19c96-9df0-405b-888d-de1fa68f7d3e.png)
iv.	#4: Bấm cập nhật 
![lỗi 555](https://user-images.githubusercontent.com/92785502/141220785-87541619-9c93-4ce0-a0bd-8fb728853689.png)
c.	Kết quả thực tế: hệ thống cập nhật mật khẩu thành công
d.	Kết quả mong đợi: hệ thống báo lỗi “Bạn phải thay đổi mật khẩu mới”

**Comment by 31191025698** [comment]
Chức năng đổi mật khẩu hoạt động bình thường (_vẫn tới được mục đích là đổi mật khẩu_), đơn giản là không có ràng buộc mật khẩu mới phải khác mật khẩu cũ.
Đây không là lỗi.
