### ISSUE TITLE
[Nhóm#9] Hiển thị thông tin không đồng nhất - Trang https://vieclam.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191024635** [UEHMonQAQC/BI_K45#210]
a.Web Browser: Google Chrome 95.0.4638.69
b.Các bước phát hiện lỗi:
i. #1: Truy cập trang: https://vieclam.ueh.edu.vn/
ii. #2: Lướt xuống dưới mục những doanh nghiệp nổi bật, chọn doanh nghiệp Suntory Pepsico đang hiển thị có 5 bài đăng
![image](https://user-images.githubusercontent.com/92788705/141234248-0aaaaf84-d8bb-4f6e-8ed6-5812c7bd46f4.png)
iii. #3: Xem kết quả ở mục thông tin chung.
![image](https://user-images.githubusercontent.com/92788705/141234044-fd4b65de-7a35-49e3-b880-8230cbe3504f.png)
c. Kết quả thực tế: Ở trang chủ hiển thị doanh nghiệp có 5 bài đăng, nhưng bấm chọn xem doanh nghiệp thì lại hiển thị không có bài đăng nào ( 0 bài đăng) 
d. Kết quả mong đợi: Thông tin số bài đăng ở các trang đồng nhất với nhau

**Comment by 31191025698** [comment]
Số bài đăng ở bước 2 là tổng số bài đã được đăng, số bài đăng ở bước 3 là số bài đăng hiện có.
Đơn cử như Tập đoàn C.T Group có 9 bài đã đăng:
![image](https://user-images.githubusercontent.com/92703651/141303193-fd7a0531-d6f2-4777-ada2-5bea6986d3b3.png)
Click vào, có 1 bài đăng hiện có:
![image](https://user-images.githubusercontent.com/92703651/141303909-24089ed2-9c4d-46cf-87ca-25fba3c4b788.png)
Kiểm tra lại trong mục danh sách các công việc thì đúng chỉ có 1 bài đăng hiện còn hiệu lực:
![image](https://user-images.githubusercontent.com/92703651/141304150-10ae623c-6799-4c62-b35b-73ab4f322f01.png)

**Không chấp nhận lỗi**
