### ISSUE TITLE
[Nhóm#9] Không tương thích với thiết bị mobile – trang https://phonhadat.net/

### ISSUE THREAD

**Issue by 31191026463** [UEHMonQAQC/BI_K45#211]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://phonhadat.net/ và chọn đăng nhập
![11-18](https://user-images.githubusercontent.com/92785792/141233767-8dbb6162-623f-46d9-8463-a78a9c063bb4.PNG)
ii. #2: Quan sát thấy có chức năng quên mật khẩu
![11-19](https://user-images.githubusercontent.com/92785792/141233915-eae60de4-42b0-47c7-a948-dad99ae39eaf.PNG)
iii. #3: Chuyển về thiết bị mobile bằng cách nhấp vào link sau https://m.phonhadat.net/dang-nhap.htm và xem kết quả
![image](https://user-images.githubusercontent.com/92785792/141234168-71e03378-b3a9-4704-8626-1b8dc3b7d3af.png)
c. Kết quả thực tế: Không có chức năng quên mật khẩu ở thiết bị mobile, việc này hạn chế sử dụng chức năng trên mobile của trang web.
d. Kết quả mong đợi: Có chức năng quên mật khẩu trên thiết bị mobile.

**Comment by 31191025698** [comment]
Lỗi phi chức này này thuộc mục nào trong 11 mục mà nhóm liệt kê trong V.3 ở file Test Plan.
@31191026463
