### ISSUE TITLE
[Nhóm#5] Định dạng văn bản không đều, văn bản lệch khỏi 1 line - trang https://youth.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191021279** [UEHMonQAQC/BI_K45#213]
a. Web Browser: Opera 81.0.4196.31
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web: https://youth.ueh.edu.vn
![image](https://user-images.githubusercontent.com/92701347/141234028-3681d90c-6d60-4c9b-8967-f6d6a78dd1b2.png)
ii. #2: Tại mục Văn phòng điện tử chọn như hình sau:
![dtn2019](https://user-images.githubusercontent.com/92701347/141234823-807712af-e095-481d-9881-955771450fa1.png)
iii. #3: Chọn vào bài viết như hình sau và xem nội dung bài:
![dtnbv](https://user-images.githubusercontent.com/92701347/141234888-5d37eff2-e67b-448f-86f7-d9807c35eb4a.png)
![dtnvblech](https://user-images.githubusercontent.com/92701347/141235090-4d7d4ff3-04f5-48a1-90ed-9abf4d06c522.png)
![dtnlechvb](https://user-images.githubusercontent.com/92701347/141235190-185beb66-e376-454f-9223-f9a2ee3f4aa5.png)
c. Kết quả thực tế: định dạng không đều, văn bản lệch nhau, không được căn thẳng trên chung 1 line
d. Kết quả mong đợi: văn bản được căn thẳng trên 1 line

**Comment by 31191024332** [comment]
Hi Nhóm,
Tương tự như issue #115 mình đã closed trước đó, đây là lỗi do định dạng văn bản từ người đăng bài không phải lỗi giao diện nha. Nhóm kiểm tra lại giúp mình.
Mình cảm ơn rất nhìu.
