### ISSUE TITLE
[Nhóm#9] Nhập sai field bắt buộc số điện thoại nhưng vẫn lưu thông tin thành công. – trang https://phonhadat.net/

### ISSUE THREAD

**Issue by 31191025549** [UEHMonQAQC/BI_K45#217]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://phonhadat.net/
ii. #2: Đăng nhập tài khoản
![Đăng nhập](https://user-images.githubusercontent.com/92793356/141238413-424b4412-2973-4256-964f-4d3e6acb327b.png)
![Đăng nhập thành công](https://user-images.githubusercontent.com/92793356/141238440-1fa29f84-cb56-4365-80c8-3bf0f61f071a.png)
iii. #3: Chọn thay đổi thông tin cá nhân
![tdttcn](https://user-images.githubusercontent.com/92793356/141238961-6504c47b-cf80-496e-9034-e250c4d290a1.png)
iv. #4: Nhập số điện thoại sai định dạng ( số điện thoại có 11 chữ số hoặc 12 chữ số )
![sđt](https://user-images.githubusercontent.com/92793356/141239035-0195f684-a7ce-4696-9923-1596dc685ec9.png)
c. Kết quả thực tế: Lưu thông tin thành công.
![Screenshot (122)](https://user-images.githubusercontent.com/92793356/141239073-781b5298-ffaf-4638-9b05-b40a13a7fc54.png)
d. Kết quả mong đợi: Báo lỗi sai định dạng số điện thoại.

**Comment by 31191025698** [comment]
Thầy có thông tin là textbox số điện thoại lưu được chữ thì mới là lỗi. Nên đây không là lỗi.
