### ISSUE TITLE
[Nhóm#9] Màu chữ không đồng nhất – trang https://phonhadat.net/

### ISSUE THREAD

**Issue by 31191025549** [UEHMonQAQC/BI_K45#221]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi
i. #1: Truy cập trang: https://phonhadat.net/
ii. #2: Chọn trang hướng dẫn sử đụng
![hướng dẫn](https://user-images.githubusercontent.com/92793356/141244260-ede072f1-aacd-4e17-8349-f8b46d103203.png)
iii. #3: Chọn mục Hướng dẫn quản lí tin rao bán/cho thuê
![quản lí tin rao](https://user-images.githubusercontent.com/92793356/141244215-77114c67-1b20-4603-8501-90a2dd009f57.png)
iv. #4: Kéo đến cuối trang
![khác màu](https://user-images.githubusercontent.com/92793356/141244253-35035a4f-ed34-493c-985e-caa17ce1ff0b.png)
c. Kết quả thực tế: Màu sắc không đồng nhất giữa Xóa tin và Up tin mới.
d. Kết quả mong muốn: Màu sắc đồng nhất giữa các mục

**Comment by 31191025698** [comment]
Đây là hình ảnh được tải lên.
Không chấp nhận lỗi.
