### ISSUE TITLE
[Nhóm#7] Trên mobile , thanh search bị mất chữ mô tả - trang https://smartlib.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31191024776** [UEHMonQAQC/BI_K45#228]
a. Web Browser: Google Chrome 95.0.4638.69- Mobile Galaxy S5
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang https://smartlib.ueh.edu.vn/, sử dụng Developer Tool để hiện giao diện của Galaxy S5, ở thanh One Search, phần chữ không được thể hiện hết
![mobile - GUI - one search](https://user-images.githubusercontent.com/92839124/141275299-e54f8a4e-032f-4c0e-a42d-ccc53a4246ff.JPG)

c. Kết quả thực tế: Nội dung bị mất , không thể hiện được hết câu
d. Kết quả mong đợi: Nội dung mô tả thanh search phải được chỉnh font sao cho vừa để thể hiện được hết câu

**Comment by 31191026515** [comment]
Theo record buổi 5 thì khi xem responsive bị vỡ layout mới bị tính lỗi nên lỗi này mình k tính nhé!
