### ISSUE TITLE
[Nhóm#3] Không tìm thấy nội dung khi nhấn vào button liên kết thông tin bài viết - trang https://tuyensinh.ueh.edu.vn

### ISSUE THREAD

**Issue by ddongvi** [UEHMonQAQC/BI_K45#23]
a.Web Browser: Google Chrome 95.0.4638.54
b.Các bước để phát hiện lỗi:
i. #1: truy cập vào trang https://tuyensinh.ueh.edu.vn
<img width="1440" alt="Screen Shot 2021-11-02 at 23 29 11" src="https://user-images.githubusercontent.com/92705124/139906200-846f24a6-e8bc-4fac-be1e-e5db444a28ea.png">
ii. #2: kéo xuống giữa trang và chọn bài viết "Tuyển sinh Văn bằng 1 Đại học Vừa làm vừa học 2021"
<img width="1440" alt="Screen Shot 2021-11-02 at 23 30 32" src="https://user-images.githubusercontent.com/92705124/139906785-98fca5e8-758c-4906-8286-cb9ba726f307.png">
iii. #3: Nhấp vào "ĐÂY"
<img width="1440" alt="Screen Shot 2021-11-02 at 23 33 24" src="https://user-images.githubusercontent.com/92705124/139906911-2ab28e9e-f25f-4b34-b049-fafa94236513.png">
c.Kết quả thực tế: Không tìm thấy bài viết.
<img width="1440" alt="Screen Shot 2021-11-02 at 23 34 28" src="https://user-images.githubusercontent.com/92705124/139907042-170ba461-1f02-4ab8-a4ea-6267e7bdbfb8.png">
d.Kết quả mong muốn: Trang hiển thị bài viết được liên kết.

**Comment by 31191022164** [comment]
Hi Vĩ, Vĩ kiểm tra lại issues này giúp mình nha. Mình check không thấy bài viết "Tuyển sinh Văn bằng 1 Đại học Vừa làm vừa học 2021"  @31191024249
