### ISSUE TITLE
[Nhóm#4] Lỗi bảo mật lịch sử tìm kiếm - trang https://www.tienganh123.com/

### ISSUE THREAD

**Issue by 31191026606** [UEHMonQAQC/BI_K45#231]
a. Web Browser: Google Chrome: Phiên bản 95.0.4638.69 (Phiên bản Chính thức) (64 bit)                      
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://www.tienganh123.com/
![Bảo tìm 1](https://user-images.githubusercontent.com/92720997/141285858-c1c32187-2955-4c83-8f87-9a46ddd5d013.JPG)
ii. #2: Đăng ký và đăng nhập vào trang.
![Bảo tìm 2](https://user-images.githubusercontent.com/92720997/141285970-057a60cb-eb87-488b-91dd-d14daa5905cc.JPG)
iii. #3: Nhập từ khóa bất kỳ vào khung và nhấn tìm kiếm.
![Bảo tìm 3](https://user-images.githubusercontent.com/92720997/141286011-72080985-4bad-46be-beda-059fd65a22ee.JPG)
iv. #4: Đăng xuất khỏi tài khoản.
![Bảo tìm 4](https://user-images.githubusercontent.com/92720997/141286033-3a4d769e-d14e-4876-996c-9d280e54871a.JPG)
v. #5: Đăng nhập bằng một tài khoản khác và nhấn vào khung tìm kiếm để xem kết quả.
![Bảo tìm 5](https://user-images.githubusercontent.com/92720997/141286061-70896754-153a-43c1-8505-84a89cc756e0.JPG)
c. Kết quả thực tế: lịch sử tìm kiếm của 2 tài khoản giống nhau.
d. Kết quả mong đợi: lịch sử tìm kiếm của 2 tài khoản khác nhau.

**Comment by 31191022164** [comment]
Lỗi này thầy có giải thích ở buổi học thứ 5 (13/11) - thời gian 1:33:41. Thầy có giải thích về vấn đề này là không phải lỗi nha.
