### ISSUE TITLE
[Nhóm#4] Hiệu suất tải chậm không đạt yêu cầu (Thiết bị di động) - trang https://digital.lib.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191026606** [UEHMonQAQC/BI_K45#232]
a. Web Browser: Google Chrome: Phiên bản 95.0.4638.69 (Phiên bản Chính thức) (64 bit)                      
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://developers.google.com/speed/pagespeed/insights/
![HS 1](https://user-images.githubusercontent.com/92720997/141286472-b1d0a5c7-9830-4d34-aed6-8b4f07994902.JPG)
ii. #2: Nhập địa chỉ của trang https://digital.lib.ueh.edu.vn/ và nhấn bottom "PHÂN TÍCH".
![HS 2](https://user-images.githubusercontent.com/92720997/141286507-3a3c2988-1f0a-409d-80b2-4f247bca1e15.JPG)
iii. #3: Chọn xem kết quả phân tích trên "Thiết bị di động" và "Máy tính để bàn".
![HS 4](https://user-images.githubusercontent.com/92720997/141286549-24d50b81-9a6f-4067-853f-76c55548a8c7.JPG)
![HS3](https://user-images.githubusercontent.com/92720997/141286558-3469ae33-5026-4805-8536-833b8dcda797.JPG)
c.Kết quả thực tế: Giao diện "Thiết bị di động" được phân tích hiệu suất tải chậm.
d.Kết quả mong đợi: Trang nên cải thiện tốc độ tốt hơn (trên 90%) để nâng cao trải nghiệm của người dùng.

**Comment by 31191022164** [comment]
Lỗi này không nằm trong giới hạn Lỗi phi chức năng của lớp (bảo mật, tốc độ truy cập quá 3p và không dùng tools). Nên mình không xác nhận lỗi này nha.
