### ISSUE TITLE
[Nhóm#9] Dùng từ không đồng nhất – trang https://phonhadat.net/

### ISSUE THREAD

**Issue by 31191025549** [UEHMonQAQC/BI_K45#235]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://phonhadat.net/
ii. #2: Đăng nhập tài khoản
![Screenshot (113)](https://user-images.githubusercontent.com/92793356/141288487-84e79cd0-5bee-4e21-bd6f-50e02bca4619.png)
![Đăng nhập thành công](https://user-images.githubusercontent.com/92793356/141288511-cc0b7fa3-8d00-4a46-8812-9b093d24de8d.png)
iii.  #3: Chọn thay đổi thông tin cá nhân
![tdttcn](https://user-images.githubusercontent.com/92793356/141288560-9bc9e130-f457-476e-a879-ea06dc2b61ff.png)
iv. #4: Nhập Điện thoại sai định đạng (ít hơn 10 số, hoặc nhiều hơn 12 số) và lưu thay đổi
![điện thoại](https://user-images.githubusercontent.com/92793356/141288853-336c731c-21ac-4b21-aa3e-f58841052f41.png)
c. Kết quả thực tế: Thông báo: "Số di động sai định dạng", bất đồng ngôn ngữ.
![sai định dạng](https://user-images.githubusercontent.com/92793356/141289104-a6409af5-e024-4108-b47e-b43cd321bc30.png)
d. Kết quả mong đợi: Thông báo :"Điện thoại sai định dạng".

**Comment by 31191025698** [comment]
**Không thể chấp nhận lỗi!!!!!!**
