### ISSUE TITLE
[Nhóm#3] Không có thuộc tính "alt" trong thẻ img - trang https://tuyensinh.ueh.edu.vn/

### ISSUE THREAD

**Issue by ddongvi** [UEHMonQAQC/BI_K45#24]
a.Web Browser: Google Chrome 95.0.4638.54
b.Các bước để phát hiện lỗi:
i. #1 truy cập trang https://validator.w3.org/
<img width="1440" alt="Screen Shot 2021-11-02 at 23 49 49" src="https://user-images.githubusercontent.com/92705124/139909581-8edca19a-f065-480e-b277-7bc334dace00.png">
ii. #2: nhập link https://tuyensinh.ueh.edu.vn/ vào ô address và click "Check"
<img width="1440" alt="Screen Shot 2021-11-02 at 23 51 04" src="https://user-images.githubusercontent.com/92705124/139909737-2c6b4afe-c3ee-49ae-8090-7cf762e1b1fb.png">
iii. #3: xuất hiện lỗi 
<img width="1440" alt="Screen Shot 2021-11-02 at 23 53 22" src="https://user-images.githubusercontent.com/92705124/139910172-21b9f18b-3088-47ad-969c-fead04296e59.png">
c.Kết quả thực tế:  không có thuộc tính "alt" trong thẻ img
d.Kết quả mong đợi: Thuộc tính "alt" được thêm trong thẻ img

**Comment by 31191022164** [comment]
Lỗi này không nằm trong giới hạn Lỗi phi chức năng của lớp (bảo mật và tốc độ truy cập quá 3p) nhé
