### ISSUE TITLE
[Nhóm#8] Lỗi ràng buộc dữ liệu nhập vào ô trong mục “Cập nhật hồ sơ”- Trang https://global.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191025019** [UEHMonQAQC/BI_K45#250]
a.	Web browser: Google Chrome 95.0.4638.69
b.	Các bước phát hiện lỗi
i. #1: Đăng nhập thành công vào trang https://global.ueh.edu.vn/
 
![image](https://user-images.githubusercontent.com/92733467/141324783-29937f5d-8bbe-4e13-b9fd-9e5d09fd9f0f.png)

ii. #2: Chọn hồ sơ
 
![image](https://user-images.githubusercontent.com/92733467/141324982-47449274-167d-4fd4-a61d-314c156758d4.png)

iii. #3: Chọn sửa hồ sơ cá nhân

 ![image](https://user-images.githubusercontent.com/92733467/141325110-249bab27-b586-44cc-b1c0-b962e2f487cb.png)

iv. #4: Nhập họ và tên

 ![image](https://user-images.githubusercontent.com/92733467/141325204-6c9306fb-4ef5-44ce-8ccc-c310258c9c69.png)

v. #5: Kéo xuống dưới chọn “Cập nhật hồ sơ”

![image](https://user-images.githubusercontent.com/92733467/141325280-de57bce0-d8b9-4c8e-a6ce-92c1b42d8ca4.png)

![image](https://user-images.githubusercontent.com/92733467/141325427-60f9a5a9-6403-422d-960a-14780f526486.png)
c. Kết quả thực tế: Nhập định dạng không hợp lệ vẫn cập nhật thành công
d. Kết quả mong đợi: Hiển thị thông báo lỗi yêu cầu người dùng nhập đúng định dạng.

**Comment by hieeusnguyeenx** [comment]
@31191025019  như đã đề cập với thầy thì đây là do trang web không ràng buộc định dạng nhé.
