### ISSUE TITLE
[Nhóm#8] Lỗi thanh chọn Luyện đề thi THPT bị tràn - trang https://global.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191026190** [UEHMonQAQC/BI_K45#253]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140551931-432799ce-f7e8-4543-856c-cdbcca12de3d.png)
ii. #2 Đăng nhập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140552138-508220cd-1c2f-489a-af35-984ca6da55d8.png)
iii. #3 Nhấp vào tên người dùng ở góc phải, chọn Tùy chọn:
![image](https://user-images.githubusercontent.com/92732798/140552348-ab1cc58f-7946-41e6-9f72-cf35500bf45d.png)
iv. #4 Chọn biểu tượng 3 gạch ở góc trái màn hình để mở thanh hiển thị điều hướng:
![image](https://user-images.githubusercontent.com/92732798/140554335-ee85c295-b302-40e3-a5a3-76ca26ded45a.png)
v. #5 Chọn mục Khóa học:
![image](https://user-images.githubusercontent.com/92732798/140557925-ed9897a5-8aaa-46e1-a396-db253c23ae98.png)
vi. #6 Chọn mục Luyện đề thi THPT :
![image](https://user-images.githubusercontent.com/92732798/141327709-6efdb67f-c247-49b2-ae14-4739d8925df3.png)
vii. #7 Xem kết quả hiển thị:
![image](https://user-images.githubusercontent.com/92732798/141327858-3808f98b-e444-4869-9a49-c143238a2ba3.png)
c. Kết quả thực tế: Thanh chọn Luyện đề thi THPT bị tràn ra khỏi màn hình hiển thị
d. Kết quả mong đợi: Thanh chọn Luyện đề thi THPT không bị tràn khỏi màn hình hiển thị

**Comment by hieeusnguyeenx** [comment]
@31191026190  lỗi này trùng với lỗi 150 nhé
