### ISSUE TITLE
[Nhóm#3] Hiệu suất tải chậm không đạt yêu cầu - trang https://tuyensinh.ueh.edu.vn/

### ISSUE THREAD

**Issue by ddongvi** [UEHMonQAQC/BI_K45#26]
a.Web Browser: Google Chrome 95.0.4638.54
b.Các bước để phát hiện lỗi:
i. #1: truy cập vào trang https://developers.google.com/speed/pagespeed/insights/
<img width="1440" alt="Screen Shot 2021-11-03 at 00 14 57" src="https://user-images.githubusercontent.com/92705124/139913452-932d0f22-2cec-4174-92a0-807dcb6e7cff.png">
ii. #2: Nhập địa chỉ trang : https://tuyensinh.ueh.edu.vn/ và click "ANALYZE"
<img width="1440" alt="Screen Shot 2021-11-03 at 00 16 30" src="https://user-images.githubusercontent.com/92705124/139913737-851a3b79-31f2-4bad-8451-bdaa84a6c8e1.png">
iii. #3: Xem kết quả phân tích trên Desktop
<img width="1440" alt="Screen Shot 2021-11-03 at 00 18 20" src="https://user-images.githubusercontent.com/92705124/139913984-0f1e0d32-e206-4693-b16a-2d6b42a6d06b.png">
iv. #4: Chọn xem kết quả phân tích trên Mobile 
<img width="1440" alt="Screen Shot 2021-11-03 at 00 23 12" src="https://user-images.githubusercontent.com/92705124/139914766-07ee8e45-f04f-419d-8a27-0ff058d5156f.png">
c.Kết quả thực tế: Cả giao diện Mobile và Desktop đều được phân tích hiệu suất tải chậm 
d.Kết quả mong đợi: Trang cải thiện tốc độ tốt hơn (trên 90%) để nâng cao kết quả trải nghiệm của người dùng

**Comment by 31191022164** [comment]
Tính từ tuần 3, thì mình chưa chấp nhận lỗi phi chức năng này nên mình sẽ đóng lỗi này nha
