### ISSUE TITLE
[Nhóm#8] Lỗi không hiển thị hình ảnh trong mục Luyện đề thi THPT - trang https://global.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191026190** [UEHMonQAQC/BI_K45#267]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140551931-432799ce-f7e8-4543-856c-cdbcca12de3d.png)
ii. #2 Đăng nhập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140552138-508220cd-1c2f-489a-af35-984ca6da55d8.png)
iii. #3 Nhấp vào tên người dùng ở góc phải, chọn Hồ sơ:
![image](https://user-images.githubusercontent.com/92732798/141335193-0a0314aa-7ba3-4958-b620-baf1248781e7.png)
iv. #4 Chọn Luyện đề thi chính thức THPT Quốc gia qua các năm:
![image](https://user-images.githubusercontent.com/92732798/141341046-de7484ce-44b3-4897-95af-79858ec40008.png)
v. #5 Xem kết quả hiển thị:
![image](https://user-images.githubusercontent.com/92732798/141341176-f278599c-7901-4a86-bc50-2d8fe085c35a.png)
c. Kết quả thực tế: Hình ảnh thông tin không được hiển thị
d. Kết quả mong đợi: Hiển thị được hình ảnh

**Comment by hieeusnguyeenx** [comment]
@31191026190 mô tả chi tiết hơn nhé, mình làm như mô tả nhưng không ra được kết quả như trên
