### ISSUE TITLE
[Nhóm#3] Không hiển thị trang khi click vào Slideshow - trang https://tuyensinh.ueh.edu.vn/

### ISSUE THREAD

**Issue by ddongvi** [UEHMonQAQC/BI_K45#27]
a.Web Browser: Google Chrome 95.0.4638.54
b.Các bước để phát hiện lỗi:
i. #1: truy cập vào trang https://tuyensinh.ueh.edu.vn/
<img width="1440" alt="Screen Shot 2021-11-05 at 23 41 05" src="https://user-images.githubusercontent.com/92705124/140546749-32b60f28-6b49-48c8-915c-62f629ba338b.png">
ii. #2: Click vào biểu tượng ">" 6 lần.
<img width="1440" alt="Screen Shot 2021-11-05 at 23 42 30" src="https://user-images.githubusercontent.com/92705124/140546934-c79e4ac3-1bc0-43b1-8f3a-de10367145de.png">
iii. #3: Click vào Slideshow đang hiển thị
<img width="1440" alt="Screen Shot 2021-11-03 at 00 37 06" src="https://user-images.githubusercontent.com/92705124/139917010-11b51e6f-5c80-4bec-8128-21ef9004f745.png">
c.Kết quả thực tế: Không hiển thị trang web "Tuyển sinh thạc sĩ" -https://tuyensinh.ueh.edu.vn/thac-si/
d.Kết quả mong đợi: Hiển thị trang web "Tuyển sinh thạc sĩ"

**Comment by 31191022164** [comment]
Mình đã kiểm tra và xác nhận đây không phải là lỗi nha. 
Vì cái này không có điều hướng nha @31191024249
