### ISSUE TITLE
[Nhóm#9] Dùng gmail của người khác (gmail chưa từng đăng ký) để đăng ký với mật khẩu tùy ý và đăng nhập thành công (Lấy mất quyền truy cập của chủ gmail) - Trang https://vieclam.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191021273** [UEHMonQAQC/BI_K45#276]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập trang https://vieclam.ueh.edu.vn/
ii. #2: Chọn "Đăng nhập/Đăng ký"
![pcn1](https://user-images.githubusercontent.com/92793980/141393625-4bcb7ffa-377d-429e-9d6c-8e682a6ada80.png)
iii. #3: Chọn "Đăng kí cho sinh viên/ứng viên"
![pcn1 1](https://user-images.githubusercontent.com/92793980/141393919-e0b6aac5-936f-4d9d-94e2-6d134ed1a13a.png)
iv. #4: Nhập mail của người khác với mật khẩu tùy ý và ấn "Đăng ký"
![Screenshot (920)](https://user-images.githubusercontent.com/92793980/141394051-2930b107-1836-4ca7-9454-0f7a3d99f518.png)
c. Kết quả thực tế:
Đăng kí thành công.
d. Kết quả mong muốn:
Hệ thống sẽ xác thực gmail để chủ gmail không bị mất quyền đăng ký trong trang này.

**Comment by 31191025698** [comment]
Kết quả đăng ký thành công đâu???
@31191021273

**Comment by 31191025698** [comment]
QA test có thông báo: 
![image](https://user-images.githubusercontent.com/92703651/141397199-48165368-d78c-42a5-8294-a115505448c2.png)

**Comment by 31191021273** [comment]
QA dùng mail nào để đăng ký ạ. QA đăng ký lại bằng mail này dùm mình với: jinzhi18042000@gmail.com (mail này chưa được đăng kí lần nào)

**Comment by 31191025698** [comment]
Tittle không miêu tả lỗi rõ ràng.

**Comment by 31191021273** [comment]
Vậy giờ mình Edit lại được không ạ

**Comment by 31191025698** [comment]
Được nha bạn

**Comment by 31191025698** [comment]
Cá nhân mình thì cho đây đúng là lỗi phi chức năng, nhưng trong khuôn khổ yêu cầu của thầy trong môn học này thì không. Nên mình xin không chấp nhận lỗi.
