### ISSUE TITLE
[Nhóm#6] Lỗi đăng ký nhận thông báo - trang https://trading.tabbook.vn/ 

### ISSUE THREAD

**Issue by 31191021871** [UEHMonQAQC/BI_K45#280]
a. Web browsers: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang https://trading.tabbook.vn/
ii. #2: Đăng nhập vào tài khoản 
iii. #3: Kéo xuống phần Footer của trang chọn Tài Khoản Của Tôi 
![image](https://user-images.githubusercontent.com/92736076/141404233-43940ca1-6032-4e37-b199-cbcadbe87368.png)
iv. #4: Chọn bản tin trong mục Newsletter
![image](https://user-images.githubusercontent.com/92736076/141404351-fa76bf96-3d5b-47aa-9ef0-e0f140b80b6c.png)
v. #5: Trong phần Đăng Ký Nhận Thông Báo nhấn "Không" rồi nhấn Tiếp Tục 
![image](https://user-images.githubusercontent.com/92736076/141404496-f417c9fe-2a38-472c-a1cb-29d7e0e9199a.png)
c. Kết quả thực tế: Nhấn "Không" nhận đăng ký thông báo nhưng màn hình lại thông báo là "Thành công: Bạn đã đăng kí nhận thư thông báo!"
![image](https://user-images.githubusercontent.com/92736076/141404655-b6b19658-ba50-49e9-a82a-fdace7b87b4c.png)
d. Kết quả mong đợi : Nhấn "Không" nhận đăng ký thông báo thực hiện đúng yêu cầu người dùng

**Comment by 31191024332** [comment]
Hông phải lỗi chức năng nha. Nhóm kiểm tra lại giúp mình

**Comment by 31191021871** [comment]
mình đã kt lại và đó là lỗi chức năng gửi thông báo của người dùng, trong GUI check list mục IV.3, IV.4 không bao gồm lỗi này.

**Comment by 31191024332** [comment]
Theo mình khi thực hiện xong các bước trong issue thì do popup hiển thị thông tin bị sai/lệch với thao tác. Nên đây thuộc lỗi GUI không phải lỗi chức năng. Nếu liên quan đến chức năng nhóm cần bổ sung thêm ảnh/video về việc nhận/không nhận được thông báo dù đã chọn không nhận/nhận trên url đề cập

**Comment by 31191024332** [comment]
Mình thấy nhóm có ghi lại trong issue #333 nên mình close issu này và qua #333 xác nhận lỗi nha
