### ISSUE TITLE
[Nhóm#6] Hình ảnh sản phẩm hiển thị bị chồng lên nhau, sai vị trí- trang https://trading.tabbook.vn/

### ISSUE THREAD

**Issue by 31191021871** [UEHMonQAQC/BI_K45#3]
a. Web Browser: Google Chrome 95.0.4638.54
b. Các bước để phát hiện lỗi 
i. #1 Truy cập vào trang https://trading.tabbook.vn/
![image](https://user-images.githubusercontent.com/92736076/139682854-f5c9a29c-f3aa-4cec-8b20-773254aadc24.png)

ii #2 Kéo xuống phần danh mục sản phẩm
![image](https://user-images.githubusercontent.com/92736076/139682941-bf19a437-a83a-47c1-8890-9b6c9e8e724d.png)

iii #3 Nhấp vào mục sách đã qua sử dụng 
![image](https://user-images.githubusercontent.com/92736076/139905479-c38fe084-2e35-4776-9bd7-a0ee0825e8d1.png)

iv #4 Kéo đến phần hiển thị sản phẩm 
v. #5 Nhấp chọn định dạng hiển thị theo Danh sách 
![image](https://user-images.githubusercontent.com/92736076/140384075-1210961f-31f1-4447-83f7-e4dc48ea80ff.png)

c. Kết quả thực tế: Hình ảnh của các sản phẩm bị chồng lên nhau sai vị trí hình ảnh
![image](https://user-images.githubusercontent.com/92736076/139905893-0ab76ffb-c41c-45d1-bd3e-b20b4971af8c.png)
![image](https://user-images.githubusercontent.com/92736076/139905937-043bfda1-b9e8-45aa-926a-1492e5d213a6.png)
 
d. Kết quả mong đợi: Các hình ảnh xếp về một cột bên phải thẳng hàng, không chồng chéo

**Comment by 31191024332** [comment]
Mình dùng cùng trình duyệt và làm theo các bước nhưng không phát hiện lỗi Nhóm 6 đề cập. Nhóm kiểm tra giúp mình nha. Mình xin phép không xác nhận lỗi này. Cảm ơn Nhóm 6
![image](https://user-images.githubusercontent.com/82808388/140322203-f2003687-0368-4eb8-97f0-9e39f91eacfd.png)

**Comment by 31191021871** [comment]
> Mình dùng cùng trình duyệt và làm theo các bước nhưng không phát hiện lỗi Nhóm 6 đề cập. Nhóm kiểm tra giúp mình nha. Mình xin phép không xác nhận lỗi này. Cảm ơn Nhóm 6 ![image](https://user-images.githubusercontent.com/82808388/140322203-f2003687-0368-4eb8-97f0-9e39f91eacfd.png)

Mình có kiểm tra lại thì lỗi post lên bị thiếu bước phát hiện lỗi. Hiện tại mình đã cập nhật lại rồi, Yến check lại giùm nhóm nha
