### ISSUE TITLE
[Nhóm#3] Dùng SĐT đã đăng ký để đăng ký tài khoản trang không báo lỗi - trang https://vexere.com/

### ISSUE THREAD

**Issue by ddongvi** [UEHMonQAQC/BI_K45#303]
a.Web Browser: Google Chrome 95.0.4638.54
b.Các bước để phát hiện lỗi:
i. #1: truy cập vào trang https://vexere.com/ và đăng nhập 
![image](https://user-images.githubusercontent.com/92705124/141823500-982e7dda-ce79-4ed7-be77-df8e59581e63.png)
ii. #2: Nhấp vào Biểu tượng tài khoản chọn "Thông tin tài khoản"
<img width="1440" alt="Screen Shot 2021-11-16 at 00 07 26" src="https://user-images.githubusercontent.com/92705124/141824025-93b5c794-0570-45dd-8696-2e874c16760a.png">
iii. #3: Sử dụng số điện thoại đã đăng ký để tạo tài khoản mới.
<img width="1440" alt="Screen Shot 2021-11-16 at 00 09 06" src="https://user-images.githubusercontent.com/92705124/141824326-51a62d8c-06e8-4b17-a3e8-cb36cb76dab5.png">
iv. #4: Đăng xuất và trở về trang chủ chọn "Đăng ký"
<img width="1440" alt="Screen Shot 2021-11-16 at 00 10 20" src="https://user-images.githubusercontent.com/92705124/141824441-4a503c2d-31cd-4ab3-a790-e8a90de469e4.png">
v. #5: Đăng ký tài khoản mới với SĐT đã được đăng ký
<img width="1440" alt="Screen Shot 2021-11-16 at 00 13 54" src="https://user-images.githubusercontent.com/92705124/141824963-37615e72-bc7c-4444-b556-1e5cfa3f8fd5.png">
<img width="1440" alt="Screen Shot 2021-11-16 at 00 11 31" src="https://user-images.githubusercontent.com/92705124/141824644-dc597c50-e77b-4e93-bb65-2cddea477f2a.png">
c.Kết quả thực tế: Hệ thống không hề thông báo SĐT đã được đăng ký mà tiếp tục dẫn đến màn hình xác thực OTP
d.Kết quả mong đợi: Hệ thống thông báo SĐT đã được đăng ký

**Comment by 31191022164** [comment]
Với lỗi phi chức năng chỉ tính bảo mật và hiệu suất quá 3p. Nên với lỗi này mình không duyệt nha.
