### ISSUE TITLE
[Nhóm#3] Button ghế bị che không thể chọn - trang https://vexere.com/

### ISSUE THREAD

**Issue by ddongvi** [UEHMonQAQC/BI_K45#309]
a.Web Browser: Google Chrome 95.0.4638.54
b.Các bước để phát hiện lỗi:
i. #1: truy cập vào trang https://vexere.com/ và đăng nhập 
![image](https://user-images.githubusercontent.com/92705124/141986415-7f7beb55-4185-4f3a-bda9-32465543c5d0.png)
ii. #2: Điền điểm đi điểm đến như hình và chọn tìm chuyến.
<img width="1440" alt="Screen Shot 2021-11-16 at 19 37 07" src="https://user-images.githubusercontent.com/92705124/141986584-479f05ff-8bf9-4fcc-a488-99d5b97c64be.png">
iii. #3: Click "Chọn chuyến"
<img width="1440" alt="Screen Shot 2021-11-16 at 19 38 25" src="https://user-images.githubusercontent.com/92705124/141986696-e8f0d562-ea7e-47d7-8e54-d13fc4046663.png">
iv. #4: Chọn ghế như hình 
<img width="1440" alt="Screen Shot 2021-11-16 at 19 39 25" src="https://user-images.githubusercontent.com/92705124/141986816-4f03bf40-636e-42c6-9819-3fccce37ef4a.png">
v. #5 Tiếp tục chọn ghế ở trên ghế đã chọn
<img width="1440" alt="Screen Shot 2021-11-16 at 19 40 29" src="https://user-images.githubusercontent.com/92705124/141986943-5e6ec0a6-88d9-4b50-b82b-3834e1baf9d4.png">
c.Kết quả thực tế: Lúc này không thể click vào ghế trên vì dòng chữ màu đen đã che khuất
d.Kết quả mong đợi: Sau khi di chuột ra khỏi ghế đã chọn thì ô chữ màu đen biến mất để có thể chọn ghế ở trên

**Comment by 31191022164** [comment]
Mình đã kiểm tra và xác nhận đây không phải lỗi nha.
