### ISSUE TITLE
[Nhóm#2] Lỗi không chọn được Phòng - Trang https://student.ueh.edu.vn/

### ISSUE THREAD

**Issue by TRAN-PHAM-HOANG-CHUONG** [UEHMonQAQC/BI_K45#313]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://student.ueh.edu.vn/Home
![image](https://user-images.githubusercontent.com/92730744/142002680-0fa53b2b-4884-4db3-8597-aadfaeaca292.png)
ii. #2: Đăng nhập vào trang web
![image](https://user-images.githubusercontent.com/92730744/142002828-09db9a46-7cfb-4f45-afdf-25bdc3a0a3ce.png)
iii. #3: Chọn chức năng Ngoại trú sinh viên
<img width="959" alt="Ngoại trú" src="https://user-images.githubusercontent.com/92730744/142003469-696aa565-f477-4878-823f-f006c0ec0563.png">
iv. #4: Chọn Đăng kí KTX
![image](https://user-images.githubusercontent.com/92730744/142003644-af7b520c-5ae7-407e-88c0-78e7b1f5c9cd.png)
v. #5: Chọn Phòng
<img width="959" alt="Phòng" src="https://user-images.githubusercontent.com/92730744/142004197-d7c139f4-e030-4fe9-8f14-7a3adb93cf11.png">
c. Kết quả thực tế: Ở ô Phòng hiển thị ra khung trống không có Phòng để lựa chọn
d. Kết quả mong đợi: Khi nhấp chọn Phòng sẽ hiển thị ra các Phòng KTX  để có thể lựa chọn

**Comment by hieeusnguyeenx** [comment]
@31191021184 Mình có hỏi mọi người thì đăng ký KTX thì đăng ký bên [web KTX,](https://l.facebook.com/l.php?u=https%3A%2F%2Fkytucxa.ueh.edu.vn%2Fstudent%2Fdorm-register%3Ffbclid%3DIwAR341XRQNVuc2CI9f0koTJPinPbGxP3ErmdEcY7-Rk6WZXN3twYtj9HPntQ&h=AT18S63273rXjXgyrRDJSEcvhgpC9E_RYg8x3-WeJ1mGXR0aguxRyulq0CEZQMkAbOKsE38VaihgYkDuGY0QHcqqZJyO_JnHJp_8ojU3rzBENTl1TOoiCc2Nr-c5N_KEWeMgUo20SKdaXbQFEbDCng) nên có thể là cái này chưa phát triển hoặc không dùng. 
Một trường hợp nữa là chức năng này đến đợt đăng ký thì mới mở ra giống như đăng ký học phần. Mà hiện tại là chưa đến đợt đăng ký nên chưa có dữ liệu để hiển thị.
Nên là mình không ghi nhận lỗi nhé.
