### ISSUE TITLE
[Nhóm#2] Lỗi không tra cứu được học phần bằng mã học phần - trang https://student.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191021724** [UEHMonQAQC/BI_K45#314]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước để phát hiện lỗi
i. #1:Truy cập vào trang https://student.ueh.edu.vn/
![Screenshot (62)](https://user-images.githubusercontent.com/92731398/142006978-3087ac0a-61c9-43d5-b6a3-f79d4e77f558.png)
ii. #2: Đăng nhập
![Screenshot (63)](https://user-images.githubusercontent.com/92731398/142007052-39c06703-24bc-49a2-b4a9-dc5ba40411a9.png)
iii. #3: Chọn Tra cứu học phần
<img width="960" alt="Screenshot (64)" src="https://user-images.githubusercontent.com/92731398/142007100-140d7351-8c4e-4810-b8d4-3a532aa850bd.png">
iv. #4: Chọn tìm theo mã học phần và nhập mã học phần
<img width="960" alt="Screenshot (65)" src="https://user-images.githubusercontent.com/92731398/142007138-8a079400-d4e9-4a9b-aebb-8827ad8c9b89.png">
(Kết quả khi tra cứu bằng tên học phần)
<img width="960" alt="Screenshot (66)" src="https://user-images.githubusercontent.com/92731398/142007188-365ecbb7-7db9-44e0-b3fd-b6b3b681a90e.png">
c. Kết quả thực tế: Không tra cứu được học phần bằng mã học phần
d. Kết quả mong đợi: Tra cứu được học phần bằng mã học phần

**Comment by hieeusnguyeenx** [comment]
@31191021724  Mã HP là cột ở ngoài cùng, do bạn tìm bằng Mã LHP nên không có kết quả nha
