### ISSUE TITLE
[Nhóm#10] Lỗi trang web quá tải khi 500 users tra cứu điểm rèn luyện cùng lúc- trang https://dsa.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191026529** [UEHMonQAQC/BI_K45#324]
a.Web Browser: Opera GX version 80.0.4170.86
b. Các bước phát hiện ra lỗi bằng Jmeter
i. #1 Truy cập Jmeter tạo thread group
![tạo thread](https://user-images.githubusercontent.com/83526024/142220708-d8603786-93f1-4cac-a591-36f5304fa168.png)
ii. #2 Nhập số lượng 500 users
![image](https://user-images.githubusercontent.com/83526024/142220858-c72ed822-ba84-40cc-a459-2f1895e2fe13.png)
iii. #3 Tạo HTTP Request
![tạo http](https://user-images.githubusercontent.com/83526024/142220973-401d6508-8d5a-4d36-9c01-b1ee162dc546.png)
iv. #4 Nhập link tra cứu điểm rèn luyện
![image](https://user-images.githubusercontent.com/83526024/142221985-59beaded-6901-4c5f-a2f3-f246b187e4ac.png)
v. #5 Tạo View results tree
![image](https://user-images.githubusercontent.com/83526024/142222689-5e40cc4f-31d7-48a5-a547-2e8843e8d1b4.png)
![image](https://user-images.githubusercontent.com/83526024/142222723-78f4d117-6388-4b93-a7d4-8d4c854e9502.png)
c. Kết quả thực tế:  Web quá tải khi 500 người tra cứu điểm rèn luyện cùng lúc
d. Kết quả mong đợi:  Web hoạt động cho phép 500 người tra cứu điểm rèn luyện cùng lúc

**Comment by 31191025698** [comment]
Như thầy đã đề cập từ những tuần trước không chấp nhận lỗi dùng kết quả trực tiếp từ tool như này.
