### ISSUE TITLE
[Nhóm#6] Lỗi khi yêu cầu đăng nhập bằng mail trường nhưng đăng nhập bằng gmail cá nhân vẫn đăng nhập bình thường - trang https://shcd.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191023504** [UEHMonQAQC/BI_K45#330]
a. Web browser: Google Chrome 95.0.4638.69
b. Các bước để phát hiện lỗi
i. #1 Truy cập vào trang https://shcd.ueh.edu.vn/ và kéo xuống đến phần "đăng nhập tài khoản của bạn trên gmail UEH":
![image](https://user-images.githubusercontent.com/92735488/142331545-756d4a0b-7bb3-4a79-aebf-12a905585464.png)
ii. #2 Điền gmail có đuôi không phải gmail trường (Gmail cá nhân) và nhấn "Tiếp theo": 
![image](https://user-images.githubusercontent.com/92735488/142331861-a4bf709e-f621-4d82-8837-51f9a69727fb.png)
iii. #3 Kết quả:
![image](https://user-images.githubusercontent.com/92735488/142332116-d6e90e32-915e-4cbb-a0cd-2298da1adfff.png)
c. Kết quả thực tế:
Hệ thống vẫn cho phép người dùng đăng nhập bằng gmail cá nhân
d. Kết quả mong đợi:
Hệ thống báo lỗi khi người dùng đăng nhập bằng gmail cá nhân

**Comment by 31191024332** [comment]
trùng với issue #61 mình đã xác nhận lỗi trước đó

**Comment by 31191023504** [comment]
Bạn ơi, đây là 2 issue khác nhau, 2 cái TÍNH NĂNG cũng khác nhau, mình hoàn toàn không đồng ý về việc bạn xem xét đó là lỗi bị trùng và mình chắc chắn 100% đó 2 lỗi đó hoàn toàn khác nhau, cụ thể  issue #61 là mình LIÊN KẾT tài khoản không phải mail UEH vẫn LIÊN KẾT ĐƯỢC, và thông tin issue 61 mình dùng tên mail là: whhy.01@gmail.com, còn issue 330 là khi mình KHÔNG CÓ LIÊN KẾT tài khoản với mail UEH ban đầu, nhưng vẫn đăng nhập bình thường với tên mail là whhy.03@gmail.com, có nghĩa là bạn đơn thuần dùng 1 gmail bất kì để đăng nhập mà không liên quan gì về mail UEH nhưng vẫn vào được trang chủ. QA xem xét lại giúp mình nhé. Xin cảm ơn

**Comment by 31191024332** [comment]
Tuy là 2 chức năng khác nhau nhưng chúng đều call đến API đăng nhập GG và không check subdomain của mail. Nhóm check lại giúp mình nhé @31191023504. Cảm ơn Nhóm

**Comment by 31191023504** [comment]
Cám ơn QA
