### ISSUE TITLE
[Nhóm#6] Hai button sắp xếp bị lệch, dính vào nhau - trang https://trading.tabbook.vn/

### ISSUE THREAD

**Issue by 31191021871** [UEHMonQAQC/BI_K45#331]
a. Web Browser: Google Chrome 95.0.4638.54
b. Các bước để phát hiện lỗi
i. #1 Truy cập vào trang https://trading.tabbook.vn/
ii. #2 Tiến hành đăng nhập 
iii. #3 nhấp chuột phải chọn kiểm tra
![kiẻmtra](https://user-images.githubusercontent.com/92736076/142333651-c0e6f5af-85a2-4f13-9105-43e045eb6487.png)
iv. #4: nhấp vào biểu tượng điện thoại
![cc](https://user-images.githubusercontent.com/92736076/142333739-3ee432aa-3063-4a94-903d-1b5bc989a9e8.png)
iv. #4: Chỉnh sang chế độ Iphone X
![ipnoe X](https://user-images.githubusercontent.com/92736076/142333568-c9ca1b7e-a9b7-47c0-bd3f-0bca8d210db1.png)
v. #5: Tiến hành thêm sản phẩm vào giỏ hàng 
![mua àng](https://user-images.githubusercontent.com/92736076/142333497-fa54c85b-ef48-4425-8cec-f04111fd6b2a.png)
vi. #6: Lên đầu trang chọn giỏ hàng chọn **Xem chi tiết giỏ hàng**
![chitiet](https://user-images.githubusercontent.com/92736076/142333941-52f22351-6db8-43bf-b5e4-1e9b9fcbf4f1.png)
c. Kết quả thực tế: Hai button **Tiếp tục tìm mặt hàng khác** và **Thanh toán** bị dính liền vào nhau
![loi](https://user-images.githubusercontent.com/92736076/142334134-cf6e518c-e912-4e5c-8ebe-02fcb64c29a6.png)
d. Kết quả mong đợi: Hai button **Tiếp tục tìm mặt hàng khác** và **Thanh toán** không bị dính liền vào nhau

**Comment by 31191024332** [comment]
Hi Nhóm. 
Mình đã check record thì thầy có giải đáp thắc mắc buổi học số 4 (phút thứ 3:33:00) thì dù hai button này vẫn click được nên mình từ chối lỗi này. Cảm ơn Nhóm
