### ISSUE TITLE
Nhóm#9] Không đồng bộ về màu sắc và kích cỡ của ô chữ - Trang: https://vieclam.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31191024635** [UEHMonQAQC/BI_K45#346]
a.Web Browser: Google Chrome 95.0.4638.69
b.Các bước phát hiện lỗi: 
i. #1: Truy cập trang: https://vieclam.ueh.edu.vn/ và đã đăng nhập, sau đó điều hướng đến trang hồ sơ ứng viên
![image](https://user-images.githubusercontent.com/92788705/142390296-c1703a7b-fff6-4028-89c9-e7bb2c43e3db.png)
ii. #2: Lướt xuống mục Công việc mong muốn và xem kết quả
![image](https://user-images.githubusercontent.com/92788705/142390094-49b1a2f4-5dc4-4f89-a24b-e0c1dc6772d4.png)
c. Kết quả thực tế: Các kênh chữ không đồng bộ về màu sắc và kích cỡ
d. Kết quả mong muốn: Các kênh chữ đồng nhất với nhau về định dạng.

**Comment by 31191025698** [comment]
Nó khác vì tính chất khác nhau, 1 cái là textbox, 1 cái là dropdown.
