### ISSUE TITLE
[Nhóm#8] Button Chọn một tệp không hoạt động - trang https://global.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191026190** [UEHMonQAQC/BI_K45#350]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi: 
i. #1: Truy cập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140551931-432799ce-f7e8-4543-856c-cdbcca12de3d.png)
ii. #2 Đăng nhập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/141406491-fe4e5cb6-fa41-4dda-a6be-56f027f377c0.png)
![image](https://user-images.githubusercontent.com/92732798/141406603-a2089bcd-4e57-45b3-a621-2bce561d7c79.png)
iii. #3 Kéo xuống và chọn Go to calendar:
![image](https://user-images.githubusercontent.com/92732798/142442142-84b371aa-d256-4f7f-a44f-3482ac75eb02.png)
iv. #4 Chọn Quản lí theo dõi:
![image](https://user-images.githubusercontent.com/92732798/142442395-2b8b813c-c648-4647-8aa7-b350a3118070.png)
v. #5 Ở mục Tệp lịch, button Chọn một tệp không hoạt động:
![image](https://user-images.githubusercontent.com/92732798/142442600-38229304-7c3e-4449-94e4-dc7be93c4938.png)
c. Kết quả thực tế: Button Chọn một tệp không hoạt động, không thể upload tệp lịch
d. Kết quả mong đợi: Button Chọn một tệp hoạt động được để có thể upload tệp lịch.

**Comment by hieeusnguyeenx** [comment]
@31191026190  Nếu thay đổi thành "Tệp lịch" thì vẫn nhập được nhé. 
![image](https://user-images.githubusercontent.com/87801356/142718290-a72f1ac0-f3d1-43fa-bec4-95df49f33733.png)
![image](https://user-images.githubusercontent.com/87801356/142718307-5873bca3-2a24-4d29-bbfa-984490c96c24.png)
