### ISSUE TITLE
[Nhóm#10] Lỗi không liên kết được với Facebook khi mời bạn bè quan tâm tại trang công thức - Trang https://www.cooky.vn/cong-thuc 

### ISSUE THREAD

**Issue by 31191026529** [UEHMonQAQC/BI_K45#354]
a.Web Browser: Opera GX version 80.0.4170.86
b. Các bước phát hiện ra lỗi:
 i. #1 Truy cập vào trang web vào mục công thức theo đường link sau:
![image](https://user-images.githubusercontent.com/83526024/142456479-47f469e2-4231-4552-8094-380228ea2e7d.png)
ii.#2 Chọn 1 thành viên
![image](https://user-images.githubusercontent.com/83526024/142456820-a036155d-be79-4da3-b054-27e7efd028f0.png)
iii.#3 Chọn Mời bạn bè
![image](https://user-images.githubusercontent.com/83526024/142457138-f74418a3-71e2-4773-8ba4-5a9416442cdf.png)
c. Kết quả thực tế: Không liên kết được với Facebook 
https://drive.google.com/file/d/1BrPmnGOdtX65S5O6giTeucc6MbjXeo6Z/view?usp=sharing
d. Kết quả mong đợi: Liên kết được Facebook

**Comment by 31191025698** [comment]
Cửa sổ mới được mở thuộc trang FB.
Không chấp nhận lỗi.

**Comment by 31191026529** [comment]
> Cửa sổ mới được mở thuộc trang FB. Không chấp nhận lỗi.

Cái này liên quan đến khả năng tương tác (Interoperability)  với Facebook. Vì không tương tác được với Facebook nên nhóm mình nghĩ là lỗi phi chức năng á

**Comment by 31191025698** [comment]
Nhóm tìm lỗi phi chức năng theo yêu cầu của thầy tại [file](https://docs.google.com/spreadsheets/d/1rOL-LSiaTWgBG3864rQdpbZ2Tj0_KXLO/edit#gid=1636255963)
Hiện tại, thầy yêu cầu chỉ chấp nhận lỗi PCN liên quan đến bảo mật và tốc độ.
