### ISSUE TITLE
[Nhóm#7] Lỗi hệ thống - Không nhấp vào I'm not a robot vẫn cho submit - trang https://smartlib.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31191024776** [UEHMonQAQC/BI_K45#358]
a. Web Browser: Microsoft Edge 95.0.1020.40
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang https://smartlib.ueh.edu.vn/, đăng nhập sẵn, kéo xuống dưới cùng
![trangchu](https://user-images.githubusercontent.com/92839124/140258282-1aec9ae8-cc4f-4a86-86c6-a02b69a514fe.JPG)

ii. #2: Ở phần Newsletter, nhập email vào
![image](https://user-images.githubusercontent.com/92839124/142468460-cf253d2b-a329-444f-8a09-169b059360e0.png)

iii. #3: Hệ thống hiển thị phần reCAPTCHA, không chọn mà bấm Signup
![image](https://user-images.githubusercontent.com/92839124/142468714-54d921fd-d454-424d-855c-1a904dc30530.png)

iv. #4: Hệ thống cho submit và hiện thông báo thành công
![image](https://user-images.githubusercontent.com/92839124/142468874-8facb20d-b255-4755-8114-3e7486a3cef1.png)

c. Kết quả thực tế: Người dùng ko cần nhấp vào ô I'm not a robot mà vẫn Sign up được, điều này sẽ khiến cho hệ thống dễ bị spam
d. Kết quả mong đợi: Người dùng phải nhấp vào ô I'm not a robot mới được Sign up

**Comment by 31191026515** [comment]
![image](https://user-images.githubusercontent.com/92660305/142656826-a42b1ad0-9b1f-4640-bdcd-24bb3638a034.png)

Thầy chỉ cho chấp nhận các lỗi phi chức năng này thôi, lỗi này không thuộc trong các lỗi đó nên mình tính không hợp lệ nha.
