### ISSUE TITLE
[Nhóm#6] Ô Hiển thị sự kiện gần đây và ô Sắp xếp theo không căn lề bằng nhau - Trang https://trading.tabbook.vn/

### ISSUE THREAD

**Issue by 31191024890** [UEHMonQAQC/BI_K45#36]
a. Web Browser: Ipad
b. Các bước phát hiện lỗi
i. #1: Truy cập vào trang https://trading.tabbook.vn/
<img width="288" alt="Screenshot 2021-11-03 194822" src="https://user-images.githubusercontent.com/85693426/140064640-252a64f2-ed3f-40a2-87fb-29b58cfed825.png">
ii. #2: Kéo xuống cuối trang và nhấp vào mục Sự kiện 
<img width="431" alt="Screenshot 2021-11-03 194933" src="https://user-images.githubusercontent.com/85693426/140064675-8513519d-a1de-44a8-a48e-4f5bcbb1750b.png">
iii. #3: Kết quả
<img width="434" alt="Screenshot 2021-11-03 195018" src="https://user-images.githubusercontent.com/85693426/140064892-70f65128-8c0c-4320-aa1a-09261900d6c4.png">
c. Kết quả thực tế: Ô Hiển thị sự kiện gần đây và ô Sắp xếp theo không căn lề bằng nhau.
d. Kết quả mong đợi: Ô Hiển thị sự kiện gần đây và ô Sắp xếp căn lề bằng nhau.

**Comment by 31191024332** [comment]
Hi Nhóm, mình thấy trong đây là do chủ ý của Dev. Họ cố ý để số cột lần lượt là 4 và 5 và cũng có căn lề trái cho cột rùi :')
![image](https://user-images.githubusercontent.com/82808388/140480552-674052d8-2f60-4658-9936-5f7e1e951ad3.png)
