### ISSUE TITLE
[Nhóm#8] Lỗi không ràng buộc thư điện tử - trang https://global.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191026190** [UEHMonQAQC/BI_K45#360]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140374105-8d37cc29-270b-4e96-ac2c-87a75f39e7f1.png)
ii. #2 Đăng nhập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140374376-f79538b3-b048-4d71-b0e7-c471db92d3e9.png)
iii. #3 Nhấp vào tên người dùng ở góc phải, chọn hồ sơ:
![image](https://user-images.githubusercontent.com/92732798/140374815-8f9ae99f-07d2-4b4e-8f06-175fc30aac58.png)
iv. #4 Chọn chức năng Sửa hồ sơ cá nhân
![image](https://user-images.githubusercontent.com/92732798/140374995-4f1a30b2-0302-4b17-99ad-a8048e18fb64.png)
v. #5 Ở mục thư điện tử, xóa email đăng nhập ban đầu và nhập một email bất kì.
![image](https://user-images.githubusercontent.com/92732798/142475144-ee85a975-c4fa-4945-bc98-289e41eca1d2.png)
![image](https://user-images.githubusercontent.com/92732798/142474937-82de2ca3-d0c1-4504-9804-980751be2e90.png)
vi. #6 Bấm Cập nhật hồ sơ thì thông tin được cập nhật thành công:
![image](https://user-images.githubusercontent.com/92732798/142475556-57f3835f-902d-4cf0-ab68-4f9fb55d8bbf.png)
c. Kết quả thực tế:  Sửa đổi thư điện tử khác với thư điện tử đã đăng nhập nhưng vẫn thành công.
d. Kết quả mong đợi: Hiển thị báo lỗi khi sửa đổi thư điện tử khác với thư điện tử đăng nhập.

**Comment by hieeusnguyeenx** [comment]
@31191026190  Email khi đăng nhập khi lưu xuống database nằm ở 1 column riêng, có thể trang web thầm định rằng bạn muốn đổi thư điện tử hiển thị để liên lạc. Nên không liên quan đến nhau
