### ISSUE TITLE
[Nhóm#7] Tính năng "Ask-us-now" lưu lại thông tin nhập trước đó dù đã đăng xuất - trang https://smartlib.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191027399** [UEHMonQAQC/BI_K45#361]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi
i.#1 Sử dụng Google Chrome với "Chế độ khách"
![image](https://user-images.githubusercontent.com/92789962/141412060-a6b5b032-f288-4144-860a-0f627f389e93.png)
ii.#2 : Truy cập vào trang SmartLibrary https://smartlib.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92789962/141411598-1326426c-4b08-4a9d-a829-995cfe58d5f8.png)
iii.#3: Chọn Button đăng nhập
![image](https://user-images.githubusercontent.com/92789962/141412928-8ea47704-071c-46a9-a5ba-8beef7e68863.png)
iv.#4: Đăng nhập vào tài khoản bằng Gmail của trường
![image](https://user-images.githubusercontent.com/92789962/141413083-e1dcbce5-20fa-41d3-92f8-d676e242a892.png)
v.#5: Chọn tính năng "Ask-us-now"
![image](https://user-images.githubusercontent.com/92789962/142476908-4e6371cd-60a0-486a-936f-fe21672e8967.png)
vi.#6: Nhập vào các trường từ "Your Name" đến "Message", không tick vào "Agree", không click vào button "Leave a message". 
Sau đó ấn dấu "-" để tắt tab Chat đi
![image](https://user-images.githubusercontent.com/92789962/142477498-56d5e6a3-9cbd-4923-92cd-11e738085a10.png)
![image](https://user-images.githubusercontent.com/92789962/142477652-4baa8a3b-df63-4144-8715-d37ad63fb3d4.png)
![image](https://user-images.githubusercontent.com/92789962/142478352-51a8563d-dbb4-4a09-aa03-4d797195ee34.png)
vii.#7: Logout tài khoản đã đăng nhập
![image](https://user-images.githubusercontent.com/92789962/141412350-7f947d05-1aa6-43be-9396-a10d16ba58b8.png)
viii.#8: Chọn tính năng "Ask-us-now"
![image](https://user-images.githubusercontent.com/92789962/142476908-4e6371cd-60a0-486a-936f-fe21672e8967.png)
Thông tin được nhập trước đó vẫn được lưu lại
![image](https://user-images.githubusercontent.com/92789962/142477889-1ea73869-b722-4b8d-89f8-a9705af2a062.png)
c. Kết quả thực tế: Thông tin được nhập từ lần đăng nhập trước đó đó vẫn được lưu lại.
d. Kết quả mong đợi: Sau khi logout, thông được từ lần đăng nhập trước được xóa đi.

**Comment by 31191027399** [comment]
Mình bổ sung video cách làm và tình trạng lỗi:
https://drive.google.com/file/d/1QKpUws1JD1bbBYtJDOtTV3CYAnlht2mU/view?usp=sharing

**Comment by 31191026515** [comment]
Mình không xác nhận lỗi này nha. Lý do vì cái chat box đó hoạt động độc lập với chức năng login, bạn nhập vào xong ẩn nó đi thì tất nhiên mở lại nó vẫn còn rồi.
