### ISSUE TITLE
[Nhóm#9] Lỗi dropdown mục "Chọn Tỉnh/TP" không hiển thị được hết các tỉnh/TP khi sử dụng web trên giao diện mobile - Trang https://m.phonhadat.net/

### ISSUE THREAD

**Issue by 31191021273** [UEHMonQAQC/BI_K45#367]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập trang https://m.phonhadat.net/
ii. #2: Chọn dropdown "Chọn Tỉnh/TP" và kéo xuống xem các tỉnh thành cuối cùng
![dropdown 1](https://user-images.githubusercontent.com/92793980/142564478-a5089730-e108-4f48-b6f9-fa20dc7d9ed2.png)
iii. #3: F12 và xem giao diện trên Iphone X, cũng kéo xuống dưới cùng và xem kết quả
![dropd2](https://user-images.githubusercontent.com/92793980/142564689-82fc1008-01b1-4d0b-965e-76e564d1b9e0.png)
c. Kết quả thực tế:
Không hiển thị được hết các Tỉnh/TP như giao diện web
d. Kết quả mong muốn:
Hiển thị được hết các Tỉnh/TP

**Comment by 31191025698** [comment]
Mình test thì vẫn hiển thị hết.
![image](https://user-images.githubusercontent.com/92703651/142577298-16c63079-2ffb-4eb4-89f3-67548a737c60.png)

**Comment by 31191024635** [comment]
Nhóm mình xem lại thì đúng là không phải lỗi. Cảm ơn QA @31191025698
