### ISSUE TITLE
[Nhóm#6] Lỗi chức năng Ordered List không hoạt động - trang https://trading.tabbook.vn/

### ISSUE THREAD

**Issue by 31191024890** [UEHMonQAQC/BI_K45#371]
a. Web browsers: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang https://trading.tabbook.vn/
![image](https://user-images.githubusercontent.com/85693426/142656021-5e9b3fad-502a-470b-9d74-d40f8ac74490.png)
ii. #2: Chọn mục Tài khoản của tôi
![image](https://user-images.githubusercontent.com/85693426/142656275-9beb8509-fbb2-4c81-92a3-7383b37856b7.png)
iii. #3: Chọn Đăng nhập
![image](https://user-images.githubusercontent.com/85693426/142656311-e1aff16d-8f20-4ba8-808d-c3436bb50ace.png)
iv. #4: Nhập thông tin đăng nhập
![image](https://user-images.githubusercontent.com/85693426/142656361-5c68841c-462a-4795-b3ba-6333b1299575.png)
v. #5: Chọn mục Đăng bán sản phẩm
![image](https://user-images.githubusercontent.com/85693426/142656395-954979fc-90c2-419c-a437-a7d47ed6687f.png)
vi. #6: Chọn Thêm sản phẩm
<img width="950" alt="themsp" src="https://user-images.githubusercontent.com/85693426/142656852-da0b8d99-5c69-4db3-b108-5a349bd1e236.png">
vii. #7: Nhập thông tin mô tả sản phẩm
<img width="950" alt="orderlist" src="https://user-images.githubusercontent.com/85693426/142656929-e01515dd-2527-4698-bcdf-ff6e372a1007.png">
viii. #8: Chọn chức năng Ordered List
<img width="949" alt="orderlist1" src="https://user-images.githubusercontent.com/85693426/142656995-e668aff4-c42b-4e44-bbf3-d1244644ad9c.png">
ix. #9: Kết quả 
<img width="949" alt="orderlistkq" src="https://user-images.githubusercontent.com/85693426/142657058-359a0049-9642-47a7-bb8e-0bd223b5ce71.png">
c. Kết quả thực tế: Không thực hiện được chức năng Ordered List
d. Kết quả mong đợi: Thực hiện được chức năng Ordered List

**Comment by 31191024332** [comment]
Tương tự như #334 đây không phải lỗi chức năng. Do ordered list đã được unable trên thư viện. Mình xin phép không xác nhận lỗi này

**Comment by 31191024890** [comment]
> Tương tự như #334 đây không phải lỗi chức năng. Do ordered list đã được unable trên thư viện. Mình xin phép không xác nhận lỗi này

Nếu mà unable thì cái icon của Ordered List nó phải biến mất, chứ ko thể để như vậy được, tại vì người dùng không biết là nó bị unable á.

**Comment by 31191024332** [comment]
> > Tương tự như #334 đây không phải lỗi chức năng. Do ordered list đã được unable trên thư viện. Mình xin phép không xác nhận lỗi này
> 
> Nếu mà unable thì cái icon của Ordered List nó phải biến mất, chứ ko thể để như vậy được, tại vì người dùng không biết là nó bị unable á.

Theo hướng nghĩ này thì sẽ thuộc về lỗi GUI hơn là chức năng á. Thầy có giải thích ở Buổi 5 (1:28:55) liên quan tới user usability - Nhóm bạn cân nhắc xem ntn

**Comment by 31191024890** [comment]
> > > Tương tự như #334 đây không phải lỗi chức năng. Do ordered list đã được unable trên thư viện. Mình xin phép không xác nhận lỗi này
> > 
> > 
> > Nếu mà unable thì cái icon của Ordered List nó phải biến mất, chứ ko thể để như vậy được, tại vì người dùng không biết là nó bị unable á.
> 
> Theo hướng nghĩ này thì sẽ thuộc về lỗi GUI hơn là chức năng á. Thầy có giải thích ở Buổi 5 (1:28:55) liên quan tới user usability - Nhóm bạn cân nhắc xem ntn

Chỗ (1:28:55) thầy có nói là cái đó nó khó xài á thì mới đưa vào lỗi GUI, còn cái ordered list này của nhóm mình là nó không sài dc luôn á bạn ơi. Bạn xem lại giúp mình nhe

**Comment by 31191024332** [comment]
Do bạn có ghi 

> > > > Tương tự như #334 đây không phải lỗi chức năng. Do ordered list đã được unable trên thư viện. Mình xin phép không xác nhận lỗi này
> > > 
> > > 
> > > Nếu mà unable thì cái icon của Ordered List nó phải biến mất, chứ ko thể để như vậy được, tại vì người dùng không biết là nó bị unable á.
> > 
> > 
> > Theo hướng nghĩ này thì sẽ thuộc về lỗi GUI hơn là chức năng á. Thầy có giải thích ở Buổi 5 (1:28:55) liên quan tới user usability - Nhóm bạn cân nhắc xem ntn
> 
> Chỗ (1:28:55) thầy có nói là cái đó nó khó xài á thì mới đưa vào lỗi GUI, còn cái ordered list này của nhóm mình là nó không sài dc luôn á bạn ơi. Bạn xem lại giúp mình nhe

B

> > > > Tương tự như #334 đây không phải lỗi chức năng. Do ordered list đã được unable trên thư viện. Mình xin phép không xác nhận lỗi này
> > > 
> > > 
> > > Nếu mà unable thì cái icon của Ordered List nó phải biến mất, chứ ko thể để như vậy được, tại vì người dùng không biết là nó bị unable á.
> > 
> > 
> > Theo hướng nghĩ này thì sẽ thuộc về lỗi GUI hơn là chức năng á. Thầy có giải thích ở Buổi 5 (1:28:55) liên quan tới user usability - Nhóm bạn cân nhắc xem ntn
> 
> Chỗ (1:28:55) thầy có nói là cái đó nó khó xài á thì mới đưa vào lỗi GUI, còn cái ordered list này của nhóm mình là nó không sài dc luôn á bạn ơi. Bạn xem lại giúp mình nhe

Bạn có ghi là "tại vì người dùng không biết là nó bị unable á." nên mình mới cân nhắc nó là lỗi GUI á. Chi tiết giải thích mình có cmt tại issue #334

**Comment by 31191024332** [comment]
Cùng 1 editor nên mình xác nhận lỗi 1 lần ở 334. Cảm ơn Nhóm rất nhiều
