### ISSUE TITLE
[Nhóm#9] Có thể copy được tài liệu trong khi trang web đã khóa tính năng này - Trang: https://123docz.net/

### ISSUE THREAD

**Issue by 31191024635** [UEHMonQAQC/BI_K45#376]
a.Web Browser: Google Chrome 95.0.4638.69
b.Các bước phát hiện lỗi:
i. #1: Kiểm tra lượt truy cập của web trên similarweb: https://www.similarweb.com/fr/website/123docz.net/
![image](https://user-images.githubusercontent.com/92788705/142762972-2561a292-738c-4989-b0a2-dfaddebdb00c.png)
ii. #2: Truy cập vào trang: https://123docz.net/ 
iii. #3: Chọn bất kỳ một bài viết nào có trả phí. Ví dụ như bài viết này: https://123docz.net/document/12047-vai-tro-cua-tich-luy-tu-ban-trong-qua-trinh-hinh-thanh-va-phat-trien-kinh-te-tu-ban-chu-nghia-doc.htm
![image](https://user-images.githubusercontent.com/92788705/142763548-3ad21a6d-2742-4494-ae4e-128d1c2e6833.png)
iv. #4: Bấm chuột phải chọn save as để lưu file về desktop (định dạng file là: Webpage, Complete)
![image](https://user-images.githubusercontent.com/92788705/142763155-b02a041c-e701-4f47-bfcc-aff08a311ebf.png)
![image](https://user-images.githubusercontent.com/92788705/142763196-b340e81c-1dea-4786-842f-355c991d37b6.png)
v. #5: Tìm và mở file mới tải về bằng notepad
![image](https://user-images.githubusercontent.com/92788705/142763326-1e14025a-709e-4bfa-9020-3df4e79aac1f.png)
vi. #6: Ctrl F để tìm kiếm từ khóa "false" và thấy dòng lệnh như hình dưới:
![image](https://user-images.githubusercontent.com/92788705/142763395-93c09504-52ab-4b83-bccb-997bf4e2a072.png)
![image](https://user-images.githubusercontent.com/92788705/142763413-9513a17c-6491-437b-89ca-8e6007f77f26.png)
vii. #7: Thay đổi tất cả các chữ "false" thành "true" ta được câu lệnh mới: 
![image](https://user-images.githubusercontent.com/92788705/142763452-62a96b80-5a83-4c27-810a-43ba0462eb17.png)
viii. #8: Nháy đúp chuột để mở file như bình thường và xem kết quả.
![image](https://user-images.githubusercontent.com/92788705/142763527-e3e8da02-3945-48bb-bcbd-9a778a789dbf.png)
c. Kết quả thực tế: Có thể copy được tài liệu sau khi can thiệp vào code.
d. Kết quả mong đợi: Sau khi can thiệp vào code, mở file hiển thị trang lỗi.

**Comment by 31191025698** [comment]
Như thầy đã đề cập buổi 7.
