### ISSUE TITLE
[Nhóm#9] Email không tồn tại nhưng vẫn đăng kí thành công - Trang https://vieclam.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191026463** [UEHMonQAQC/BI_K45#379]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập trang https://vieclam.ueh.edu.vn/ sau đó chọn "Đăng nhập/ Đăng ký"
![22-6](https://user-images.githubusercontent.com/92785792/142804425-94fed664-da66-46e7-83fc-98988ee02024.PNG)
ii. #2: Chọn "Đăng ký cho Sinh viên/ Ứng viên"
![22-7](https://user-images.githubusercontent.com/92785792/142804529-d5d2f4d2-baa2-4add-a28e-7b5dcc678204.PNG)
iii. #3: Điền tất cả thông tin và Email như hình sau đó bấm đăng ký
![22-8](https://user-images.githubusercontent.com/92785792/142804980-818c16ac-62bc-4642-88a7-ee5dfe5956db.PNG)
iv. #4: Xem kết quả
![22-9](https://user-images.githubusercontent.com/92785792/142805023-2840df08-41fa-4b48-89af-85a54eb65116.PNG)
c. Kết quả thực tế: Đăng ký thành công và hệ thống không kiểm tra Email đã tồn tại hay chưa
d. Kết quả mong đợi: Hiển thị thông báo Email không tồn tại

**Comment by 31191025698** [comment]
Trang không có chức năng xác thực gmail nên không thể cho là lỗi chức năng.

**Comment by 31191026463** [comment]
Theo mình tìm hiểu thì lỗi này khá giống lỗi năm ngoái và được xác nhận lỗi. Bạn coi lại giúp mình!
https://github.com/UEHMonQAQC/ST_K44/issues/122
@31191025698
