### ISSUE TITLE
[Nhóm#4] Lỗi XSS tại thanh tìm kiếm - trang https://www.nguoiduatin.vn/bao-moi

### ISSUE THREAD

**Issue by 31191024175** [UEHMonQAQC/BI_K45#384]
a. Web Browser: Google Chrome: Phiên bản 95.0.4638.69 (Phiên bản Chính thức) (64 bit)                      
b. Các bước để phát hiện lỗi:
i. #1:  Kiểm tra lượng truy cập của trang https://www.nguoiduatin.vn/bao-moi
![2](https://user-images.githubusercontent.com/87383454/143047545-0ac11017-ab58-434e-b3ec-37bcc9479d07.jpg)
ii. #2: Truy cập vào trang trang https://www.nguoiduatin.vn/bao-moi
![1](https://user-images.githubusercontent.com/87383454/143047694-2171437a-ed57-432a-b10d-c67c164f6686.jpg)
iii. #3: Điền <script>alert('cám ơn bạn')</script> vào thanh tìm kiếm.
![3](https://user-images.githubusercontent.com/87383454/143048031-6d4d8dc9-2f4d-4007-a7db-85240380001f.jpg)
iv. #4 Sau khi web hiện lên "cám ơn bạn" thì nhấn OK.
![4](https://user-images.githubusercontent.com/87383454/143048638-3bd8f56a-9f9e-4c12-9968-833a32800d03.jpg)
c.Kết quả thực tế: 
Đoạn mã: <script>alert('cám ơn bạn')</script> được thực thi
d.Kết quả mong đợi: 
Đoạn mã: <script>alert('cám ơn bạn')</script>  không được thực thi

**Comment by 31191022164** [comment]
Thầy có nhận xét về lỗi này của nhóm là không phải lỗi phi chức năng nha.
