### ISSUE TITLE
[Nhóm#4] Không mã hóa tài khoản, mật khẩu sau khi đăng nhập - trang https://www.tienganh123.com/

### ISSUE THREAD

**Issue by 31191026606** [UEHMonQAQC/BI_K45#385]
a. Phần mềm Burp Suite Community Edition v2021.10.2                   
b. Các bước để phát hiện lỗi:
i. #1: Khởi động Burp Suite, set up như hình bên dưới và nhấn vào "Open Browser"
![Pro1](https://user-images.githubusercontent.com/92720997/143052623-a4eb1f20-de34-4248-a192-73c15887e1fb.JPG)
ii. #2: Đăng nhập vào trang https://www.tienganh123.com/
![Pro2](https://user-images.githubusercontent.com/92720997/143052647-feea1b35-144e-4414-b143-f106cb1ef1af.JPG)
iii. #3: Chọn Proxy -> HTTP history -> tìm kiếm địa chỉ trang với phương thức "POST" và URL "login"
![Pro3](https://user-images.githubusercontent.com/92720997/143052669-8ba2f0e0-d85a-4af3-86be-358e1c650681.JPG)

Link video chứng minh:
https://drive.google.com/file/d/1rXpkOO3yABsbSrgj3CA1e3hdZ6T3WqKF/view?usp=sharing
c.Kết quả thực tế: Ở phần Request kéo xuống phần login, chúng ta có thể thấy tài khoản và mật khẩu người dùng.
d.Kết quả mong đợi: Mã hóa phần login Request
![Pro4](https://user-images.githubusercontent.com/92720997/143052689-f9283c15-c66c-4d74-916e-2f23bbf75ee2.JPG)

**Comment by 31191022164** [comment]
Mình đã thử nhưng không tìm ra, nhóm cho mình xin video test nha @31191026606
