### ISSUE TITLE
[Nhóm#7] Lỗi XSS tại textbox - trang https://chanhtuoi.com/

### ISSUE THREAD

**Issue by 31191024776** [UEHMonQAQC/BI_K45#386]
a. Web Browser: Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang chủ Chanh Tươi và đăng nhập, chọn phần Tạo Deals
![image](https://user-images.githubusercontent.com/92839124/143071033-ca8d55c1-1eb6-4f82-a777-379a6a561bc7.png)

ii. #2: ở khung textbox **Tiêu đề**, dán <script>alert(123)</script>

![image](https://user-images.githubusercontent.com/92839124/143071129-f3c1fc90-59ef-4b03-86d2-881da028776b.png)

iii. #3: Hệ thống hiển thị thông báo "123"
![image](https://user-images.githubusercontent.com/92839124/143071326-273949f7-3264-434f-bf1d-957e064a77d2.png)

Ảnh chứng minh lưu lượng truy cập trong tháng
![image](https://user-images.githubusercontent.com/92839124/143072336-76486f1c-df0f-4f07-872c-968fad1ec802.png)

c. Kết quả thực tế: Hệ thống nảy thông báo , đoạn script được thực thi
d. Kết quả mong đợi: Hệ thống không nảy thông báo

**Comment by 31191026515** [comment]
Mình không xác nhận lỗi này nha. Lý do như lỗi #388
