### ISSUE TITLE
[Nhóm#7] Lỗi XSS tại textbox - trang https://gaubongonline.com.vn/

### ISSUE THREAD

**Issue by 31191024776** [UEHMonQAQC/BI_K45#388]
a. Web Browser: Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang chủ Gấu bông online
![image](https://user-images.githubusercontent.com/92839124/143072896-728a6013-f201-483c-9c30-dbab8b433432.png)
ii. #2 Kéo xuống chọn 1 sản phẩm bất kỳ
![image](https://user-images.githubusercontent.com/92839124/143072967-ac63d1f0-2025-4827-a6af-fcd650f59bc0.png)

iii.#3: Ở phần textbox Nhập số điện thoại, nhập <script>alert()</script> và nhấn Gửi
![image](https://user-images.githubusercontent.com/92839124/143073137-32f7f396-9d8f-41d2-993d-710e881482f9.png)

Ảnh lưu lượng truy cập của trang gaubongonline
![image](https://user-images.githubusercontent.com/92839124/143074001-750d844f-589f-4054-9630-0b65fbbbe494.png)
c. Kết quả thực tế: Hệ thống nảy thông báo , đoạn script được thực thi
d. Kết quả mong đợi: Hệ thống không nảy thông báo

**Comment by 31191026515** [comment]
Mình không xác nhận lỗi này nha. Lý do mình giải thích ở video này: https://drive.google.com/file/d/1yf8nPVI1Jk_BOlPNCbVdZpsbfFiakryH/view?usp=sharing
