### ISSUE TITLE
[Nhóm#7] Lỗi bảo mật folder hình ảnh- trang https://gauteddy.vn/

### ISSUE THREAD

**Issue by 31191024776** [UEHMonQAQC/BI_K45#390]
a. Web Browser: Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang chủ Gấu Teddy https://gauteddy.vn/ , chọn 1 hình ảnh sản phẩm bất kỳ , chuột phải và nhấn " Open image in new link"

![image](https://user-images.githubusercontent.com/92839124/143079624-9c5de9cc-b2f1-418c-b22f-f6f6bd43cabf.png)

ii. #2: Xóa phần được khoanh tròn và enter
![image](https://user-images.githubusercontent.com/92839124/143517852-70fe2327-8a38-4fa5-a2ad-71a0a0aecf57.png)

iii. #3: ở đây ta truy cập được vào các file ảnh của web
![image](https://user-images.githubusercontent.com/92839124/143079297-627a7673-4e78-411a-bce8-55a434689642.png)

Ảnh lưu lượng truy cập của trang gauteddy.vn
![image](https://user-images.githubusercontent.com/92839124/143079433-b4d9e729-f5d8-455b-b83d-a2350cf3ab9f.png)

c. Kết quả thực tế: Người dùng truy cập được vào file ảnh, file css
d. Kết quả mong đợi: Khi người dùng truy cập vào thì hệ thống phải hiển thị Forbiden

**Comment by 31191026515** [comment]
Nhóm chỉnh lại format giúp mình nha:
- Bước 1 cần thêm link trang chủ. Chọn 1 ảnh bất kỳ là bất kỳ ảnh nào của web cũng được (bao gồm ảnh logo, banner, ảnh sản phẩm,...) hay chỉ cụ thể là ảnh bất kỳ trong phần ảnh sản phẩm?
- Bước 2 mình thấy khoanh từ chữ "uploads" cho đến hết như tới bước 3 lại còn phần chữ "uploads"

Nhóm kiểm tra lại web thử còn truy cập được không nha, mình vào thì cứ load hoài không có chạy á.
![image](https://user-images.githubusercontent.com/92660305/143386272-c661f2c2-6e78-4346-bfd7-e68cd4e499fc.png)

**Comment by 31191024776** [comment]
Trang edit lại rồi á Quỳnh ơi

**Comment by 31191026515** [comment]
Mình không xác nhận lỗi này vì lý do những hình ảnh này web cho tải về, cho phép xem ảnh công khai. Truy cập vào file ảnh nhưng không thay đổi ảnh trên web hay có thể thao tác gì gây ảnh hưởng đến web.

**Comment by 31191024776** [comment]
Mình thấy phần data của web thường là chỉ có admin được cấp quyền truy cập, nên web này lại để người dùng truy cập vào cái kho data ko thuộc quyền của mình thì mình nghĩ là lỗi á

**Comment by 31191026515** [comment]
Lúc nãy thầy có giải thích rồi nha
