### ISSUE TITLE
[Nhóm#7] Lỗi XSS tại textbox - trang https://gaubongvip.com/

### ISSUE THREAD

**Issue by 31191024776** [UEHMonQAQC/BI_K45#392]
a. Web Browser: Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang chủ gaubongvip, kéo xuống chọn mua 1 sản phẩm
![image](https://user-images.githubusercontent.com/92839124/143083541-9b7ff99b-f245-4a2a-93d4-45ea778df94e.png)

ii. #2: Chọn Mua hàng
![image](https://user-images.githubusercontent.com/92839124/143083660-64d75a5d-576c-43c7-b556-42001ffe1928.png)

iii. #3: Chọn Thanh toán
![image](https://user-images.githubusercontent.com/92839124/143083752-cd296780-5fa4-4dfe-8dd3-2c5aafa86284.png)

iv. #4 NHập script <script>alert(123)</script> vào textbox, nhập Mã an toàn và bấm Đặt mua
![image](https://user-images.githubusercontent.com/92839124/143083796-aec2cc3b-6c2d-48cb-a049-7f5d6da4069d.png)

v. #5: Hệ thống chuyển qua trang và hiển thị thông báo "123"
![image](https://user-images.githubusercontent.com/92839124/143083968-54db539a-bb5c-4001-8f1f-080c8f096e53.png)

Ảnh lưu lượng truy cập của trang gaubongvip
![image](https://user-images.githubusercontent.com/92839124/143084109-2e9ac112-f619-4d8d-a05e-61c7cdfca8c1.png)

c. Kết quả thực tế: Hệ thống nảy thông báo , đoạn script được thực thi
d. Kết quả mong đợi: hệ thống không nảy thông báo "123"

**Comment by 31191027399** [comment]
lỗi XSS BỊ TRÙNG, CLOSED NHA
