### ISSUE TITLE
[Nhóm#3] Nội dung căn lề không đều - trang https://vexere.com/

### ISSUE THREAD

**Issue by ddongvi** [UEHMonQAQC/BI_K45#40]
a.Web Browser: Google Chrome 95.0.4638.54
b.Các bước để phát hiện lỗi:
i. #1: truy cập vào trang https://vexere.com/
<img width="1440" alt="Screen Shot 2021-11-03 at 22 44 17" src="https://user-images.githubusercontent.com/92705124/140094046-a250c1be-e483-4e1e-83c0-b18070619920.png">
ii. #2: Kéo xuống giữa trang chọn "Bến xe Gia Lâm"
<img width="1440" alt="Screen Shot 2021-11-03 at 22 45 25" src="https://user-images.githubusercontent.com/92705124/140094248-a2e65293-cc2c-4ffb-b218-2bd9e03f526e.png">
iii. #3 Cuộn xuống cuối trang xem kết quả
<img width="1440" alt="Screen Shot 2021-11-03 at 22 46 53" src="https://user-images.githubusercontent.com/92705124/140094420-b250f83b-ca81-4534-9e43-32118321e8c0.png">
c.Kết quả thực tế: Đề mục "Chấp cánh ước mơ" không được căn đều
d.Kết quả mong đợi: Các nội dung trong trang phải được căn lề đều nhau.

**Comment by 31191022164** [comment]
Mình đã check và xác nhận đây không phải là lỗi nha. Lề căn đúng, ở trước "quyển sách" là khoảng trắng của ảnh.

**Comment by ddongvi** [comment]
<img width="640" alt="Screen Shot 2021-11-09 at 01 29 46" src="https://user-images.githubusercontent.com/92705124/140797766-55ac8341-f53f-452a-ac6d-dc6a2ae2e2db.png">
Mình có zoom to ra để check kĩ hơn, bạn xem thử lại giúp mình.
