### ISSUE TITLE
[Nhóm#9] Lỗi bảo mật tài liệu - trang https://studyhippo.com/

### ISSUE THREAD

**Issue by 31191026463** [UEHMonQAQC/BI_K45#407]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Kiểm tra lượng truy cập trang: https://studyhippo.com/ và kết quả lượng truy cập trên 300/tháng
![image](https://user-images.githubusercontent.com/92785792/143162486-0111e12d-01d1-478d-9515-99c8242fc75e.png)
ii. #2: Truy cập trang: https://studyhippo.com/
iii. #3: Tiếp tục chọn mục SAMPLES
![image](https://user-images.githubusercontent.com/92785792/143163708-41ed2b99-8906-4e2b-b066-d948bb9d08b7.png)
iv. #4: Kéo xuống phần Most popular subjects chọn Education
![image](https://user-images.githubusercontent.com/92785792/143163787-2f1c7154-9306-44d3-8821-c18ae7c199a3.png)
v. #5: Tiếp tục chọn Read more
![image](https://user-images.githubusercontent.com/92785792/143163866-0ddc49bd-6a17-464c-9980-9643a21401cd.png)
vi. #6: Kéo xuống đến phần tài liệu bị làm mờ, click chuột phải chọn kiểm tra
![image](https://user-images.githubusercontent.com/92785792/143163925-ce959ea0-f6a4-48f5-9d74-aa552c02553d.png)
vii. #7: Nhấn vào nút bên trái phần Elements sau đó chọn vào tài liệu bị mờ
![image](https://user-images.githubusercontent.com/92785792/143164209-ad1d1d48-0503-49bb-850c-ad2481612a65.png)
viii. #8: Chọn dòng code như hình
![image](https://user-images.githubusercontent.com/92785792/143164346-f2aabc96-6635-4574-a6fa-72eefe7fbd79.png)
ix. #9: Sửa đoạn "sample-preview-blur__inner" thành "none" sau đó bấm Enter và xem kết quả
![image](https://user-images.githubusercontent.com/92785792/143165333-33e96a28-b07a-4a34-bab5-afdda0a5c9c2.png)
c. Kết quả thực tế: Có thể xem được tài liệu đã được làm mờ trước đó.
d. Kết quả mong đợi: Không thể xem được tài liệu đã được làm mờ trước đó.

**Comment by 31191025698** [comment]
Như thầy đã đề cập buổi 7.
