### ISSUE TITLE
[Nhóm#7] Lỗi XSS tại thanh tìm kiếm- trang https://noithatdogoviet.com/

### ISSUE THREAD

**Issue by 31191023780** [UEHMonQAQC/BI_K45#410]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web https://noithatdogoviet.com/
ii.#2: Nhập vào thanh tìm kiếm nội dung "<script>alert()</script> ", sau đó chọn button có biểu tượng kính lúp
![1](https://user-images.githubusercontent.com/92867185/143184223-e171a161-2a34-49f6-af86-160813a882c6.PNG)

iii.#3: Hệ thống hiển thị thông báo
![2](https://user-images.githubusercontent.com/92867185/143184253-cd53a56d-5e7a-4f73-9994-71bee417f978.PNG)

Ảnh lưu lượng truy cập của https://noithatdogoviet.com/
![image](https://user-images.githubusercontent.com/92867185/143184163-4e4b7bf9-9c12-4638-bcbd-db2c4e824be8.png)

c. Kết quả thực tế: Hệ thống hiển thị thông báo, script được thực thi
d. Kết quả mong đợi: Hệ thống không nảy thông báo

**Comment by 31191027399** [comment]
lỗi XSS bị trùng, closed nha
