### ISSUE TITLE
[Nhóm#7] Lỗi XSS tại thanh tìm kiếm- trang https://www.artplode.com/

### ISSUE THREAD

**Issue by 31191023780** [UEHMonQAQC/BI_K45#411]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web https://www.artplode.com/
ii.#2: Nhập vào thanh tìm kiếm nội dung "<script>alert("XSS attack!");</script>", sau đó chọn button có biểu tượng kính lúp
![1](https://user-images.githubusercontent.com/92867185/143215850-cefa83d9-3411-44e5-962f-d46b45e6712b.PNG)

iii.#3: Hệ thống hiển thị thông báo
![2](https://user-images.githubusercontent.com/92867185/143215877-75b134d8-8a93-4a6b-8f0f-18825494460a.PNG)

Ảnh lưu lượng truy cập củahttps://www.artplode.com/
![259580875_1422901038106431_1162967538356471428_n](https://user-images.githubusercontent.com/92867185/143215817-ad20ac56-8806-49d5-b374-21e352639ddb.png)

c. Kết quả thực tế: Hệ thống hiển thị thông báo, script được thực thi
d. Kết quả mong đợi: Hệ thống không nảy thông báo

**Comment by 31191027399** [comment]
lỗi xss bị trùng, closed nha
