### ISSUE TITLE
[Nhóm#7] Lỗi XSS tại thanh tìm kiếm- trang http://www.saomainews.com.vn/

### ISSUE THREAD

**Issue by 31191025157** [UEHMonQAQC/BI_K45#412]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web http://www.saomainews.com.vn
ii.#2: Nhập vào thanh tìm kiếm nội dung "<script>alert("XSS attack!");</script>", sau đó chọn button có biểu tượng kính lúp
![image](https://user-images.githubusercontent.com/92876716/143219499-c927ed44-999f-46a0-8e22-f2c84ff116c7.png)
iii.#3: Hệ thống hiển thị thông báo
![image](https://user-images.githubusercontent.com/92876716/143219614-dcb632cc-8564-4601-82c2-73aa4bc429da.png)
Ảnh lưu lượng truy cập của http://www.saomainews.com.vn
![image](https://user-images.githubusercontent.com/92876716/143219869-d2283c55-87b7-4086-9e2f-5f46054042b4.png)
c. Kết quả thực tế: Hệ thống hiển thị thông báo, script được thực thi
d. Kết quả mong đợi: Hệ thống không nảy thông báo

**Comment by 31191027399** [comment]
Lỗi xss bị trùng, closed nha
