### ISSUE TITLE
[Nhóm 7] Lỗi XSS tại textbox tìm kiếm- trang https://dinhgianhadat.vn

### ISSUE THREAD

**Issue by 31191025157** [UEHMonQAQC/BI_K45#413]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web https://dinhgianhadat.vn
ii.#2:  Nhập vào thanh tìm kiếm nội dung "<script>alert("Hello QA!");</script>", sau đó chọn button "Tìm nhanh"
![image](https://user-images.githubusercontent.com/92876716/143221305-8c9384f3-01c2-4f83-a743-1ee8f2498463.png)
iii.#3: Hệ thống hiển thị thông báo
![image](https://user-images.githubusercontent.com/92876716/143221385-8a0d4c09-be80-463f-8c89-8709df9b3f32.png)
Ảnh lưu lượng truy cập của https://dinhgianhadat.vn
![image](https://user-images.githubusercontent.com/92876716/143221543-f3dad981-5e2a-4d3f-ad05-40c1470687af.png)
c. Kết quả thực tế: Hệ thống hiển thị thông báo, script được thực thi
d. Kết quả mong đợi: Hệ thống không nảy thông báo

**Comment by 31191027399** [comment]
lỗi bị trùng, closed nha
