### ISSUE TITLE
[Nhóm#3] Lỗi XSS tại textbox Tìm kiếm - trang https://babycuatoi.vn/

### ISSUE THREAD

**Issue by 31191026769** [UEHMonQAQC/BI_K45#416]
a. Web browsers: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
#1: Truy cập vào trang https://babycuatoi.vn/
![![image](https://user-images.githubusercontent.com/92705375/143239081-3a2e3c36-8caa-447d-95eb-c6d00a7b5d01.png)](https://user-images.githubusercontent.com/92705375/143238895-02617b64-9fdb-4c75-b0d4-d9d85d06da4c.png)
#2: Nhập vào thanh tìm kiếm đoạn mã "<script>alert('Quang Hiếu nè')</script>", sau đó nhấp vào nút Tìm kiếm
![image](https://user-images.githubusercontent.com/92705375/143238958-7c2a55db-2cf5-4ef6-893b-44e8d662a17f.png)
#3: Kết quả
![image](https://user-images.githubusercontent.com/92705375/143239149-1400701e-36a8-4db2-9bce-5b67f59b1d1f.png)
Ảnh lượng truy cập trang https://babycuatoi.vn/
![image](https://user-images.githubusercontent.com/92705375/143239191-2e6533b0-ebd2-41f2-ad1d-4689384f3715.png)
![image](https://user-images.githubusercontent.com/92705375/143239238-0ebec77d-af16-4225-aa38-c6ef550eeccf.png)

c.Kết quả thực tế: Đoạn mã được thực thi
d.Kết quả mong đợi: Đoạn mã không được thực thi

**Comment by ddongvi** [comment]
<img width="1440" alt="Screen Shot 2021-11-24 at 19 39 58" src="https://user-images.githubusercontent.com/92705124/143240269-d770883c-f52b-4796-ae2c-06e67217a9d9.png">
