### ISSUE TITLE
[Nhóm#9] Lỗi bảo mật thông tin giỏ hàng - trang https://aeoneshop.com/

### ISSUE THREAD

**Issue by 31191025750** [UEHMonQAQC/BI_K45#420]
a.	Web Browser: Google Chrome 95.0.4638.69
b.	Các bước phát hiện lỗi:
i.	#1: Truy cập vào trang: https://aeoneshop.com/ 
![lỗi 1](https://user-images.githubusercontent.com/92785502/143269317-db019bba-030f-4be2-a943-bbca11b60cf2.png)
ii.	#2: Đăng nhập bằng gmail
![lỗi 11](https://user-images.githubusercontent.com/92785502/143269719-40921567-9cc7-497d-a07f-ae4f0b45af62.png)
iii.	#3: Sau đó thêm sản phẩm bất kỳ vào giỏ hàng
![lỗi 111](https://user-images.githubusercontent.com/92785502/143269762-e6505718-4f59-4ecd-80b8-b91692645815.png)
iv.	#4: Đăng xuất tài khoản
![lỗi 1111](https://user-images.githubusercontent.com/92785502/143269793-eebcf13d-509c-4a3a-a5db-3965931dbc45.png)
v.	#5: Đăng nhập một tài khoản khác
![lỗi 11111](https://user-images.githubusercontent.com/92785502/143269878-0ba4ad37-9bba-4a9d-86ba-5249ef9b6abd.png)
vi.	#6: Kiểm tra giỏ hàng
![lỗi 111111](https://user-images.githubusercontent.com/92785502/143269927-3757af4a-0e77-41d4-99b0-9221adbae289.png)
c.	Kết quả thực tế: sau khi đăng nhập bằng tài khoản khác vẫn xem được thông tin giỏ hàng của tài khoản đã đăng nhập trước đó
d.	Kết quả mong đợi: sau khi đăng xuất tài khoản và đăng nhập tài khoản khác sẽ không xem được thông tin giỏ hàng của tài khoản trước đó.
e.     Lưu lượng truy cập trang https://aeoneshop.com/
![lỗi](https://user-images.githubusercontent.com/92785502/143270889-73cd1666-ff4c-49c9-a08c-b7bbfb879f30.png)

**Comment by 31191025698** [comment]
Như thầy đã đề cập buổi 7.
