### ISSUE TITLE
[Nhóm#4] Lỗi bảo mật thông tin giỏ hàng - trang https://cellphones.com.vn

### ISSUE THREAD

**Issue by 31191024175** [UEHMonQAQC/BI_K45#421]
a. Web Browser: Edge  version 96.0.1054.34 
b. Các bước phát hiện ra lỗi:
i.#1: Check lượng truy cập của trang https://cellphones.com.vn
![viii](https://user-images.githubusercontent.com/87383454/143377051-0cad1788-c274-4429-b89f-cd93fe5c7765.jpg)

ii. #2: Truy cập vào trang web: https://cellphones.com.vn
![i](https://user-images.githubusercontent.com/87383454/143375005-25e9ad34-ffc7-4db5-b98f-31534d3955ad.jpg)

iii. #3: Chọn đăng nhập tài khoản gmail và xác nhận mã OTP qua sđt
![ii](https://user-images.githubusercontent.com/87383454/143375017-e3dc9d68-5fc7-4cc0-826a-3b13b8a81eb7.jpg)

iv. #4: Chọn mua một sản phẩm bất kì
![iii](https://user-images.githubusercontent.com/87383454/143375042-5c099d27-1488-439a-bfa6-a3b23bd1af6b.jpg)

v. #5: Đăng xuất tài khoản
![iv](https://user-images.githubusercontent.com/87383454/143375060-7cda8aa9-a34e-4971-bbc1-fa70a89fd391.jpg)

vi. #6: Đăng nhập tài khoản gmail và sđt khác
![v](https://user-images.githubusercontent.com/87383454/143375071-0d5e4925-7b56-4323-b344-56438662f28c.jpg)

 vii. #7: Sau khi đăng nhập thành công nhấp vào icon giỏ hàng
![vi](https://user-images.githubusercontent.com/87383454/143375093-72a9c35e-0457-4337-91a0-255ad52fc7b9.jpg)

c. Kết quả thực tế: Sau khi đăng nhập bằng tài khoản khác vẫn xem được thông tin giỏ hàng của tài khoản đã đăng nhập trước đó
d. Kết quả mong đợi: Sau khi đăng xuất tài khoản và đăng nhập tài khoản khác sẽ không xem được thông tin giỏ hàng của tài khoản trước đó.

**Comment by 31191022164** [comment]
Cái này mình check không phải phi lỗi chức năng nha. Khi mình dùng tab ẩn danh thì nó không lưu lại -> là do browser.
