### ISSUE TITLE
[Nhóm#4] Lỗi bảo mật thông tin giỏ hàng - trang https://gearvn.com/

### ISSUE THREAD

**Issue by 31191024175** [UEHMonQAQC/BI_K45#423]
a. Web Browser: Edge version 96.0.1054.34
b. Các bước phát hiện ra lỗi:
i.#1: Check lượng truy cập của trang trang https://gearvn.com/
![ge1](https://user-images.githubusercontent.com/87383454/143378448-abe9ddec-c4ab-44c3-94ff-371398e8ccaf.jpg)
ii. #2: Truy cập vào trang web: trang https://gearvn.com/
![ge2](https://user-images.githubusercontent.com/87383454/143378474-45e2703c-e49d-4820-a515-8eda8a89bfe6.jpg)
iii. #3: Chọn đăng nhập tài khoản gmail
![gedn1](https://user-images.githubusercontent.com/87383454/143378512-3d38d2ea-2e92-4319-a8a6-cef6503f1191.jpg)
iv. #4: Chọn mua một sản phẩm bất kì
![ge3](https://user-images.githubusercontent.com/87383454/143378557-4a079640-4d3c-4dc8-94aa-b116425c3184.jpg)
v. #5: Đăng xuất tài khoản
![ge4](https://user-images.githubusercontent.com/87383454/143378636-cfdf68b7-94e3-4961-a145-b70c790a7ca4.jpg)
vi. #6: Đăng nhập tài khoản gmail khác
![gedn2](https://user-images.githubusercontent.com/87383454/143378669-e08eca43-b0e8-48fd-bc62-6f0d7fd4ed3a.jpg)
vii. #7: Sau khi đăng nhập thành công nhấp vào icon giỏ hàng
![ge5](https://user-images.githubusercontent.com/87383454/143378704-9d2e1aa7-c53e-40c9-b641-1146253bf872.jpg)
c. Kết quả thực tế: Sau khi đăng nhập bằng tài khoản khác vẫn xem được thông tin giỏ hàng của tài khoản đã đăng nhập trước đó
d. Kết quả mong đợi: Sau khi đăng xuất tài khoản và đăng nhập tài khoản khác sẽ không xem được thông tin giỏ hàng của tài khoản trước đó.

**Comment by 31191022164** [comment]
Cái này mình check không phải phi lỗi chức năng nha. Khi mình dùng tab ẩn danh thì nó không lưu lại -> là do browser.

**Comment by 31191024175** [comment]
Cái này là mình test bên Edge là nó bị, xong rồi mình test bên Chrome cũng bị , có thể là các browser khác cũng vậy. Nhưng mà các trang web điện tử khác lại không bị trên các browser khác nhau, thì mình nghĩ đây là lỗi do trang web chứ.

**Comment by 31191022164** [comment]
Như thầy vừa giải thích thì đây không phải lỗi phi chức năng, nên mình đóng nha

**Comment by 31191024175** [comment]
Oki QA
