### ISSUE TITLE
[Nhóm#9] Lỗi bảo mật tin nhắn ở chatbox - trang https://www.petsaigon.vn/

### ISSUE THREAD

**Issue by 31191025549** [UEHMonQAQC/BI_K45#425]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://www.petsaigon.vn/
ii. #2: Đăng nhập tài khoàn 1
![Đăng nhập 1](https://user-images.githubusercontent.com/92793356/143384313-dac9a70e-ed12-413a-a608-918d46e867b8.png)
iii. #3: Chọn Chatbox để gửi tin nhắn, yêu cầu bắt buộc cung cấp số điện thoại
![lại tin hắn 1](https://user-images.githubusercontent.com/92793356/143571940-ddfcb399-ad02-4181-8c53-89feebb35803.png)
iv. #4: Đăng xuất tài khoản
![lại thoát](https://user-images.githubusercontent.com/92793356/143571966-7310fbe8-3150-465e-8939-1d19969eee7a.png)
v. #5: Đăng nhập một tài khoản 2
![Đăng nhập 2](https://user-images.githubusercontent.com/92793356/143384405-76e753dc-d143-4547-8ea6-2d5693b49c79.png)
vi. #6: Kiểm tra lại Chatbox
c. Kết quả thực tế: Tin nhắn của tài khoản 1 vẫn còn, thông tin liên quan số điện thoại vẫn còn, F5 nhiều lần không mất, cũng không có nút xóa tin nhắn
![lại tn 2](https://user-images.githubusercontent.com/92793356/143571993-a1beda00-d426-4ec1-b2cc-1a6278686cb9.png)
d. Kết quả mong đợi: Tin nhắn được gửi ở tài khoản 1, tài khoản 2 sẽ không nhìn thấy được
e. Lưu lượng truy cập trang https://www.petsaigon.vn/
![Screenshot (167)](https://user-images.githubusercontent.com/92793356/143384255-2ec50cca-c5e8-4c7d-9c8c-014ce9782d50.png)

**Comment by 31191025549** [comment]
Mình xin phép chỉnh sửa bước #3 với #4 nha QA

**Comment by 31191025698** [comment]
Okee nha

**Comment by 31191025698** [comment]
Giống lỗi giỏ hàng #420.
