### ISSUE TITLE
[Nhóm#9] Màu chữ không đồng nhất - trang https://vieclam.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191025549** [UEHMonQAQC/BI_K45#426]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://vieclam.ueh.edu.vn/
ii. #2: Chọn " Việc làm".
![Công việc](https://user-images.githubusercontent.com/92793356/143385263-938d2290-d93e-4969-b6a6-6eb23089467e.png)
iii. #3: Chọn công việc.
![viec](https://user-images.githubusercontent.com/92793356/143385288-d6d33aaa-6dab-40c9-a88b-97c13c975f25.png)
iv. #4: Kéo đến mục " thông tin liên hệ".
![Màu  k giống](https://user-images.githubusercontent.com/92793356/143385333-900268d8-da9d-4d2f-adff-e7082f7af158.png)
c. Kết quả thực tế: 2 mục "Thông tin liên hệ" và "Phúc lợi"  giống nhau, nhưng lại khác về màu sắc
![257592012_619482029084018_2560130817949924751_n](https://user-images.githubusercontent.com/92793356/143528483-bfd5799f-1b98-4222-bd89-0605a575b5aa.png)
![260263241_4975231305823447_2484272770124254623_n](https://user-images.githubusercontent.com/92793356/143528487-397d897e-5a6c-4dec-9f8a-4936a323bf27.png)
d. Kết quả mong đợi: Màu sắc giống nhau.

**Comment by 31191025549** [comment]
Mình xin phép chỉnh sửa ở bước kết quả thực tế nha QA, QA xem xét lại lỗi giúp mình

**Comment by 31191025698** [comment]
Nó khác vì phần miêu tả và phần phúc lợi nằm ở 2 thẻ div khác nhau, 2 thẻ div này có style khác nhau.

**Comment by 31191025549** [comment]
Mình xem lại thì không phải lỗi, cám ơn QA
