### ISSUE TITLE
[Nhóm#9] Có thể tải phim khi web không cho download - Trang https://haophim.com/

### ISSUE THREAD

**Issue by 31191026463** [UEHMonQAQC/BI_K45#432]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Kiểm tra lượng truy cập trang: https://haophim.com/ và kết quả lượng truy cập trên 300/tháng
![image](https://user-images.githubusercontent.com/92785792/143426935-017a8480-0ac3-4608-b72c-857d98c08e54.png)
ii. #2: Truy cập trang https://haophim.com/
iii. #3: Tại mục PHIM NỔI BẬT chọn 1 phim bất kì 
![image](https://user-images.githubusercontent.com/92785792/143434770-f28a0c70-19c3-44ad-bfd0-cc8a734d8ac8.png)
iv. #4: Kéo xuống chọn 1 tập bất kì
![image](https://user-images.githubusercontent.com/92785792/143434829-d995f197-b9ce-4395-99c3-2b76c7614d37.png)
v. #5: Chờ 5s sau đó chọn bỏ qua quảng cáo
![image](https://user-images.githubusercontent.com/92785792/143434883-cde96d9c-9e7d-4696-8b13-6c3d33571edc.png)
vi. #6: Bấm dừng video
![image](https://user-images.githubusercontent.com/92785792/143434941-2ab9e19f-7488-4311-b74c-9e7110caebdc.png) 
vii. #7: Click chuột phải sau đó chọn kiểm tra hoặc bấm F12
![image](https://user-images.githubusercontent.com/92785792/143435021-496f68a7-73ce-4d22-9653-4cba820f5a5d.png)
viii. #8: Trong DevTools bấm chọn Network
![image](https://user-images.githubusercontent.com/92785792/143435124-a91ff938-f8ff-4273-a257-cf19674498a9.png)
ix. #9: Tiếp tục chọn media và bấm chạy phim
![image](https://user-images.githubusercontent.com/92785792/143435271-099875f6-cd04-4c25-a8b0-412f7d17e656.png)
x. #10: Quan sát thấy xuất hiện name như hình, click chuột phải "Open in new tab" 
![image](https://user-images.githubusercontent.com/92785792/143435473-ab205674-8e7d-4104-a47a-d9faf80cad31.png)
xi. #11: Click chọn chức năng mở rộng ở góc phải video sau đó click chọn tải xuống
![image](https://user-images.githubusercontent.com/92785792/143435794-58ef45ce-93ff-43c2-b603-a2a0fc3a9de3.png)
![image](https://user-images.githubusercontent.com/92785792/143435915-1ca99486-07de-416a-ac0e-b676256b1fe5.png)
c. Kết quả thực tế: Có thể tải phim khi web không cho download.
d. Kết quả mong đợi: Không thể tải được phim.

**Comment by 31191026463** [comment]
Mình xin phép sửa lỗi #1 vs Title nha QA

**Comment by 31191025698** [comment]
Như thầy đã đề cập buổi 7.
