### ISSUE TITLE
[Nhóm#9] Lỗi bảo mật hình ảnh - Trang https://www.flickr.com/

### ISSUE THREAD

**Issue by 31191026463** [UEHMonQAQC/BI_K45#435]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Kiểm tra lượng truy cập trang: https://www.flickr.com/ và kết quả lượng truy cập trên 300/tháng
![image](https://user-images.githubusercontent.com/92785792/143448153-b6bf1dd9-c9ca-4eae-abbc-8b210746fdc9.png)
ii. #2: Truy cập trang: https://www.flickr.com/ 
iii. #3: Nhập thanh tìm kiếm với nội dung "Roberto Bertero" và chọn "Search people"
![image](https://user-images.githubusercontent.com/92785792/143452828-4ea12f67-7623-42c8-8f83-cfb89d92bdf5.png)
iv. #4: Click chọn members Roberto Bertero
![image](https://user-images.githubusercontent.com/92785792/143452978-6c5dc399-4653-4114-8f6b-eaf7056b4a3f.png)
v. #5: Chọn 1 ảnh
![image](https://user-images.githubusercontent.com/92785792/143453566-a7def1fa-671c-4107-aa93-87c62f3c24c9.png)
vi. #6: Kéo xuống chọn biểu tượng download ở góc phải của ảnh sau đó chọn "View all sizes"
![image](https://user-images.githubusercontent.com/92785792/143453748-4adf1039-2efe-41f1-84ab-675e5e9dca31.png)
vii. #7: Quan sát thấy người dùng đã tắt tính năng tải ảnh của họ
![image](https://user-images.githubusercontent.com/92785792/143454257-a4507ed2-0e71-48fc-aef5-ca73cdaf26e9.png)
viii. #8: Click chuột phải chọn kiểm tra
![image](https://user-images.githubusercontent.com/92785792/143454409-c6af420c-75ee-4dd1-988e-718684ea970b.png)
ix. #9: Chọn biểu tượng con trỏ chuột sau đó click vào ảnh
![image](https://user-images.githubusercontent.com/92785792/143454744-8861b8f8-1c09-43aa-a367-ed9f0f13c775.png)
x. #10: Rê con trỏ chuột đến đường link của ảnh sau đó click đường link
![image](https://user-images.githubusercontent.com/92785792/143454929-eedfb363-646c-4ec4-b3db-6df76d905173.png)
xi. #11: Click chuột phải sau đó chọn lưu hình ảnh để tải về
![image](https://user-images.githubusercontent.com/92785792/143455105-875b8669-3518-4cfd-9423-f86235d7818c.png)
c. Kết quả thực tế: Có thể tải hình ảnh khi người dùng đã tắt tính năng tải ảnh của họ.
d. Kết quả mong đợi: Không thể tải hình ảnh.

**Comment by 31191026463** [comment]
Mình xin phép sửa lại bước 11 nha QA

**Comment by 31191025698** [comment]
> 

Okee nha 💯 👍

**Comment by 31191025698** [comment]
Như thầy đã đề cập buổi 7.
