### ISSUE TITLE
[Nhóm#4] Lỗi XSS tại thanh tìm kiếm - trang https://www.pinky.vn/

### ISSUE THREAD

**Issue by 31191026606** [UEHMonQAQC/BI_K45#436]
a. Web Browser: Google Chrome: Phiên bản 95.0.4638.69 (Phiên bản Chính thức) (64 bit)                      
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://www.pinky.vn/
![Pin1](https://user-images.githubusercontent.com/92720997/143455896-9d1d0bd3-57f5-4c37-a7e4-2b5526f6b943.JPG)
ii. #2: Nhập dòng lệnh "<script>alert('Lỗi nha')</script>" và nhấn Enter
![Pin2](https://user-images.githubusercontent.com/92720997/143456348-827fa854-9fbb-4cc4-a3c8-f806f4e9fa29.JPG)
iii. #3: Xem kết quả.
![Pin3](https://user-images.githubusercontent.com/92720997/143456680-2e7c4590-4b3c-446c-b407-e40374f81714.JPG)
Ảnh lưu lượng truy cập của trang pinky:
![Pin4](https://user-images.githubusercontent.com/92720997/143456713-0daa618f-bf9c-4ee2-9eb8-0c25301a49d6.JPG)
c.Kết quả thực tế: Hệ thống nảy thông báo, đoạn script được thực thi
d.Kết quả mong đợi: Đoạn script không nảy thông báo.

**Comment by 31191022164** [comment]
Thầy có nhận xét về lỗi này của nhóm là không phải lỗi phi chức năng nha.
