### ISSUE TITLE
[Nhóm#4] Lỗi không điền được nội dung vào textbox Email trong phần Cập nhật thông tin cá nhân - trang https://www.tienganh123.com/

### ISSUE THREAD

**Issue by 31191024968** [UEHMonQAQC/BI_K45#441]
a. Web Browser: Google Chrome: Phiên bản 95.0.4638.69 (Phiên bản Chính thức) (64 bit)
b. Các bước để phát hiện lỗi:
i. #1: Đăng nhập vào trang https://www.tienganh123.com/ và chọn Quản trị thông tin cá nhân
<img width="960" alt="SDT 1" src="https://user-images.githubusercontent.com/92668481/143460773-78f9ae51-25ae-47a7-8803-834b5f1d3df0.png">
ii. #2: Ở phần chỉnh sửa Thông tin cá nhân, điền nội dung vào ô Email
<img width="960" alt="email" src="https://user-images.githubusercontent.com/92668481/143461622-6da5da6d-afef-43d0-8014-4912bdbd59bc.png">

c. Kết quả thực tế: Không điền được nội dung vào ô email
d. Kết quả mong đợi: Điền được nội dung vào ô email

**Comment by 31191022164** [comment]
Hi nhóm. Cái này là do người ta disable không cho chỉnh chứ không phải lỗi nhé. Nhóm kiểm tra lại giúp mình nha. Nếu có vấn đề gì thì nhóm phản hồi trước 17h00 ngày 26/11 giúp mình nha. Sau thời gian này mình sẽ Close nha. @31191024968
