### ISSUE TITLE
[Nhóm#10] Lỗi tấn công XSS tại ô đánh giá sản phẩm - Trang https://nongsanbanbuon.com

### ISSUE THREAD

**Issue by 31191026529** [UEHMonQAQC/BI_K45#446]
a.Web Browser: Opera GX version 80.0.4170.86
b. Các bước phát hiện ra lỗi:
i. #1 Truy cập vào trang web https://nongsanbanbuon.com và đăng nhập
![image](https://user-images.githubusercontent.com/83526024/143466311-8e56955f-80d8-49c1-9594-2c121d80bf73.png)
ii. #2 Truy cập vào sản phẩm bất kỳ
![image](https://user-images.githubusercontent.com/83526024/143466377-ac3d386e-5ad4-4d48-8d16-25ae72a92c3f.png)
iii. #3 Kéo xuống đánh giá sản phẩm và điền  (<script>alert('Anuteeeeee')</script>) 
![image](https://user-images.githubusercontent.com/83526024/143466547-c8820fc5-bb9c-4da2-a8b0-17b11f0161e4.png)
c. Kết quả thực tế: Thực hiên  (<script>alert('Anuteeeeee')</script>) 
![image](https://user-images.githubusercontent.com/83526024/143466743-50349789-c347-4d8d-beeb-572bbead6c86.png)
d. Kết quả mong đợi: Không thực hiện được  (<script>alert('Anuteeeeee')</script>)

**Comment by 31191025698** [comment]
Nhóm bổ sung ảnh kiểm tra lượng truy cập giúp mình.

**Comment by 31191025698** [comment]
Nhóm bổ sung ảnh kiểm tra lượng truy cập giúp mình. @31191026529
