### ISSUE TITLE
[Nhóm#10] Lỗi tấn công XSS tại ô tìm kiếm - Trang https://websach.vn/

### ISSUE THREAD

**Issue by 31191026529** [UEHMonQAQC/BI_K45#448]
a.Web Browser: Opera GX version 80.0.4170.86
b. Các bước phát hiện ra lỗi:
i. #1 Truy cập vào trang web https://websach.vn/ 
![image](https://user-images.githubusercontent.com/83526024/143475341-3c912010-1758-4a22-88dd-4aec7117e9ff.png)
ii. #2 Tại mục tìm kiếm nhập <script>alert('Xin chào QA')</script>
![image](https://user-images.githubusercontent.com/83526024/143475479-8d8ce860-ffb8-4c80-b3df-33136da9227c.png)
c. Kết quả thực tế: Thực hiên <script>alert('Xin chào QA')</script>
![image](https://user-images.githubusercontent.com/83526024/143475550-9141d073-da0c-43d3-9353-957a36fbb90a.png)
https://websach.vn/tim-kiem?search_key=%3Cscript%3Ealert%28%27Xin%20ch%C3%A0o%20QA%27%29%3C%2Fscript%3E
d. Kết quả mong đợi: Không thực hiện được <script>alert('Xin chào QA')</script>
Lượng truy cập: 
![image](https://user-images.githubusercontent.com/83526024/143532741-85dc8132-fc18-43b4-9bca-a23c6422c9ef.png)

**Comment by 31191025698** [comment]
Nhóm bổ sung ảnh kiểm tra lượng truy cập giúp mình.

**Comment by 31191026529** [comment]
Nhóm mình bổ sung rồi QA kiểm tra giúp nhóm nha
