### ISSUE TITLE
[Nhóm#10] Lỗi bảo mật cho phép tải hình ảnh không tải được - Trang https://dsa.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191023135** [UEHMonQAQC/BI_K45#451]
a.Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1 Truy cập vào trang web https://dsa.ueh.edu.vn/
ii. #2 Chuột phải, không thể copy hình ảnh hay lưu hình ảnh
![image](https://user-images.githubusercontent.com/92784013/143481335-19778340-9e5c-47e2-8566-4e04ab22810b.png)
iii. #3 Chuột phải -> Inspect -> Application, Chọn image
![image](https://user-images.githubusercontent.com/92784013/143481487-809e44cb-95e0-421d-abff-028b93bbe70d.png)
iv. #4 Chuột phải -> Mở hình qua trang mới hoặc lưu hình ảnh
![image](https://user-images.githubusercontent.com/92784013/143481566-0f2d0705-cacd-4e8b-a9e6-a213e0339cc5.png)
c. Kết quả thực tế: Lưu và sao chép được hình không cho tải và copy
![image](https://user-images.githubusercontent.com/92784013/143481635-68681995-5b83-42d7-aab8-8e7d318c3805.png)
d. Kết quả mong đợi: Không cho lưu hoặc copy hình ảnh không cho copy

**Comment by 31191025698** [comment]
Như thầy đã đề cập buổi 7.
