### ISSUE TITLE
[Nhóm#8] Lỗi XSS tại thanh Tìm kiếm - trang https://www.haitien.com.vn/

### ISSUE THREAD

**Issue by 31191025019** [UEHMonQAQC/BI_K45#452]
a.  Web browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi
i. #1: Truy cập vào trang https://www.haitien.com.vn/ 
![image](https://user-images.githubusercontent.com/92733467/143481631-8689ac46-5881-4c2e-9d04-4eb1e479f8d7.png)

ii. #2: Nhập vào thanh tìm kiếm đoạn mã "<script> alert ('XSS error') </script>", sau đó tìm kiếm: 
![image](https://user-images.githubusercontent.com/92733467/143481353-06a92cab-f54b-4cf1-a29a-bda271b1ae98.png)

iii. #3: Xem kết quả hiển thị: Ảnh lượng truy cập trang https://www.haitien.com.vn/ : 

![image](https://user-images.githubusercontent.com/92733467/143481452-00438995-a7c9-471a-acde-d03f4dcd2705.png)
Ảnh lượng truy cập trang
![image](https://user-images.githubusercontent.com/92733467/143481537-edcbae1b-2b4d-4158-b85d-0e0e424e6d4f.png)

c. Kết quả thực tế: Đoạn mã được thực thi 
d. Kết quả được mong đợi: Đoạn mã không được thực thi

**Comment by hieeusnguyeenx** [comment]
@31191025019 Bạn chỉnh lại format như Thầy nhé và chỉnh lại tên title cụ thể là "Nhóm#8". Cảm ơn.

**Comment by 31191025019** [comment]
@31191026446 Đã sửa format, bạn xem lại giúp mình. Cảm ơn bạn nhiều nha!!!!
