### ISSUE TITLE
[Nhóm 7] Lỗi bảo mật cho phép sao chép tài liệu có trả phí, không cho sao chép - Trang https://123docz.net

### ISSUE THREAD

**Issue by 31191025157** [UEHMonQAQC/BI_K45#453]
a.Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1 Truy cập vào trang web https://123docz.net
ii. #2 Bấm chọn bất kỳ tài liệu phải trả phí để tải về
![image](https://user-images.githubusercontent.com/92876716/143489274-00717fc6-8422-4566-bfc3-5a394506ddf7.png)
iii. #3 Nhấn chuột phải chọn Save As và chọn Webpage,Complete —> Save
![image](https://user-images.githubusercontent.com/92876716/143489436-b0d3961a-cf87-4fcf-9d17-b1cfab5718d4.png)
iv. #4 Ở file đã lưu bằng notepad hoặc trình sạn thảo HTML nhé. Sau đó ấn Crtl + F và tìm kiếm từ khóa “false”
v. #5 Tìm đến dòng **div id="container" oncopy="return false" oncut="return false" onselectstart="return false"**
và đổi thành dòng  **div id="container" oncopy="return true" oncut="return true" onselectstart="return true"**
![image](https://user-images.githubusercontent.com/92876716/143489781-9ffb0842-a1c9-481e-b573-00c43c1de4a8.png)
vi. #6 Lưu file lại và mở file 
![image](https://user-images.githubusercontent.com/92876716/143489878-20f250a1-8948-4d13-b0de-7515df76c369.png)
Ảnh lưu lượng của trang https://123docz.net
![image](https://user-images.githubusercontent.com/92876716/143490238-5f0280b4-7cff-4b3c-a6b5-f577471029fa.png)

c. Kết quả thực tế: Có thể copy được tài liệu trả phí, không cho phép copy mà không cần trả phí
d. Kết quả mong đợi: Không thể copy được tài liệu trả phí khi không trả phí.

**Comment by 31191026515** [comment]
Mình closed vì trùng với lỗi nhóm 9 đã post nha.
