### ISSUE TITLE
[Nhóm#9] Lỗi bảo mật hình ảnh - Trang https://vieclam.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191026463** [UEHMonQAQC/BI_K45#456]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập trang: https://vieclam.ueh.edu.vn/ sau đó click chuột phải vào slideshow, quan sát thấy trang đã chặn tải
![image](https://user-images.githubusercontent.com/92785792/143520008-32264a30-b9ca-4192-be47-1c896cb41ed5.png)
ii. #2: Chọn kiểm tra, sau đó chọn Application
![image](https://user-images.githubusercontent.com/92785792/143520067-78c20b5a-4245-465e-a58e-01d6f7670341.png)
![image](https://user-images.githubusercontent.com/92785792/143520127-2cf9950a-7cae-4b9d-90bf-698d32c6c30f.png)
iii. #3: Tiếp tục chọn Top --> Images
![image](https://user-images.githubusercontent.com/92785792/143520221-cb134fb9-bca0-4128-8276-be76f4de3272.png)
![image](https://user-images.githubusercontent.com/92785792/143520252-7fbb2322-b7f1-47be-9d66-4cd04413eec5.png)
iv. #4: Kéo xuống đến ảnh slider1-min.jpg sau đó click chuột phải vào ảnh chọn Save image để tải ảnh về 
![image](https://user-images.githubusercontent.com/92785792/143520601-aba81a60-f995-427f-9f20-618b92ad5501.png)
c. Kết quả thực tế: Có thể tải ảnh slideshow khi người dùng đã chặn tính năng này.
d. Kết quả mong đợi: Không thể tải được ảnh khi người dùng đã chặn tính năng.

**Comment by 31191025698** [comment]
Như thầy đã đề cập buổi 7.
