### ISSUE TITLE
[Nhóm#6] Lỗi bảo mật cho phép tải xuống bài nhạc khi web không cho tải xuống - trang https://nhac.vn/

### ISSUE THREAD

**Issue by 31191024890** [UEHMonQAQC/BI_K45#457]
a. Web browsers: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang https://nhac.vn/
<img width="960" alt="nhac0" src="https://user-images.githubusercontent.com/85693426/143524395-1c969a2b-4e24-48da-914f-37c06576d6cb.png">
ii. #2: Di chuyển chuột vào Chủ đề và chọn Chill out
<img width="960" alt="nhac2" src="https://user-images.githubusercontent.com/85693426/143524453-d6c4ac45-2edb-443a-839f-b37e50acd961.png">
iii. #3: Bấm vào nút 3 chấm góc phải màn hình
<img width="960" alt="nhac3" src="https://user-images.githubusercontent.com/85693426/143524528-c4379a5f-272c-481a-bbdf-a6f666a58ae5.png">
iv. #4: Di chuyển chuột đến More tools và sau đó chọn Developer tools
<img width="960" alt="nhac4" src="https://user-images.githubusercontent.com/85693426/143524602-94c853ea-7774-4563-a3be-7f66565cdfec.png">
v. #5: Chọn Network và sau đó chọn Media 
<img width="960" alt="nhac5" src="https://user-images.githubusercontent.com/85693426/143524708-cbe17f49-a4d8-4877-b027-615b7ed3d113.png">
vi. #6: Click chuột phải vào vùng khoanh đỏ và chọn Open in new tab
<img width="960" alt="nhac6" src="https://user-images.githubusercontent.com/85693426/143524963-e1f000cd-b07f-4f20-a4c2-43eeebdf3001.png">
vii. #7: Kết quả:
<img width="960" alt="nhac7" src="https://user-images.githubusercontent.com/85693426/143525011-4dc42980-94f8-4738-9db8-3e7b127c898b.png">
Ảnh lượng truy cập 
<img width="960" alt="nhac" src="https://user-images.githubusercontent.com/85693426/143525374-1172a587-aa8e-4327-b687-f77f5eb37d46.png">
c. Kết quả thực tế: Có thể tải được bài nhạc khi web không cho tải về
d. Kết quả mong đợi: Không thể tải được bài nhạc khi web không cho tải về

**Comment by 31191024332** [comment]
Ở buổi học thứ 7 thầy không đồng ý lỗi PCN này nên mình xin phép gỡ label và close issue này
