### ISSUE TITLE
[Nhóm#5] Lỗi download được full bài hát khi không cần đăng nhập tài khoản - trang http://imuzik.vn/

### ISSUE THREAD

**Issue by 31191021279** [UEHMonQAQC/BI_K45#462]
a. Web Browser: Mozilla Firefox 94.0.2 (64-bit)
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web: http://imuzik.vn/
![ảnh](https://user-images.githubusercontent.com/92701347/143605042-4c74c43d-03dc-4d4b-b88c-a45d68e62685.png)
ii. #2: Chọn bài hát như hình:
![buayeu](https://user-images.githubusercontent.com/92701347/143605163-aac1c055-cac8-46d2-89c3-62a234342072.png)
iii. #3: Paused bài hát (không có nút Download full bài)
![ảnh](https://user-images.githubusercontent.com/92701347/143605261-d9768332-c285-4557-bc27-05163f881dcb.png)
![pau](https://user-images.githubusercontent.com/92701347/143605385-7701704a-b25d-4297-8b09-23910b4b6f9a.png)
iv. #4: Click chuột phải kiểm tra thành phần -> Trình gỡ lỗi -> Ctrl F gõ "mp3" -> copy đường link 
![mp3](https://user-images.githubusercontent.com/92701347/143605579-d0fa55d6-11ef-4573-8fe4-6ef70de25441.png)
v. #5: Dán đường link vào tab mới -> tại thanh musicplayer click phải chọn "Lưu audio với(V)"
![001](https://user-images.githubusercontent.com/92701347/143605787-41fbfa5b-5d8a-4ba9-bfc8-397eb9c38bf8.png)
![ảnh](https://user-images.githubusercontent.com/92701347/143605877-cf31e932-712d-42f9-9010-0e9504e8929a.png)
![101](https://user-images.githubusercontent.com/92701347/143606031-afd83e6b-7c0c-430e-bcc3-8b3382672018.png)
c. Kết quả thực tế: Download được full bài hát khi không có cần đăng nhập
d. Kết quả mong đợi: Không download được full bài hát

**Comment by 31191024332** [comment]
Theo buổi 7 của Thầy thì đây chưa đủ để công nhận là PCN. Mình xin phép close lỗi này
