### ISSUE TITLE
[Nhóm#8] Không xem được video sau khi đăng tải - trang https://global.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191026190** [UEHMonQAQC/BI_K45#463]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi: 
i. #1: Truy cập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140551931-432799ce-f7e8-4543-856c-cdbcca12de3d.png)
ii. #2 Đăng nhập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/141406491-fe4e5cb6-fa41-4dda-a6be-56f027f377c0.png)
![image](https://user-images.githubusercontent.com/92732798/141406603-a2089bcd-4e57-45b3-a621-2bce561d7c79.png)
iii. #3 Nhấp vào tên người dùng ở góc phải, chọn hồ sơ:
![image](https://user-images.githubusercontent.com/92732798/140379432-4d11bc4a-89cf-408d-b05a-c89136faf989.png)
iv. #4 Chọn Các mục Blog:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92732798/143606393-665d9c6e-4169-4a76-8db5-7e036e5ccdce.png">
v. #5 Chọn Đưa thêm mục mới:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92732798/143606471-495892f9-2b3d-401a-8d9c-d61cda245309.png">
vi. #6: Nhập các thông tin bắt buộc khác và chọn Insert Media ở Phần nội dung của mục:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92732798/143606634-0c8a812e-72e9-4395-b37a-06a5392ed7ae.png">
vii. #7 Chọn Video, dán link vào ô và bấm Insert Media:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92732798/143606896-d554fc31-33fb-4559-ba54-114ef5308989.png">
viii. #8 Chọn Lưu những thay đổi :
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92732798/143606997-7bc2c1f2-dad0-45d4-8a3c-7f89136ee2b4.png">
ix: #9 Xem kết quả video hiển thị:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92732798/143607077-5ef23a89-4959-4069-b0b2-9bfc3bdbefe9.png">
c. Kết quả thực tế: Video không thể phát
d. Kết quả mong đợi: Có thể phát được video

**Comment by hieeusnguyeenx** [comment]
@31191026190  Chức năng này chỉ cho phép đem video lên từ repositories thôi nha, nghĩa là upload lên từ máy. Khi bạn upload video lên thì sẽ lưu vào server và dẫn tới đường link của video. Do bạn đưa 1 đường link khác nên server không tìm thấy dữ liệu để show video nên dẫn đến là nó sẽ bị như hình bạn đã nêu. Bạn xem lại giúp mình nha
![image](https://user-images.githubusercontent.com/87801356/143613283-c34c1635-53ec-45a1-aeae-c42be52b0b31.png)
![image](https://user-images.githubusercontent.com/87801356/143613626-08af3eeb-661e-4a31-8c93-a94cf2eb725a.png)
