### ISSUE TITLE
[Nhóm#7] Các button không bằng nhau - trang https://www.cgv.vn/

### ISSUE THREAD

**Issue by 31191024776** [UEHMonQAQC/BI_K45#47]
a. Web Browser: Microsoft Edge 95.0.1020.40
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang chủ CGV Việt Nam
 
![1](https://user-images.githubusercontent.com/92839124/140102148-6f4be284-fc07-408c-9b62-7db0e4f421d1.JPG)

i. #2: Truy cập vào trang Quầy Online ở phần CULTUREPLEX
![2](https://user-images.githubusercontent.com/92839124/140102268-bb92b4f6-ec80-4acc-8848-69bb60ea5229.JPG)

iii. #3: Chọn voucher hoặc quà tặng bất kỳ, hệ thống sẽ hiển thị thông tin của voucher đó
![3](https://user-images.githubusercontent.com/92839124/140102411-22e60d87-104f-458b-b647-353bb6b6d9d8.JPG)

vi. #4: Chọn nút MUA HOẶC TẶNG QUÀ, hệ thống sẽ qua trang Thanh toán
![4](https://user-images.githubusercontent.com/92839124/140102638-8fa5c0f1-9221-4538-80ab-6cc8e8803fa4.JPG)

v. #5: Người dùng chọn vào nút tick xanh, hệ thống sẽ xuất hiện bảng pop-up
![5_LI](https://user-images.githubusercontent.com/92839124/140103143-1958cc34-753f-4a41-91e5-d9a34ba9e316.jpg)

c. Kết quả thực tế: Button KHÔNG và Button CÓ có kích thước ô không bằng nhau, 
d. Kết quả mong đợi: Button KHÔNG và Button CÓ có kích thước ô bằng nhau,

**Comment by 31191026515** [comment]
Mình không ghi nhận lỗi này vì kích thước của button này dựa vào độ dài của chữ, đây là chủ ý của người thiết kế web.
