### ISSUE TITLE
[Nhóm#8] Lỗi bảo mật Coppy - Trang https://123docz.net/trang-chu.htm

### ISSUE THREAD

**Issue by 31181023259** [UEHMonQAQC/BI_K45#471]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://123docz.net/trang-chu.htm và chọn tập tài liệu cần coppy
![image](https://user-images.githubusercontent.com/92772571/143988185-d4860028-a33b-4483-b46d-76c770e2b6cb.png)
ii. #2 Thêm từ “text”  vào ngay sau phần “.123docz” trên đường link của bài viết đó.
![image](https://user-images.githubusercontent.com/92772571/143988353-47681f0f-eb09-4e39-8e4b-d73a7b2accad.png)
iii. #3 Nhấn chuột phải vào bài viết rồi chọn Lưu thành và nhấn chọn Save
![image](https://user-images.githubusercontent.com/92772571/143988503-c4452a9d-9cc6-491d-bdad-788ac12c696d.png)
![image](https://user-images.githubusercontent.com/92772571/143988620-2fc53962-173b-4370-b475-ddc9af45be84.png)
iv. #4 Nhấp chuột phải vào file vừa lưu nhấn chọn Open with rồi nhấn chọn Choose another app và chọn tiếp Notpade
![image](https://user-images.githubusercontent.com/92772571/143988861-b4eb7ccb-6eed-4a7d-b558-47ab048f9622.png)
v. #5 Mở lên bằng notepad và tìm đến thẻ <body> và xóa hết dòng: oncopy=”return false” oncut=”return false” onpaste=”return false” onselectstart=”return false” style=”
![image](https://user-images.githubusercontent.com/92772571/143989014-8d9c490a-d4a2-4f8b-865c-21e66f02cccf.png)
vi. #6 Sau khi xóa xong đoạn mã trên các bạn nhấn Ctrl + S để lưu lại.
![image](https://user-images.githubusercontent.com/92772571/143989113-d652da93-3554-4f94-a354-3600ddf140ca.png)
c. Kết quả thực tế: Mở file vừa lưu lên và có thể coppy được
![image](https://user-images.githubusercontent.com/92772571/143989258-6515e789-6353-43b6-b2be-f4b50e6a2686.png)
d. Kết quả mong đợi: Không coppy được

**Comment by hieeusnguyeenx** [comment]
@31181023259 Nếu bạn tải được file mà không tốn phí thì mình sẽ chấp nhận lỗi nhé. Issue này tương tự như issue #387 và đã có đề cập đến với Thầy ở buổi học trước vào lúc 2:16:34. Bạn vui lòng xem lại nhé. Cảm ơn !

**Comment by 31181023259** [comment]
> @31181023259 Nếu bạn tải được file mà không tốn phí thì mình sẽ chấp nhận lỗi nhé. Issue này tương tự như issue #387 và đã có đề cập đến với Thầy ở buổi học trước vào lúc 2:16:34. Bạn vui lòng xem lại nhé. Cảm ơn !

mình có xem lại record rồi ha, thầy có nói là nếu nó lấy hết nội dung thì vẫn tính á.
Còn phần của mình thì trang web này không cho xem hết nội dung và không cho coppy thì mình đã vượt cái bảo mật của nó rồi ( Nếu mà bình thường có thể xem hết được nội dung và có thể coppy được thì mình chấp nhận đây không phải lỗi )
Bạn xem lại giúp mình nha, mình cảm ơn

**Comment by hieeusnguyeenx** [comment]
Ok, vậy hiện tại mình thấy rằng các bước trên chưa lấy hết được nội dung. Nếu bạn chứng minh được vấn đề này thì mình sẽ accept lỗi nhé. Cảm ơn !

**Comment by 31181023259** [comment]
> Ok, vậy hiện tại mình thấy rằng các bước trên chưa lấy hết được nội dung. Nếu bạn chứng minh được vấn đề này thì mình sẽ accept lỗi nhé. Cảm ơn !

cái bước thêm text là đã lấy hết nội dung nha

**Comment by hieeusnguyeenx** [comment]
Mình có thử nhưng mà chưa được á, bạn có thể bổ sung video để minh xem xét nha. Video nhớ là bao gồm mục lục và trang cuối nhé. 
![image](https://user-images.githubusercontent.com/87801356/144042032-703ca188-46f1-439c-ab9e-8c03af93f81f.png)
![image](https://user-images.githubusercontent.com/87801356/144042161-cda68252-941a-4a5e-a8f7-d46c64bc0566.png)

**Comment by hieeusnguyeenx** [comment]
À còn nữa, mấy trang web bên ngoài bạn nhớ bổ sung thêm số lượng người truy cập trang/tháng nhé. Việc đo cái này thầy có đề cập trên file báo cáo. Mình cảm ơn!
