### ISSUE TITLE
[Nhóm#8] Tải tài liệu không cần đăng nhập tài khoản - Trang https://www.slideshare.net/

### ISSUE THREAD

**Issue by 31181023259** [UEHMonQAQC/BI_K45#472]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://www.slideshare.net/ và chọn tài liệu muốn tải cụ thể là tài liệu: https://www.slideshare.net/LunVnDchV/v-sao-mt-mt-cmc-nhn-mnh-vai-tr-ca-ngoi-thng-i-vi-qu-trnh-ti-sn-xut-x-hi-t-bn-ch-ngha-mt-khc-li-gi-nh-khng-c-ngoi-thng-khi-nghin-cu-ti-sn-xut-t-bn-x-hi
![image](https://user-images.githubusercontent.com/92772571/143993633-82199aa0-b6c1-4664-aad6-622cf63b1b8d.png)
ii. #2 Nhấn chuột phải chọn " Kiểm tra "
![image](https://user-images.githubusercontent.com/92772571/143993708-ec1cc147-01bf-42d2-a29e-0ebc8d747fa8.png)
![image](https://user-images.githubusercontent.com/92772571/143993761-1dcba299-1093-4d5f-9324-77038421235c.png)
iii. #3 Bấm Ctrl F và nhập Embed_code
![image](https://user-images.githubusercontent.com/92772571/143993951-fb754f11-88eb-492e-88cf-64b72edb6831.png)
iv. #4 Coppy địa chỉ chứa Embed_ code cụ thể là https://www.slideshare.net/slideshow/embed_code/key/vp9GHtukjXbfeh và dán vào tab mới
![image](https://user-images.githubusercontent.com/92772571/143994110-a8824e0d-1e08-471e-8f0b-e23bf969d1bb.png)
v. #5 Bấm Ctrl P và chọn " Lưu dưới dạng PDF " sau đó chọn " Lưu "
![image](https://user-images.githubusercontent.com/92772571/143994296-5866844d-7dda-4210-8e26-7e497fd6d0e6.png)
vi. #6 Nhập tên và chỗ cần lưu sau đó nhấn Save
![image](https://user-images.githubusercontent.com/92772571/143994474-1a9dc659-41b0-4809-85cc-9ca58f1130ec.png)
c. Kết quả thực tế: Tải được tài liệu 
![image](https://user-images.githubusercontent.com/92772571/143994547-bae74576-c6c0-4633-94fd-c32c13f40adf.png)
d. Kết quả mong đợi: Không tải được tài liệu khi không có tài khoản

**Comment by hieeusnguyeenx** [comment]
@31181023259  mình vừa kiểm tra lại thì lỗi này trùng với lỗi #454 . Bạn xem lại nhé. Cảm ơn !
