### ISSUE TITLE
[Nhóm#8] Lỗi bảo mật đáp án trước khi chọn - Trang https://tracnghiem.net/

### ISSUE THREAD

**Issue by 31181023259** [UEHMonQAQC/BI_K45#475]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://tracnghiem.net/ chọn bài thi muốn thi
![image](https://user-images.githubusercontent.com/92772571/144039704-80987d53-b473-47d6-a195-76c67f902f60.png)
![image](https://user-images.githubusercontent.com/92772571/144039753-fc1376d5-a35c-456e-902b-8fcdd11e3815.png)
ii. #2 Nhấn Ctrl U sau đó nhấn Ctrl F nhập " Câu xx " với xx là câu bạn muốn tra đáp án
![image](https://user-images.githubusercontent.com/92772571/144040013-825dad4a-385a-462f-8db3-40dae3170838.png)
iii. #3 Nhấn vào link phía dưới
![image](https://user-images.githubusercontent.com/92772571/144040107-1300e1f6-fa48-4bcb-a21d-aa7bd2cb8baf.png)
![image](https://user-images.githubusercontent.com/92772571/144040131-c0b123a1-165e-40c6-be3c-fc65d5314a2c.png)
iv. #4 Nhấn Ctrl U sau đó nhấn Ctrl F nhập " answer-result " và xem đáp án ở bên dưới
![image](https://user-images.githubusercontent.com/92772571/144040816-13dafda9-a1d0-4cc1-a2a1-03c782e75957.png)
c. Kết quả thực tế: Tra được đáp án trước khi chọn đáp án 
d. Kết quả mong đơi: Không tra được đáp án trước khi chọn đáp án

**Comment by hieeusnguyeenx** [comment]
@31181023259 cái này sau khi bạn chọn thì nó vẫn show đáp án mà, có vấn đề gì bảo mật đâu.

**Comment by 31181023259** [comment]
> @31181023259 cái này sau khi bạn chọn thì nó vẫn show đáp án mà, có vấn đề gì bảo mật đâu.

Cái này là một bài thi thử vậy trong khi thi bạn xem được đáp án là không phải bảo mật hả bạn

**Comment by hieeusnguyeenx** [comment]
@31181023259 issue này mình sẽ hỏi lại với thầy nhé. Cảm ơn !

**Comment by 31181023259** [comment]
> @31181023259 issue này mình sẽ hỏi lại với thầy nhé. Cảm ơn !

ok bạn. Mình cảm ơn
