### ISSUE TITLE
[Nhóm#7] Các đoạn text không canh lề giống nhau - trang https://www.cgv.vn/

### ISSUE THREAD

**Issue by 31191024776** [UEHMonQAQC/BI_K45#48]
a. Web Browser: Microsoft Edge 95.0.1020.40
b. Các bước phát hiện ra lỗi:

i. #1: Truy cập vào trang chủ CGV Việt Nam
![1](https://user-images.githubusercontent.com/92839124/140103998-90559866-4bab-46ff-9227-5895581257ba.JPG)

ii. #2: Truy cập vào trang Quầy Online ở phần CULTUREPLEX, hệ thống hiển thị danh sách các voucher
![2](https://user-images.githubusercontent.com/92839124/140104035-f00f9827-b628-40e2-8053-2baa29b55584.JPG)

iii. #3: Chọn voucher hoặc quà tặng bất kỳ, hệ thống sẽ hiển thị thông tin của voucher đó
![GUI - Canh Lề_LI](https://user-images.githubusercontent.com/92839124/140104123-20d706be-be21-464c-8eb4-b8c867c630b5.jpg)

c. Kết quả thực tế: Đoạn text trên canh lề trái và đoạn text dưới canh lề phải
d. Kết quả mong đợi: Các đoạn text phải canh lề như nhau

**Comment by 31191026515** [comment]
Đoạn text của phần "Chi tiết" thuộc mục "Voucher 4DX", các phần khác của phần này như "giá", "hạn sử dụng" cũng căn trái, các phần của 1 mục đều đồng bộ với nhau. Đoạn text của mục "Điều kiện và điều khoản" đã thuộc mục khác, không cùng mục với "Voucher 4DX" nên mình thấy định dạng như vậy là hợp lý. QA không tính lỗi này nhé.

**Comment by 31191026515** [comment]
Các chức năng của trang CGV mà phải đăng nhập mới thực hiện được thì các bài sau nhóm thêm bước đăng nhập vào nha!
