### ISSUE TITLE
[Nhóm#5] Lỗi tấn công CSRF khi đăng nhập - trang https://nhasachlaptrinh.tk/

### ISSUE THREAD

**Issue by 31191024988** [UEHMonQAQC/BI_K45#481]
a. Web Browser: Google Chrome 96.0.4664.45
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web: https://nhasachlaptrinh.tk/
![image](https://user-images.githubusercontent.com/92745794/144072480-c969029b-cf0c-43a1-ab48-e556f07f72cd.png)
ii. #2: Click chuột phải -> Inspect -> Network 
![aa](https://user-images.githubusercontent.com/92745794/144072921-eeb12016-cfdd-4087-9ad2-d4efc588ff1b.png)
iii. #3: Sau đó đăng nhập vào trang với tài khoản và mật khẩu sai: 
![112](https://user-images.githubusercontent.com/92745794/144077287-31f73f97-6ebb-4d53-b928-7a55289abef5.png)
![113](https://user-images.githubusercontent.com/92745794/144077636-4b31cbe8-abee-45f9-9b71-8dff4b74fe71.png)
iv. #4: Đăng nhập lại với tài khoản và mật khẩu đúng 
![114](https://user-images.githubusercontent.com/92745794/144077822-b9f52fb1-5cd8-46e5-9357-29dec6d14381.png)
![115](https://user-images.githubusercontent.com/92745794/144078128-65fe5f4c-ffca-4ef6-83b6-c592f31dca11.png)
v. #5: So sánh 2 mã "csrf" của 2 phiên đăng nhập và thấy trùng nhau 
c. Kết quả thực tế: Khi đăng nhập với tài khoản mật khẩu sai có thể lấy được mã csrf của phiên đăng nhập tiếp theo
d. Kết quả mong đợi: Mã csrf của phiên đăng nhập trước đó phải khác mã csrf của phiên đăng nhập tiếp theo

**Comment by 31191024332** [comment]
Mình xin phép close lỗi này trước. Nhóm cần c/m thêm việc dùng mã csrf tiếp theo được dùng mới có thể xác nhận được
