### ISSUE TITLE
[Nhóm#4] Hệ thống lưu lại Cookie đăng nhập - trang https://student.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31191026810** [UEHMonQAQC/BI_K45#482]
a. Web Browser: Google Chrome: Phiên bản 95.0.4638.69 (Phiên bản Chính thức) (64 bit)
b. Các bước để phát hiện lỗi:
i. #1: Sử dụng Google Chrome với "Chế độ khách".
ii. #2: Truy cập vào trang https://student.ueh.edu.vn/  và chọn nút "Đăng nhập".
<img width="960" alt="Dangnhapj" src="https://user-images.githubusercontent.com/72840892/144077912-5a03f505-7694-4578-b688-e1eab27b1691.png">

iii. #3: Đăng nhập bằng Google với Email ST UEH.
<img width="960" alt="chon dang nhạp" src="https://user-images.githubusercontent.com/72840892/144078133-02c057bd-2674-4b44-9f39-3b737c46333b.png">

iv. #4: Đăng xuất tài khoản.
<img width="960" alt="Dãnguat" src="https://user-images.githubusercontent.com/72840892/144078317-5596d082-809b-40cd-93ad-578300c2112d.png">

v. #5: Chọn lại Đăng nhập bằng Google với Email ST UEH.
<img width="960" alt="chon dang nhạp" src="https://user-images.githubusercontent.com/72840892/144078400-defd128e-9418-4258-a3cf-9acc618d2b31.png">

c.Kết quả thực tế: Hệ thống tự động đăng nhập trang bằng tài khoản vừa đăng xuất.
<img width="960" alt="dangnhap2" src="https://user-images.githubusercontent.com/72840892/144078530-b8824f55-2de7-434c-b9ae-f0110b7c1f29.png">

d.Kết quả mong đợi: Hệ thống yêu cầu chọn lại Gmail muốn sử dụng để đăng nhập.
e.Kiểm tra truy cập.
![soluong](https://user-images.githubusercontent.com/72840892/144079985-0697f7ec-e61a-4133-b092-81d97821131d.png)

**Comment by 31191022164** [comment]
Lỗi bảo mật ngoài trang đã đăng ký chỉ được tính với những trang không trùng với nhóm khác nha. Nhóm xem lại trang này giúp mình, vì trang này của nhóm 2 rồi. @31191026810

**Comment by 31191022164** [comment]
Như thầy đã giải thích sáng nay thì mình sẽ đóng lại lỗi này nhé.

**Comment by 31191026810** [comment]
Mình có để đường link chứng minh lỗi này hợp lệ, Có so sánh với trang [Global](https://global.ueh.edu.vn/) (trang này không bị lỗi) để QA dễ quan sát hơn. QA xem lại giúp mình, mình cảm ơn!
 https://drive.google.com/file/d/1q_CmDKvbXvNR5mv72kEjLkjVfwLcJCNp/view?usp=sharing
