### ISSUE TITLE
[Nhóm#5] Lỗi không mã hóa mật khẩu khi đăng nhập - trang http://hoctap.dvtienich.com/

### ISSUE THREAD

**Issue by 31191025282** [UEHMonQAQC/BI_K45#483]
a. Web Browser: Google Chrome
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web: http://hoctap.dvtienich.com/
![11](https://user-images.githubusercontent.com/92708502/144267598-80337684-34ca-4955-9449-61fa2b8c6791.png)
ii. #2: Click Đăng nhập -> Sau đó thực hiện các thao tác như hình và đăng nhập vào trang
![12](https://user-images.githubusercontent.com/92708502/144268256-348e855a-0a51-47cc-9cd0-487046b988a6.png)
iii. #3: Chọn login -> Payload như hình
![14](https://user-images.githubusercontent.com/92708502/144270332-9f856096-9add-4bb2-80ef-eed6885a9f8e.png)
c. Kết quả thực tế: Mật khẩu không được mã hoá
d. Kết quả mong đợi: Mật khẩu được mã hóa
Lượng truy cập:
![15](https://user-images.githubusercontent.com/92708502/144269792-4d31644b-4fa6-4d2f-8fdd-7960d9159f00.png)

**Comment by 31191024332** [comment]
Thầy chỉ chấp nhận 1 lỗi liên quan đến không mã hóa mật khẩu (Buổi 8), mình xin phép close lỗi này
