### ISSUE TITLE
[Nhóm#7] Textbox số lượng nhưng cho nhập ký tự chữ - trang https://www.cgv.vn/

### ISSUE THREAD

**Issue by 31191024776** [UEHMonQAQC/BI_K45#49]
a. Web Browser: Microsoft Edge 95.0.1020.40
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang chủ CGV Việt Nam
![1](https://user-images.githubusercontent.com/92839124/140105006-b507a38f-1067-4081-9b84-1990607b2c49.JPG)

i. #2: Truy cập vào trang Quầy Online ở phần CULTUREPLEX
![2](https://user-images.githubusercontent.com/92839124/140105033-cd1d6d30-c936-4559-abc8-6a95934ca447.JPG)

iii. #3: Chọn voucher hoặc quà tặng bất kỳ, hệ thống sẽ hiển thị thông tin của voucher đó
![3](https://user-images.githubusercontent.com/92839124/140105070-7a93dcd4-b27c-48ea-9c57-16f3c4b4269a.JPG)

vi. #4: Chọn nút MUA HOẶC TẶNG QUÀ, hệ thống sẽ qua trang Thanh toán
![4](https://user-images.githubusercontent.com/92839124/140105125-486d64b6-6e75-4fb7-a7df-6613554ee92d.JPG)

v. #5 Nhập chữ vào textbox số lượng
![5 LỖI DATATYPE](https://user-images.githubusercontent.com/92839124/140105322-721cfd36-2c99-4bea-bd33-8e7786ef2b05.JPG)

c. Kết quả thực tế: Nhập được ký tự chữ vào textbox số lượng
d. Kết quả mong đợi: Textbox số lượng chỉ cho phép nhập ký tự số

**Comment by 31191026515** [comment]
![image](https://user-images.githubusercontent.com/92660305/140475946-6b93012e-1067-47d9-9945-9451ac63d15a.png)

Mình đã thử và khi mình nhập số và chọn "xác nhận", web mới hiển thi "đã xác nhận". Khi mình nhận chữ, web sẽ thông báo "vui lòng chọn số lượng". Nghĩa là web không cho nhập ký tự chữ hoặc vừa ký tự chữ và số. 
Lỗi này QA không chấp nhận nhé
