### ISSUE TITLE
[Nhóm#5] Lỗi tấn công CSRF khi đăng nhập - trang https://banlinhkien.com/

### ISSUE THREAD

**Issue by 31191025282** [UEHMonQAQC/BI_K45#492]
a. Web Browser: Microsoft Edge 
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web: https://banlinhkien.com/
![B1](https://user-images.githubusercontent.com/92708502/144160893-81e6b270-5302-4200-bcca-08c3f92a82c1.png)
ii. #2: Click chuột phải -> Inspect -> Network
![B2](https://user-images.githubusercontent.com/92708502/144160954-0c782fc0-613f-40d0-bf63-0979e1783704.png)
iii. #3: Sau đó đăng nhập vào trang với tài khoản và mật khẩu sai:
![B3 1](https://user-images.githubusercontent.com/92708502/144169726-1d9f1735-0e38-4c74-b44f-415ccce022b4.png)
![B3 2](https://user-images.githubusercontent.com/92708502/144169856-e624dc7e-2efe-47a5-a9c5-79c35a769224.png)
iv. #4: Đăng nhập lại với tài khoản và mật khẩu đúng
![B4 1](https://user-images.githubusercontent.com/92708502/144169991-311fb583-ff61-46e6-be62-6258d7631dd6.png)
v. #5: So sánh 2 mã "csrf" của 2 phiên đăng nhập và thấy trùng nhau
c. Kết quả thực tế: Khi đăng nhập với tài khoản mật khẩu sai có thể lấy được mã csrf của phiên đăng nhập tiếp theo
d. Kết quả mong đợi: Mã csrf của phiên đăng nhập trước đó phải khác mã csrf của phiên đăng nhập tiếp theo
Lượt truy cập:
![B_END](https://user-images.githubusercontent.com/92708502/144161900-de7ce540-7af4-4a8b-8d40-7b164be41a18.png)

**Comment by 31191024332** [comment]
Tương tự #481
