### ISSUE TITLE
[Nhóm 7] Lỗi bảo mật cho phép tải tài liệu không cho phép tải, yêu cầu đăng nhập - Trang https://issuu.com

### ISSUE THREAD

**Issue by 31191025157** [UEHMonQAQC/BI_K45#493]
[](url)a.Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1 Truy cập vào trang web https://issuu.com
ii. #2 Bấm chọn bất kỳ tài liệu không cho phép download
Ví dụ: https://issuu.com/242805/docs/katalog_black_friday_1_
![image](https://user-images.githubusercontent.com/92876716/144165074-d19fb26c-1c72-406d-b79a-95c5afcf75a6.png)
iii. #3 Mở file issuu.py bằng python 3.8
Lưu ý: Cần có thư viện urllib, Beautiful Soup, và wget
`pip install urllib3 beautifulsoup4 wget`

Code Python issuu.py:
[py-issuu-scrape-master.zip](https://github.com/UEHMonQAQC/BI_K45/files/7630502/py-issuu-scrape-master.zip)
![image](https://user-images.githubusercontent.com/92876716/144165599-2911feaf-32a6-4f9f-816f-6a0648cf2d12.png)
iv. #4 Nhập url của tài liệu cần tải và nhập số trang 
![image](https://user-images.githubusercontent.com/92876716/144165697-c999d83c-7eb1-49b9-a244-6863d5f419d7.png)

![image](https://user-images.githubusercontent.com/92876716/144165841-7a13fc39-08b3-4304-84fa-5f88f65b3771.png)
v. #5 Mở tài liệu được tải về ở folder file py-issuu
![image](https://user-images.githubusercontent.com/92876716/144166141-f581f497-80ba-4dee-a525-3784e4a5d2fe.png)
Lưu lượng truy cập web Issuu.com
![image](https://user-images.githubusercontent.com/92876716/144166851-c72caf48-f18e-4724-a14a-7885457a19d8.png)

c. Kết quả thực tế: Có thể tải được tài liệu không cho phép tải
d. Kết quả mong đợi: Không tải được tài liệu không cho phép tải

**Comment by 31191026515** [comment]
Mình không xác nhận lỗi này nhé. Lý do mình nói trong video này: https://drive.google.com/file/d/19bKIeZtoTDUfegeHoxh4RlAsojO5RVvW/view?usp=sharing
