### ISSUE TITLE
[Nhóm#3] Hệ thống lưu lại Cookie đăng nhập - trang https://lms.ueh.edu.vn/

### ISSUE THREAD

**Issue by ddongvi** [UEHMonQAQC/BI_K45#502]
a. Web Browser: Google Chrome: Phiên bản 95.0.4638.69 (Phiên bản Chính thức) (64 bit)
b. Các bước để phát hiện lỗi:
i. #1: Chọn chế độ  ẩn danh của trình duyệt và truy cập web https://lms.ueh.edu.vn/
ii. #2: Chọn đăng nhập bằng google
iii. #3: Sau khi đăng nhập thành công và nhấn đăng xuất
iv. #4: Tiếp tục đăng nhập lại với google.
v. #5: Xem kết quả
https://drive.google.com/file/d/1gbX-HOZalA9RXs-jbfAmwqENofUD0YnW/view?usp=sharing
c.Kết quả thực tế: Hệ thống tự động đăng nhập trang bằng tài khoản vừa đăng xuất mà không hỏi đăng nhập lại.
d.Kết quả mong đợi: Hệ thống yêu cầu chọn lại Gmail muốn sử dụng để đăng nhập.

**Comment by ddongvi** [comment]
Link video test: https://drive.google.com/file/d/1U4Q94_ap4bkU6twAv0hqSEdpfYWynKo9/view?usp=sharing

**Comment by 31191022164** [comment]
Mình đóng lỗi này nhé.
