### ISSUE TITLE
[Nhóm#6] Hệ thống lưu lại Cookie đăng nhập - trang https://shcd.ueh.edu.vn/

### ISSUE THREAD

**Issue by huongptt23** [UEHMonQAQC/BI_K45#503]
a. Web Browser: Google Chrome: Phiên bản 95.0.4638.69 (Phiên bản Chính thức) (64 bit)
b. Các bước để phát hiện lỗi:
i. #1: Mở tab ẩn danh của trình duyệt và truy cập web https://shcd.ueh.edu.vn/
ii. #2: Đăng nhập tài khoản bằng email 
![image](https://user-images.githubusercontent.com/92672213/144284416-ef36cde1-17ac-4531-8a83-6c553b689fa4.png)
iii. #3: Đăng xuất tài khoản 
![image](https://user-images.githubusercontent.com/92672213/144284582-c63d46cf-115a-4d1a-9c2f-81c51037841b.png)
iv. #4. Mở 1 tab ẩn danh mới truy cập vào web https://shcd.ueh.edu.vn/ và chọn đăng nhập bằng email
![image](https://user-images.githubusercontent.com/92672213/144284915-ee1f4e4d-103d-47cc-a604-f58c2adcde62.png)
v. #5: Xem kết quả
![image](https://user-images.githubusercontent.com/92672213/144285259-7755bf0a-1308-4083-abda-81f5784002ad.png)
Link video: https://drive.google.com/file/d/17XmbVOWiB46m7smXAuNU5-SqoZyA8UeH/view?usp=sharing 
c.Kết quả thực tế: Hệ thống tự động đăng nhập trang bằng tài khoản vừa đăng xuất mà không hỏi đăng nhập lại.
d.Kết quả mong đợi: Hệ thống yêu cầu chọn lại Gmail muốn sử dụng để đăng nhập.

**Comment by 31191024332** [comment]
Thầy có đề cập đến vấn đề này ở buổi 6, khi bạn vừa logout thì nó vẫn còn giữ vết của bạn nên khi bạn đăng nhập lại thì không cần phải nhập lại gmail + password. Bạn có thể thử lại bằng cách logout xong rồi thoát tab, sau đó mở 1 web browser mới rồi tiến hành đăng nhập. Nếu nó vẫn giữ vết này thì là lỗi nhé (bạn không nên thực hiện bằng tab ẩn danh).
Bạn có thể xem thầy giải thích vấn đề này và có hướng dẫn ở buổi 6 (record 40p, ở 20:28). Cảm ơn Nhóm

**Comment by huongptt23** [comment]
Khi mình dùng tab ẩn danh thì mình thấy chrome không có lưu cookie (như hình) 
![image](https://user-images.githubusercontent.com/92672213/144652177-62769a74-2e1b-480b-beea-727b77cf1932.png)
Và mình thấy thầy có đề cập tới lỗi này ở buổi 5 (1:27:30). QA xem xét lại lỗi này giúp nhóm mình nhé. Cảm ơn QA nhiều.

**Comment by 31191024332** [comment]
Trong buổi 8 (2:35:00) thầy có thử trên brower thường. Nếu sau lần 1 chọn email, lần 2 vào không cần chọn thì mới xác nhận lỗi này được. Nhóm kiểm tra lại giúp mình nha
