### ISSUE TITLE
[Nhóm#8] Hệ thống lưu lại Cookie đăng nhập - trang https://global.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191026190** [UEHMonQAQC/BI_K45#504]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước để phát hiện lỗi:
i. #1: Chọn chế độ ẩn danh của trình duyệt và truy cập web https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/144348762-982b5cf7-0862-4791-a872-a3c1d361a97e.png)
ii. #2: Chọn sử dụng gmail để đăng nhập: 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92732798/144348936-e8cdb7b4-78fc-4436-b6e4-b7b275c889ce.png">
iii. #3: Sau khi đăng nhập thành công thì nhấn đăng xuất:
![image](https://user-images.githubusercontent.com/92732798/144348999-e402503c-034f-4f06-a174-b2257ae0a9e6.png)
iv. #4: Tiếp tục đăng nhập lại bằng cách sử dụng gmail như bước 2
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92732798/144348936-e8cdb7b4-78fc-4436-b6e4-b7b275c889ce.png">
v. #5: Xem kết quả thực hiện:
https://drive.google.com/file/d/1uJtrvGaNNrQbI-8iN-Cobu4iXKTD5Gm5/view?usp=sharing
c. Kết quả thực tế: Hệ thống tự động đăng nhập trang bằng tài khoản vừa đăng xuất mà không hỏi đăng nhập lại.
d. Kết quả mong đợi: Hệ thống yêu cầu chọn lại Gmail muốn sử dụng để đăng nhập.

**Comment by hieeusnguyeenx** [comment]
@31191026190 Thầy có đề cập đến vấn đề này ở buổi 6, khi bạn vừa logout thì nó vẫn còn giữ vết của bạn nên khi bạn đăng nhập lại thì không cần phải nhập lại gmail + password. Bạn có thể thử lại bằng cách logout xong rồi thoát tab, sau đó mở 1 web browser mới rồi tiến hành đăng nhập. Nếu nó vẫn giữ vết này thì là lỗi nhé (bạn không nên thực hiện bằng tab ẩn danh).
Bạn có thể xem thầy giải thích vấn đề này và có hướng dẫn ở buổi 6 (record 40p, ở 20:28). Cảm ơn !

**Comment by 31191026190** [comment]
Bạn xem giúp mình nhé, thầy có đề cập là mở tab mới nếu nó lưu thì vẫn chấp nhận!
Ngoài ra bạn có thể xem qua record buổi 5 ở 1:27:30 thầy có nhận xét về lỗi #287. Cảm ơn và Chúc ngủ ngon!
https://drive.google.com/file/d/1iK6Kc6MnV4W_p7UxITX7XO6NowYSaKhT/view?usp=sharing

**Comment by hieeusnguyeenx** [comment]
@31191026190  nhu Thầy đã đề cập thì đây không phải lỗi nhé. Mình cảm ơn !
