### ISSUE TITLE
[Nhóm#7] Các dòng chữ không được thẳng hàng - trang https://www.cgv.vn/

### ISSUE THREAD

**Issue by 31191024776** [UEHMonQAQC/BI_K45#52]
a. Web Browser: Microsoft Edge 95.0.1020.40
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang chủ CGV Việt Nam, chọn TIN MỚI VÀ ƯU ĐÃI trên đầu trang
![1](https://user-images.githubusercontent.com/92839124/140130558-148f8646-3213-4e69-8d82-7c98fe37c00f.JPG)

ii. #2: Hệ thống hiển thị trang Tin Mới và Ưu Đãi
![tinmoivauudai](https://user-images.githubusercontent.com/92839124/140132150-7c0519f7-2158-455c-8998-e3b12a832149.JPG)

c. Kết quả thực tế: Các dòng chữ không được thẳng hàng
d. Kết quả mong đợi: Các dòng chữ phải thẳng hàng nhau

**Comment by 31191026515** [comment]
Mình thấy trong Test Plan không có trang này á. Nhóm cập nhật Test Plan trước deadline tuần này thì mình sẽ xác nhận lỗi này nha.
