### ISSUE TITLE
[Nhóm#7] Lỗi không mã hóa mật khẩu sau khi đăng nhập - trang https://www.cgv.vn/

### ISSUE THREAD

**Issue by 31191024776** [UEHMonQAQC/BI_K45#521]
a. Web Browser: Google Chrome 96.0.4664.45
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web: https://www.cgv.vn/
![image](https://user-images.githubusercontent.com/92839124/145514641-6fd8d959-442e-43bf-892a-39e144a4df5c.png)

ii. #2: Chọn Đăng nhập đồng thời Click chuột phải -> Inspect -> Network như hình
![image](https://user-images.githubusercontent.com/92839124/145514754-8386df34-a82e-4a36-9d9e-fd4430c80c7c.png)

iii. #3 Sau khi đăng nhập thành công , click vào loginuserpost và chọn PayLoad như hình
![image](https://user-images.githubusercontent.com/92839124/145514808-51b02a86-ed4a-49fc-920f-5b1644f5eeef.png)

Video clip: https://drive.google.com/file/d/1gRtmZsEXCbO9V59aoOmH52D1jqrZV8dU/view?usp=sharing
c. Kết quả thực tế: Mật khẩu không được mã hoá
d. Kết quả mong đợi: Mật khẩu được mã hóa

**Comment by 31191026515** [comment]
Loại này thầy chỉ chấp nhận ở trang http thôi nha.
