### ISSUE TITLE
[Nhóm #7] Lỗi không mã hóa tài khoản sau khi đăng nhập - Trang https://lms.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191025157** [UEHMonQAQC/BI_K45#522]
a. Web Browser: Google Chrome 96.0.4664.45
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang web: https://lms.ueh.edu.vn
![image](https://user-images.githubusercontent.com/92876716/145516892-aa226337-7cb9-4128-a707-4cd607f0154c.png)
ii. #2: Chọn Đăng nhập đồng thời Click chuột phải -> Inspect -> Network như hình
![image](https://user-images.githubusercontent.com/92876716/145516907-b23668f5-ec6b-47cc-899c-fb19d427bbee.png)
iii. #3 Sau khi đăng nhập thành công , click vào index.php và chọn PayLoad như hình
![image](https://user-images.githubusercontent.com/92876716/145516930-f1301f31-6087-475c-94b7-f6db16c2c74f.png)
Video: https://drive.google.com/file/d/1ePJosUaIWTzXcQewnWU7-hLt-yDElEMh/view?usp=sharing
Lưu lượng truy cập:
![image](https://user-images.githubusercontent.com/92876716/145517051-1660c2ce-659e-47e0-a30f-f97bdc39eb01.png)

c. Kết quả thực tế: Mật khẩu không được mã hoá
d. Kết quả mong đợi: Mật khẩu được mã hóa

**Comment by 31191026515** [comment]
Loại này thầy chỉ chấp nhận ở trang http thôi nha.
