### ISSUE TITLE
[Nhóm#8] - Lỗi Phi Chức Năng - Tốc độ load web chậm khi nhiều user truy cập cùng lúc - Trang Web http://bit.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181023259** [UEHMonQAQC/BI_K45#523]
a. Web Browser: Google Chrome 96.0.4664.45
b. Các bước phát hiện lỗi:
i. #1: Mở phần mềm Jmester, kích chuột phải vào Test Plan -> Add -> Threads -> Threads Group
![image](https://user-images.githubusercontent.com/92772571/145517081-aa8bc2fc-f8f3-49e0-bb52-865b9df4df79.png)
ii. #2:  Điền thông tin như hình
![image](https://user-images.githubusercontent.com/92772571/145517150-1900a85d-7ee1-45f3-b5f6-ea4ab6eafd02.png)
iii. #3: Kích chuột phải vào Thread Group -> Add -> Sampler -> HTTP Request
![image](https://user-images.githubusercontent.com/92772571/145517300-a7873928-c203-4e8f-871a-a44b97662eae.png)
iv: #4: Điền thông tin như hình
![image](https://user-images.githubusercontent.com/92772571/145517399-29f55c52-f636-4d5b-8bd9-bf774cf557b8.png)
v: #5: Kích chuột phải vào Thread Group -> Add -> Listener -> View Results Tree và bấm Run
![image](https://user-images.githubusercontent.com/92772571/145517588-b902ba48-9bc9-4eee-9c83-b14b86a5dfd5.png)
c. Kết quả thực tế: Load time quá lớn
![image](https://user-images.githubusercontent.com/92772571/145517875-ff8e5eef-49c6-4c36-ad84-361cf8bc2156.png)
![image](https://user-images.githubusercontent.com/92772571/145517913-c553694b-9dc9-4186-bc02-1e063f86a023.png)
d. Kết quả mong đợi: thời gian load nhanh hơn

**Comment by hieeusnguyeenx** [comment]
@31181023259 Thầy chỉ cho 1 lỗi dùng tool áp dụng cho 1 trang trường thôi, bạn bổ sung lỗi khác giúp mình nhé
