### ISSUE TITLE
[Nhóm#7] Chất lượng hình ảnh banner bị kém - trang https://smartlib.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191024776** [UEHMonQAQC/BI_K45#56]
a. Web Browser: Microsoft Edge 95.0.1020.40
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang https://smartlib.ueh.edu.vn/, nhìn vào banner đầu tiên sẽ thấy bị mờ so với các banner khác

Banner đầu tiên
![GUI- Banner bị mờ](https://user-images.githubusercontent.com/92839124/140164496-c4e2d85f-01e0-499b-9ee4-8998f212cf89.JPG)

Banner khác
![GUI-So sánh banner](https://user-images.githubusercontent.com/92839124/140164547-b3acb6d5-41cc-4175-9195-1b5317f0b027.JPG)

c. Kết quả thực tế: Chất lượng hình ảnh banner bị mờ, không đồng đều
d. Kết quả mong đợi: Chất lượng hình ảnh tất cả banner phải được rõ nét

**Comment by 31191026515** [comment]
Phần ảnh mờ vì người chỉnh/chụp xóa có chủ ý như vậy, không phải lỗi hiển thị. Mình k ghi nhận lỗi này nhé
