### ISSUE TITLE
[Nhóm#5] Lỗi định dạng, văn bản bị lệch khỏi các bullets trong bài viết - trang https://youth.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191021279** [UEHMonQAQC/BI_K45#63]
a. Web Browser: Opera 81.0.4196.31
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang https://youth.ueh.edu.vn
![1](https://user-images.githubusercontent.com/92701347/140289777-8bfe31bc-99de-4034-a4b8-6bf4d7d2777f.png)
ii. #2: Tại thanh Tìm kiếm nhập "dấu chân" và bấm tìm kiếm
![font](https://user-images.githubusercontent.com/92701347/140290314-b4bea36c-69af-419f-8080-2dbd3cca9c0f.png)
iii. #3: Tại trang Kết quả tìm kiếm "dấu chân" chọn bài viết số 2- tên Dấu chân sử Việt
![font2](https://user-images.githubusercontent.com/92701347/140290780-d7415abd-ea7e-4574-b009-1270be538ef6.png)
iv. #4: Đọc nội dung bài viết:
![font3png](https://user-images.githubusercontent.com/92701347/140291007-a642d08c-4565-4a09-bd2e-7a46feff2bfa.png)
![font4](https://user-images.githubusercontent.com/92701347/140294718-5978f2df-4f6c-4247-b64d-69b44b97c879.png)
c. Kết quả thực tế: lỗi định dạng văn bản, văn bản bị lệch khỏi các bullets
d. Kết quả mong đợi: văn bản được căn chỉnh đúng định dạng

**Comment by 31191024332** [comment]
Nhóm 5 kiểm tra nguyên tắc đặt title giúp mình nhé

**Comment by 31191024332** [comment]
Đây không phải lỗi GUI mà là lỗi format văn bản của người upload lên. Mình xin phép không xác nhận lỗi này. Cảm ơn Nhóm
