### ISSUE TITLE
[Nhóm#7] Kết quả của Filter theo Giờ không đúng- trang https://smartlib.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191024776** [UEHMonQAQC/BI_K45#74]
a. Web Browser: Microsoft Edge 95.0.1020.40, Chrome 95.0.4638.69
b. Các bước phát hiện ra lỗi:
i. #1: Truy cập vào trang https://smartlib.ueh.edu.vn/ chọn phần được khoanh đỏ
![Chọn](https://user-images.githubusercontent.com/92839124/140320291-d6981a6c-0ce0-46fc-bd71-4fa47d5cbcaf.JPG)

ii. #2: Chọn phần Room Booking để truy cập vào trang Room Booking
![rb](https://user-images.githubusercontent.com/92839124/140320383-a5989454-b51e-415e-bd98-302a22d3633a.JPG)

iii. #3: Lúc này hệ thống hiển thị danh sách phòng tại ngày hiện tại đang truy cập, chọn thanh Filter,
![Filter-Day1](https://user-images.githubusercontent.com/92839124/140320539-95882951-579e-4fce-ac95-3f7f68292b30.JPG)

iv. #4 Chọn giờ muốn đặt phòng, thường sẽ chọn vào giờ trong tương lai, để ý vào thời gian ở góc dưới bên tay trái
![Filter-Time2_LI](https://user-images.githubusercontent.com/92839124/140321748-bfe40cda-1208-4da9-8a4c-c057c7feca77.jpg)

v. #5: Nhấn Apply, hệ thống tắt sidebar và trả về kết quả " No rooms found"
![Filter-Time3_LI](https://user-images.githubusercontent.com/92839124/140321877-165c25f9-61e5-4811-abcd-ee3e9b956da4.jpg)

**Comment by 31191027399** [comment]
Cái này xác minh lỗi chưa á ?
@31191026515

**Comment by 31191026515** [comment]
Cái này Trang nói closed lại r á @31191027399
