### ISSUE TITLE
[Nhóm#07]Hiệu suất load trang không đạt (Mobile và Desktop) - Trang https://smartlib.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191025157** [UEHMonQAQC/BI_K45#80]
a. Web browers: Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1 Truy cập vào trang https://developers.google.com/speed/pagespeed/insights/
![image](https://user-images.githubusercontent.com/92876716/140333355-14972b9a-424a-405b-b7c4-d5be03d10b2d.png)
ii. #2 Nhập địa chỉ của trang https://smartlib.ueh.edu.vn vào và ấn nút ANALYZE
![image](https://user-images.githubusercontent.com/92876716/140333699-bef70bc4-8253-4ff2-8758-f759cf3cee43.png)
iii. #3 Chọn Mobile và Desktop để xem kết quả
![image](https://user-images.githubusercontent.com/92876716/140334081-b0186001-7129-4345-820e-47b0ca0fc73f.png)
![image](https://user-images.githubusercontent.com/92876716/140334196-e6918779-d2e6-463a-a458-fbb06825cbb6.png)
c. Kết quả thực tế: Tốc độ load trang không đạt ở mobile và desktop.
d. Kết quả mong đợi: Tốc độ phản hồi của trang sẽ được cải thiện để người dùng có thể sử dụng nhanh hơn (trên 89%).

**Comment by 31191026515** [comment]
Mình không xác nhận lỗi này vì sử dụng tool nha
