### ISSUE TITLE
[Nhóm#9] Lỗi căn chỉnh dòng - trang: https://vieclam.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191025549** [UEHMonQAQC/BI_K45#81]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://vieclam.ueh.edu.vn/
![Screenshot (102)](https://user-images.githubusercontent.com/92793356/140337103-852d67da-637e-4ef8-95a6-c7cd0499060e.png)
ii. #2: Zoom in trang chủ lên (>=175%) và kéo xuống cuối trang
![175%](https://user-images.githubusercontent.com/92793356/140337280-a7e1a934-3feb-4354-8ce1-e6ebe0f0e5fc.png)
c. Kết quả thực tế: Trong mục việc làm theo ngành, dòng Việc làm bán hàng và Việc làm Điện-điện tử căn chỉnh không đều
![vieclam](https://user-images.githubusercontent.com/92793356/140337367-f481c36d-1064-47a3-ae57-b6629dd04d94.png)
d. Kết quả mong đợi: Các dòng được căn chỉnh đều nhau

**Comment by 31191025698** [comment]
Zoom lên các link vẫn click được. Không phải lỗi.
