### ISSUE TITLE
[Nhóm#9] Lỗi căn lề - trang: https://vieclam.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191025549** [UEHMonQAQC/BI_K45#82]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://vieclam.ueh.edu.vn/
ii. #2: Kéo xuống và chọn bất kỳ một công việc
![viec](https://user-images.githubusercontent.com/92793356/140338379-c3669b4d-a149-48af-a9b0-710953c9e0a2.png)
iii. #3: Zoom in trang công việc lên ( >=250%) và kéo xuống mục Công việc phù hợp khác
![250](https://user-images.githubusercontent.com/92793356/140338653-d2c4f5b4-aa01-470c-b0b8-d89b6edb059f.png)
c. Kết quả thực tế: Lề của công việc không được căn đều giữa trang khi zoom in
![Screenshot (105)](https://user-images.githubusercontent.com/92793356/140338894-c39da194-15e7-4287-8c50-30c193caf09f.png)
d. Kết quả mong đợi: Lề được căn đều, công việc được đặt ở giữa

**Comment by 31191025698** [comment]
Zoom lên không bị vỡ, input không bị che,.... Không phải lỗi.
