### ISSUE TITLE
[Nhóm#9] Điều hướng lỗi khi click vào banner quảng cáo - trang: https://phonhadat.net/

### ISSUE THREAD

**Issue by 31191025549** [UEHMonQAQC/BI_K45#83]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://phonhadat.net/
![Screenshot (106)](https://user-images.githubusercontent.com/92793356/140341888-093eb896-bd93-4e8d-8a0d-9600430116f0.png)
ii. #2: Click vào banner quảng cáo
![phd](https://user-images.githubusercontent.com/92793356/140343914-e40cbe45-2005-4a93-a2bd-0a6569da766c.png)
c. Kết quả thực tế: Hệ thống báo không thể truy cập trang Web.
![Screenshot (107)](https://user-images.githubusercontent.com/92793356/140344474-34f810b8-feae-4ad4-83aa-9ef211a91cec.png)
d. Kết quả mong đợi: Hệ thống điều hướng đến trang Web của quảng cáo.

**Comment by 31191025698** [comment]
Lỗi bên trang web quảng cáo, phonhadat chỉ có nhiệm vụ nhúng banner, không chấp nhận lỗi.
