### ISSUE TITLE
[Nhóm#9] Lỗi chuyển đổi ngôn ngữ không đầy đủ - trang https://phonhadat.net/

### ISSUE THREAD

**Issue by 31191026463** [UEHMonQAQC/BI_K45#85]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://phonhadat.net/
![image](https://user-images.githubusercontent.com/92785792/140317556-3f2a805b-f189-4cf8-aed6-ea969c055fcd.png)
ii. #2:  Kích chuột phải tại 1 khoảng trống trên trang sau đó chọn "Translate to English" 
![Ngôn ngữ - 1](https://user-images.githubusercontent.com/92785792/140365114-fdc95e8c-a87a-42ed-8179-846816bab83b.PNG)
ii. #3: Xem kết quả
![ngôn ngữ - 2](https://user-images.githubusercontent.com/92785792/140365977-32d0cbc7-16cb-4223-bcd4-c78fbcfd02c7.PNG)
c. Kết quả thực tế: Ngôn ngữ được chuyển đổi chưa đầy đủ
d. Kết quả mong muốn: Tất cả nội dung phải được chuyển đổi sang Tiếng Anh

**Comment by 31191025698** [comment]
Đây không phải là chức năng của trang web phát triển. Đây là extension của trình duyệt, không trong phạm vi trang web.
