### ISSUE TITLE
[Nhóm#7] Hiệu suất load trang không đạt (Mobile và Desktop) - Trang https://www.cgv.vn/ 

### ISSUE THREAD

**Issue by 31191025157** [UEHMonQAQC/BI_K45#86]
a. Web browers:  Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1 Truy cập vào trang https://developers.google.com/speed/pagespeed/insights/
![image](https://user-images.githubusercontent.com/92876716/140374294-3fdc9b27-a915-4999-badd-047c8b62a03c.png)
ii. #2 Nhập địa chỉ của trang https://www.cgv.vn vào và ấn nút ANALYZE
![image](https://user-images.githubusercontent.com/92876716/140374572-aec70423-f730-4b05-b7c4-b12c9fe9cd44.png)
iii. #3 Chọn Mobile và Desktop để xem kết quả
![image](https://user-images.githubusercontent.com/92876716/140374967-bf118530-e7cb-4b72-afd6-bbafb220ac87.png)
![image](https://user-images.githubusercontent.com/92876716/140375528-5b88d9da-1c67-47f2-96d4-f7888179e61b.png)
c. Kết quả thực tế: Tốc độ load trang không đạt ở mobile và desktop.
d. Kết quả mong đợi: Tốc độ phản hồi của trang sẽ được cải thiện để người dùng có thể sử dụng nhanh hơn (trên 89%).

**Comment by 31191026515** [comment]
Mình không xác nhận lỗi này vì sử dụng tool nha
