### ISSUE TITLE
[Nhóm#8] Lỗi hiển thị sai thông tin Tên bỏ trống - trang https://global.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31191026190** [UEHMonQAQC/BI_K45#90]
a. Web Browser: Google Chrome 95.0.4638.69
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140379175-3cf24b31-b58f-4245-9227-dc98e0cdb030.png)
ii. #2 Đăng nhập vào trang: https://global.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/92732798/140379320-b5fb6214-4ed8-4636-869a-78ef95c0bbab.png)
iii. #3 Nhấp vào tên người dùng ở góc phải, chọn hồ sơ:
![image](https://user-images.githubusercontent.com/92732798/140379432-4d11bc4a-89cf-408d-b05a-c89136faf989.png)
iv. #4 Chọn chức năng Sửa hồ sơ cá nhân:
![image](https://user-images.githubusercontent.com/92732798/140379536-82ad6265-c660-4e44-801b-cb30de037d0b.png)
v. #5 Xóa thông tin trong ô Tên:
![image](https://user-images.githubusercontent.com/92732798/140379916-1c2c79c4-9388-49a7-b3ec-4e78263310ff.png)
![image](https://user-images.githubusercontent.com/92732798/140380020-7c271a3f-6fbb-41da-9ad5-f84c17265af5.png)
c. Kết quả thực tế: Hiển thị báo lỗi sai thông tin ô để trống.
d. Kết quả mong đợi: Hiển thị báo lỗi đúng thông tin ô để trống:"Xin cho biết Tên".

**Comment by hieeusnguyeenx** [comment]
Xác nhận lỗi
