### ISSUE TITLE
[Nhóm#4] Lỗi bị khuất chữ khi phóng to 150% - trang https://digital.lib.ueh.edu.vn/  

### ISSUE THREAD

**Issue by thanhha02621** [UEHMonQAQC/BI_K45#93]
a. Web Browser: Google Chrome: Phiên bản 95.0.4638.69 (Phiên bản Chính thức) (64 bit)                          
b. Các bước để phát hiện lỗi:                        
i. #1: Vào trang chủ Digital library: https://digital.lib.ueh.edu.vn/   
![Trang chủ](https://user-images.githubusercontent.com/87024797/140382430-9d643740-570e-49c6-b6b1-e50721733867.jpg)                   
ii. #2: Phóng to màn hình 150%
c. Kết quả thực tế: Chữ "Browse" bị khuất chỉ còn "wse"  
![Lỗi khuất chữ](https://user-images.githubusercontent.com/87024797/140382715-cb51d7b0-f930-459d-b736-b3ae6352e30a.jpg)                  
d. Kết quả mong đợi: Chữ "Browse" hiện đầy đủ

**Comment by 31191022164** [comment]
Hiện tại mình zoom lên 150% thì chữ Browse bị che. Nhưng vẫn click được. 
Chỗ này thầy có giải đáp thắc mắc của bạn Thảo trong buổi học số 4 - lúc 10h53 AM, ngày 06/11/2021 
(phút thứ 3:33:00)
=> mình từ chối lỗi này nha
